### ISSUE TITLE
pytorch 1.1.0 训练时候距离是NAN

### ISSUE THREAD

**Issue by pxpeng** [JDAI-CV/fast-reid#100]
首先感谢您非常好的工作。
我碰到一个奇怪的bug，想和您讨论一下。

我在1.1.0上训练的时候，刚开始程序可以运行，但rank1 只有1%。。。训一会儿之后测试时候就报错了，距离是NAN。
我把non_local模块迁移到我自己的代码里，训一阵子测试的时候也会出现距离是NAN的BUG
看代码感觉non_local 用的也是一些常规的算子，为什么会在1.1.0里面出问题呢。

**Comment by L1aoXingyu** [comment]
我觉得是初始化的问题，因为 non-local layer 是没有 pretrain 的，所以容易出问题。
