### ISSUE TITLE
circle loss 出现nan

### ISSUE THREAD

**Issue by thenighthunter0** [JDAI-CV/fast-reid#102]
你好，在使用circle loss训练的时候出现nan, fastreid有相关的解决机制吗，还是circle loss代码的问题？

**Comment by L1aoXingyu** [comment]
请把你的配置文件发出来

**Comment by pxpeng** [comment]
我也跟风问一下，感觉circle loss非常敏感。我把circle loss的迁移到我的代码替换掉softmax，要么就是nan，要么就是越训越差。。。有点神奇

**Comment by L1aoXingyu** [comment]
circle loss 需要调参，直接替换是不 work 的，而且这也和数据集有关，除了 face 和 reid 的数据之外，其他数据可能并不好用。

**Comment by thenighthunter0** [comment]
多谢，大概率是没调参的原因
