### ISSUE TITLE
Can not achieve the result in paper.

### ISSUE THREAD

**Issue by zhangxiaobaibai** [JDAI-CV/fast-reid#106]
Hi. I run the partial re-id code with the default parameter. However, I can only achieve rank-1=76.0% on PartialREID dataset, which is far below the result in your paper(82.7%).

**Comment by Mrkkew** [comment]
I have the same problem with you. And I cannot find the partial-iLIDS dataset. Can you share the dataset?

**Comment by L1aoXingyu** [comment]
We have updated code, please try again.
