### ISSUE TITLE
how to train?

### ISSUE THREAD

**Issue by vicwer** [JDAI-CV/fast-reid#109]
hello,
    how to train?
    when I run `python train_loop.py`:
```
import fastreid.utils.comm import comm
ModuleNotFoundError: No module named `fastreid`
```

**Comment by L1aoXingyu** [comment]
check here

https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line

**Comment by vicwer** [comment]
> check here
> 
> https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line

thanks，when I use 2gpus train `Market bagtricks-Res50` model, rank1=80%+.  How to set the gpu nums?
