### ISSUE TITLE
partial person reid

### ISSUE THREAD

**Issue by zhanghongruiupup** [JDAI-CV/fast-reid#110]
请问关于fast-reid中的DSR代码尚未更新完毕？比如框架图中所示要用到的non-local，autoaug等在partial_market.yaml中并没有明确写出

**Comment by lingxiao-he** [comment]
You can run the new setting, and we have updated the code and datasets.

**Comment by Mrkkew** [comment]
Thank you for your reply. I looked for the goole drive given in the README.md, but it showed that I have no right to visit it.

**Comment by Mrkkew** [comment]
> You can run the new setting, and we have updated the code and datasets.
Thank you for your reply. I looked for the goole drive given in the README.md, but it showed that I have no right to visit it.
