### ISSUE TITLE
arcface

### ISSUE THREAD

**Issue by zhukuan96** [JDAI-CV/fast-reid#111]
When I use arcface loss, the loss is NAN. How can I fix this issue?

**Comment by L1aoXingyu** [comment]
Have fixed this problem, loss NaN reason can check this commit https://github.com/JDAI-CV/fast-reid/commit/3840f3f79a49a3544fc32509f897101d3634e574
Have fixed this problem, loss NaN reason can check this commit https://github.com/JDAI-CV/fast-reid/commit/3840f3f79a49a3544fc32509f897101d3634e574
