### ISSUE TITLE
label(-1)in test of market1501

### ISSUE THREAD

**Issue by VincentZ-2020** [JDAI-CV/fast-reid#112]
for img_path in img_paths:
            pid, camid = map(int, pattern.search(img_path).groups())
            if pid == -1:
                continue  # junk images are just ignored
            assert 0 <= pid <= 1501  # pid == 0 means background
            assert 1 <= camid <= 6
            camid -= 1  # index starts from 0
            data.append((img_path, pid, camid))

why remove label(-1)? 
In my view, label(-1) is a part of test as obstacle.

**Comment by VincentZ-2020** [comment]
In <Scalable Person Re-identification: A Benchmark>, i found the following that "Market-1501 is the largest person re-id dataset featured by 32,668+500K bboxes and 3,368 query images."
And in the readme.txt of Market1501, also found that "1. "bounding_box_test" file. This file contains 19732 images for testing. "
I see that label(-1) are not in class 751 ,but the test ought to include the label(-1).

**Comment by L1aoXingyu** [comment]
We just refer to [deep-person-reid](https://github.com/KaiyangZhou/deep-person-reid/blob/fe0f39fb678fb7c2035252d7d5caf52790f5561c/torchreid/data/datasets/image/market1501.py#L79)

In reality, label with -1 will not appear because we have better detectors.
