### ISSUE TITLE
How does fastreid.utils.registry work?

### ISSUE THREAD

**Issue by linjiawen2019** [JDAI-CV/fast-reid#114]
@L1aoXingyu Hi, I found that when building model and train set, they both end at calling fastreid.utils.Registry, I didn't understand how this function works. Can I train using my own dataset by modifying configs?

1. in fastreid.datasets.__init__.py：
from ...utils.registry import Registry：

DATASET_REGISTRY = Registry("DATASET")
DATASET_REGISTRY.__doc__ = """
Registry for datasets
It must returns an instance of :class:`Backbone`.
"""

2. in  fastreid.modeling.meta_arch.build.py：
from ...utils.registry import Registry

META_ARCH_REGISTRY = Registry("META_ARCH")  # noqa F401 isort:skip
META_ARCH_REGISTRY.__doc__ = """
Registry for meta-architectures, i.e. the whole model.
The registered object will be called with `obj(cfg)`
and expected to return a `nn.Module` object.
"""

**Comment by L1aoXingyu** [comment]
You can refer partialreid project https://github.com/JDAI-CV/fast-reid/blob/3840f3f79a49a3544fc32509f897101d3634e574/projects/PartialReID/partialreid/partialbaseline.py#L12

In your own project, you can register a new dataset, `meta_arch`, `backbone`, and `head`, then call them by modifying configs.
The only thing you need to notice is importing all registered modules.

**Comment by linjiawen2019** [comment]
> You can refer partialreid project
> 
> https://github.com/JDAI-CV/fast-reid/blob/3840f3f79a49a3544fc32509f897101d3634e574/projects/PartialReID/partialreid/partialbaseline.py#L12
> 
> In your own project, you can register a new dataset, `meta_arch`, `backbone`, and `head`, then call them by modifying configs.
> 
> The only thing you need to notice is importing all registered modules.

Thank you.
