### ISSUE TITLE
triplet loss circle loss ， batch  sample负样本

### ISSUE THREAD

**Issue by zoujialong9012** [JDAI-CV/fast-reid#116]
BalancedIdentitySampler batch sample没看出负样本sample 都是相同pid 选取。 NaiveIdentitySampler 才有取neg 过程， 但默认都是BalancedIdentitySampler？

**Comment by L1aoXingyu** [comment]
balanced sampler 和 naive sampler 都是按照 id 采样，比如一个 batch 里面采样了16个id，每个id采样了4张图，那么每张图片和自己id里面的图片构成 positive sample，和其他 id 的图片构成 negative sample。

**Comment by zoujialong9012** [comment]
明白了，  sampler __iter__ 不满一个batch size 会继续再等待sampler满足； 
for kid in indices:   //每次抽取 不同num_instances个数 pid  实际上等到len(indices) 个数完才满一个batch size

**Comment by zoujialong9012** [comment]
明白了， sampler iter 不满一个batch size 会继续再等待sampler满足；
for kid in indices: //每次抽取 num_instances个数 相同pid 实际上等到len(indices) 个数pid才能满足一个batch size

**Comment by zoujialong9012** [comment]
明白了， sampler iter 不满一个batch size 会继续再等待sampler满足；
for kid in indices: //每次抽取 num_instances个数相同pid 实际上等到len(indices) 个数pid才能满足一个batch size ，   random.choice(self.pid_index[self.pids[kid]]) 也有可能每次抽取到相同的 id，  大趋势是平衡的

**Comment by zoujialong9012** [comment]
明白了， sampler iter 不满一个batch size 会继续再等待sampler满足；
for kid in indices: //每次抽取 num_instances个数相同pid 实际上等到len(indices) 个数pid才能满足一个batch size ， random.choice(self.pid_index[self.pids[kid]]) 也有可能每次抽取到多组相同的 id，如果 全相同的话那么就没有negative sample， 大趋势是平衡的 。
