### ISSUE TITLE
About the knowledge distillation module

### ISSUE THREAD

**Issue by YingjieYin** [JDAI-CV/fast-reid#118]
what about the experimental results for knowledge distillation module? Will you have a plan to release the code?

**Comment by L1aoXingyu** [comment]
We will release the code when finishing cleaning up.

**Comment by zhanghongruiupup** [comment]
xingyu 大佬，关于蒸馏 有# train BagTricksIBN50 as teacher model  和 # train BagTricksIBN18 as student model 
是不是如果我已经训练好了一个基础模型，只需要使用小一点的模型做学生网络，只需要运行
CUDA_VISIBLE_DEVICES=$CUDA python ./projects/DistillReID/train_net.py --kd --config-file ./projects/DistillReID/configs-bagtricks-ibn-dukemtmcreid/KD-bot50ibn-bot18ibn.yml MODEL.DEVICE "cuda:0"
对吗
