### ISSUE TITLE
我用自己的测试代码测试结果比这里低4个点

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#121]
我看了下输出特征都是一样的，甚至dist都是一样的，但是经过cmc评测函数之后的结果就不一样了

**Comment by L1aoXingyu** [comment]
你的 cmc 评测函数是自己写的吗？

**Comment by guanyonglai** [comment]
不是自己写的，用的MGN开源代码里面的，

**Comment by guanyonglai** [comment]
三个公开数据集测试的结果都一致，我自己做的数据集测试结果不一致

**Comment by L1aoXingyu** [comment]
也许是你自己的数据集做的和公开数据集不太一致，如果你确定你的测试方法对你制作的数据集是正确的，你可以直接把 `fastreid` 中的测试方式换成你自己的，方式非常简单，替换下面这一行代码即可。

https://github.com/JDAI-CV/fast-reid/blob/3840f3f79a49a3544fc32509f897101d3634e574/tools/train_net.py#L28

**Comment by guanyonglai** [comment]
debug了一个周末终于找到原因了，就是因为relable_cam的问题。因为公开数据集跨镜少，整个数据集也就几个镜头，所以query，bounding_box_test和bounding_box_train可以共用一套cam2label，但是我自己的数据集跨镜多，三个dataset不能共用一套cam2label，就导致在测试中去除同镜头同id图片时有些没有去掉。而我自己的测试代码没有relable_cam，所以不存在这个问题。这才导致了测我自己的数据集时结果偏低

**Comment by guanyonglai** [comment]
感谢作者耐心解答

**Comment by guanyonglai** [comment]
你好，我在做dataset的时候把 relable_cam 改成False，但是经过Dataloader之后camid的输出就变成了['<map object at 0x7f6b3bc27190>', '<map object at 0x7f6b3bc27390>', '<map object at 0x7f6b3bc27b90>']，输出转list也不行。请问如何修改这一处报错呢

**Comment by sky186** [comment]
@guanyonglai 
您好我想请教您
测试中为什么要 去除同镜头同id图片，

**Comment by guanyonglai** [comment]
> 您好我想请教您
> 测试中为什么要 去除同镜头同id图片，

因为reid实际的任务是做多个镜头下的行人检索，为了更贴合实际，测试的时候一般会去掉同镜头同id的图片，因为这样的图片检索起来往往比较简单，简单样本对模型的能力说服力不强
