### ISSUE TITLE
rank1准确率85%+

### ISSUE THREAD

**Issue by vicwer** [JDAI-CV/fast-reid#122]
你好，
        我对代码没有任何改动，使用单卡P40训练，训练指令如下
```python
python train_net.py --config-file=../configs/Market1501/bagtricks_R50.yml
```

数据集使用Market，预训练模型使用`~/.cache/torch/checkpoints/resnet50-19c8e357.pth`，但在训练过程中eval的rank1最高就85%+，这是正常的吗？

**Comment by L1aoXingyu** [comment]
请把你的保存模型路径下的配置文件 `config.yaml` 贴出来看一些

**Comment by vicwer** [comment]
你好，
        由于服务器在内网，没办法贴代码。不过我找到问题了。我以为预训练模型放在cache路径下就不需要自己手动添加路径了。。
我现在预训练模型路径添加到config中，`PRETRAIN_PATH= "/home/.cache/torch/checkpoints/resnet50-19c8e357.pth"`,然后运行`python train_net.py --config-file=../configs/Market1501/bagtricks_R50.yml`，报错如下
```python
state_dict=torch.load(pretrain_path)["model"]
KeyError: 'model'
```
我看了一下load model后的键，都是各层layer权重的变量名，我应该如何修改？

**Comment by L1aoXingyu** [comment]
如果你使用的是 `imagenet pretrain model`，你不需要在 config 文件中申明具体的路径，代码会自动找到 `.cache/torch/checkpoints` 下面的 pretrain model，导入成功的话，会出现下面的 logging

![image](https://user-images.githubusercontent.com/19245504/85245920-ad518780-b47b-11ea-9cc4-fa32563504b7.png)

这是我训练到 14000 iter 的测试结果

![image](https://user-images.githubusercontent.com/19245504/85245839-682d5580-b47b-11ea-94a7-cb4a63a0b0ce.png)

**Comment by vicwer** [comment]
谢谢，
        我使用的是imagenet 预训练模型，也出现了`load model pretrain from torchvision`的log，我对代码和数据集没有任何改动，我再训练一遍看看准确率如何，然后再请教您，多谢。

**Comment by vicwer** [comment]
可能是我clone代码早一些，在config中删掉`USE_COSINE_DIST:False`之后就eval准确率就正常了，多谢～
