### ISSUE TITLE
config 参数问题

### ISSUE THREAD

**Issue by sky186** [JDAI-CV/fast-reid#123]
@JinkaiZheng 
您的工程文件代码比较全，我想请教您几个问题

1、FREEZE_ITERS: 2000  作用？
2、max_iter  ，是 1个epoch  =数据量 / batch  例如一个数据是10个iter ,   max_iter最大的迭代= epoch数量  * 每个epoch 的迭代

3、DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)  #要改成DukeMTMC?
这里我用自己的数据做训练格式变成 Market1501 数据格式，
测试数据的评估，我只是把数据读取路径 改成duke的,   测试结果不对，训练收敛
是我改动的方式错了吗？

**Comment by L1aoXingyu** [comment]
https://github.com/JDAI-CV/fast-reid/issues/124
