### ISSUE TITLE
DukeMTMC

### ISSUE THREAD

**Issue by sky186** [JDAI-CV/fast-reid#124]
@JinkaiZheng 
您的工程文件代码比较全，我想请教您几个问题

1、FREEZE_ITERS: 2000  作用？
2、max_iter  ，是 1个epoch  =数据量 / batch  例如一个数据是10个iter ,   max_iter最大的迭代= epoch数量  * 每个epoch 的迭代

3、DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)  #要改成DukeMTMC?
这里我用自己的数据做训练格式变成 Market1501 数据格式，
测试数据的评估，我只是把数据读取路径 改成duke的,   测试结果不对，训练收敛
是我改动的方式错了吗？

**Comment by L1aoXingyu** [comment]
1. freeze_iter 是为了固定住 backbone，只训练 head，这样结果会更稳定。

2. max_iter 是通过这个方式计算得到的。

3. 如果你要使用自己的数据集进行训练，需要对数据集进行注册，然后 import 这个注册的数据集，例子可以先参考下面
https://github.com/JDAI-CV/fast-reid/blob/3840f3f79a49a3544fc32509f897101d3634e574/projects/PartialReID/partialreid/partialbaseline.py#L12
我们很快会提供 tutorial。

**Comment by sky186** [comment]
@L1aoXingyu 
1、代码 有个问题很困惑 model.train()位置
class SimpleTrainer(TrainerBase):

      ‘’‘
     这句 model.train() 为什么放在这里，不能放在如下位置吗
      class DefaultTrainer(SimpleTrainer):
            ...
            self.register_hooks(self.build_hooks())  
            model.train()  #放在这里不行吗，执行顺序也是执行到这里，再执行train
  放在那里我觉得很奇怪  train相关的代码接口， 放在加载数据的前面

     ’‘’
        model.train()  
        self.model = model
        self.data_loader = data_loader
        self._data_loader_iter = iter(data_loader)
        self.optimizer = optimizer

2、 第二个问题是，代码里有 sbs 相关训练运行都会报错，cuda memory 有问题
训练测试了几轮之后，2000iter ，之后再训练就有问题，报内存有问题，这可能是哪个优化结构引起的吗？
例如  D:\Projects\reid\fast-reid\configs\DukeMTMC\mgn_R50-ibn.yml
         D:\Projects\reid\fast-reid\configs\DukeMTMC\sbs_R50-ibn.yml

其他的例如
bagtricks_R50.yml
bagtricks_R50-ibn.yml 都正常迭代运行

**Comment by JinkaiZheng** [comment]
您好！欢迎关注我们的工作~
看您的描述，应该是显存out of memory(OOM)了，因为按照默认设置，sbs在2000 iters之后会解冻model层，显存会出现暴增，训练时长也会变长，这些都是正常现象。如果是这样的话，建议您改小batch size（_SOLVER.IMS_PER_BATCH_）即可，当然相应的iters也需要依据batch size重新计算。
如果不是OOM的问题，方便把输出结果，以及config.yaml贴一下吗？

**Comment by sky186** [comment]
@JinkaiZheng 

谢谢您的回复，应该是这个原因导致的 
这边添加新的测试数据，修改有什么注意的吗？ 数据格式类似market1501，但是相机信息camid 没有，都写成固定是1

**Comment by JinkaiZheng** [comment]
u r welcome.
1、没有camera信息，camid都写成1是可以的。
2、数据格式方面，建议您把相应的变量输出，对照查看和原版数据格式是否一致即可。如：market1501.py，可以将process_dir函数的返回值print一下，倘若自己修改的不对，根据输出再改就好了。

**Comment by sky186** [comment]
自己的数据集训练，因为数据label 不是连续的，数据处理里面加了 relabel属性，数据label 从0 开始 ，训练没有背景数据，有问题吗？
if relabel: pid = pid2label[pid]  # label  start 0 1 2......
            dataset.append((img_path, pid, camid))

**Comment by JinkaiZheng** [comment]
这样改可以的，但是不加这些也没有问题，因为[CommDataset类](https://github.com/JDAI-CV/fast-reid/blob/4cc157a12fe6c2ea5babe2477fb5aa6d337ec302/fastreid/data/build.py#L29)里面已经加relabel了。

**Comment by sky186** [comment]
@L1aoXingyu 

adam() 优化器，有自己的学习率自动衰减
config 参数有 外在学习率衰减， STEPS:
  我不明白， 这两者结合 学习率到底是怎么变化的
SOLVER:
  MAX_ITER: 160000  #64 batch  41epoch
  STEPS: [50000, 100000,150000]  # multi lr
  WARMUP_ITERS: 20000

**Comment by sky186** [comment]
@L1aoXingyu 
并行训练 如果采用分布式训练接口   syncbn 这个参数，是否还需要昵？为什么代码里面没有采用这个接口昵？
torch.nn.parallel.DistributedDataParallel

syncbn 这个我理解就是  DataParallel  并行训练时候 bn层的优化，单卡是用不到的？

**Comment by sky186** [comment]
@L1aoXingyu 
mgn_R50-ibn.yml    duke 数据集，参数没有改，训练精度是89.3%top1
您的 readme，duke数据集是91.6%  ，，我参数没有改动，添加了 with ibn ： true

[06/29 23:31:52] fastreid.data.datasets.bases INFO: => Loaded DukeMTMC
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   subset   | # ids | # images | # cameras
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   query    |   702 |     2228 |         8
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   gallery  |  1110 |    17661 |         8
[06/29 23:31:52] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/29 23:31:52] fastreid.evaluation.evaluator INFO: Start inference on 19889 images
[06/29 23:31:55] fastreid.evaluation.evaluator INFO: Inference done 11/311. 0.1275 s / img. ETA=0:00:39
[06/29 23:32:25] fastreid.evaluation.evaluator INFO: Inference done 196/311. 0.1528 s / img. ETA=0:00:18
[06/29 23:32:44] fastreid.evaluation.evaluator INFO: Total inference time: 0:00:49.936985 (0.163193 s / img per device)
[06/29 23:32:44] fastreid.evaluation.evaluator INFO: Total inference pure compute time: 0:00:46 (0.153538 s / img per device)
[06/29 23:34:37] fastreid.engine.defaults INFO: Evaluation results for DukeMTMC in csv format:
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: Rank-1
[06/29 23:34:37] fastreid.evaluation.testing INFO: 89.2%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: Rank-5
[06/29 23:34:37] fastreid.evaluation.testing INFO: 95.0%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: Rank-10
[06/29 23:34:37] fastreid.evaluation.testing INFO: 96.7%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: mAP
[06/29 23:34:37] fastreid.evaluation.testing INFO: 79.6%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: mINP
[06/29 23:34:37] fastreid.evaluation.testing INFO: 43.7%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.0001
[06/29 23:34:37] fastreid.evaluation.testing INFO: 14.5%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.001
[06/29 23:34:37] fastreid.evaluation.testing INFO: 41.8%
[06/29 23:34:37] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.01
[06/29 23:34:37] fastreid.evaluation.testing INFO: 79.9%

**Comment by sky186** [comment]
这是训练保存config,yml 文件，单卡训练，不知道是哪些参数可能导致这个问题，或者以后修改的话要注意哪些参数？
CUDNN_BENCHMARK: true
DATALOADER:
  NAIVE_WAY: false
  NUM_INSTANCE: 16
  NUM_WORKERS: 16
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - DukeMTMC
  TESTS:
  - DukeMTMC
INPUT:
  DO_AUGMIX: false
  DO_AUTOAUG: true
  DO_CJ: false
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 384
  - 128
  SIZE_TRAIN:
  - 384
  - 128
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: /home/svt/pytorch_code/reid/pretrained_model/resnet50_ibn_a.pth.tar
    WITH_IBN: true
    WITH_NL: false
    WITH_SE: false
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 256
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 702
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 0.125
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 0.2
  META_ARCHITECTURE: MGN
  OPEN_LAYERS:
  - b1_pool
  - b1_head
  - b2_pool
  - b2_head
  - b21_pool
  - b21_head
  - b22_pool
  - b22_head
  - b3_pool
  - b3_head
  - b31_pool
  - b31_head
  - b32_pool
  - b32_head
  - b33_pool
  - b33_head
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ''
OUTPUT_DIR: logs/dukemtmc/author_duke_mgn_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 128
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS:
  - 30
  - 55
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 64
  METRIC: cosine
  PRECISE_BN:
    DATASET: DukeMTMC
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3

**Comment by L1aoXingyu** [comment]
> adam() 优化器，有自己的学习率自动衰减
config 参数有 外在学习率衰减

scheduler 主要是改变了 `Adam` 里面的 base_lr，Adam 里面 adaptive 的部分还是会动态变化。

**Comment by L1aoXingyu** [comment]
> 并行训练 如果采用分布式训练接口 syncbn 这个参数，是否还需要昵？为什么代码里面没有采用这个接口昵？
torch.nn.parallel.DistributedDataParallel

syncBN 主要是为了同步跨卡之间的 bn 统计量，因为现在是 id 采样，单卡上的图片统计量 noise 并不够。
目前采用的多卡方式还是简单的 dataparallel，DistributedDataParallel 我们正在做，估计下周会正式做好，替换现在的 dataparallel。

**Comment by sky186** [comment]
@L1aoXingyu 
您好，打扰您了，想请教下问题
PRECISE_BN  dataset 主要做什么用昵
TEST:
  EVAL_PERIOD: 2000   #测试间隔
  PRECISE_BN:
    DATASET: 'DukeMTMC'

**Comment by sky186** [comment]
@L1aoXingyu 
提个建议，如果你们改代码， 训练迭代能用 epoch  循环吗？ 用迭代次数
真的很不直观，不同的数据应该都要各种改

我想和您确认下 修改不同数据后，超参数  这些超参数的设置 改动问题
**_duke 训练数据大概 17000 左右 那么batch=64单卡，  MAX_ITER: 18000 就是 70个epoch 左右，所以这个迭代次数需要怎么改以70 epoch 作为基准？_**
以下
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 128
  SCHED: "DelayedCosineAnnealingLR"  
不变

 DELAY_ITERS: 9000   **_是 max iter 的一半，lr 变化是一个波峰，我设置也要是 最大迭代的一半？，还是要自己调整改变？_**
以下
  ETA_MIN_LR: 0.00000077
  WARMUP_FACTOR: 0.01
不变


  WARMUP_ITERS: 2000  # 17000左右的duke 数据应该是 7个epoch 左右（batch 64)
  FREEZE_ITERS: 2000   # 17000左右的duke 数据应该是 7个epoch 左右（batch 64)
_**冻结训练和 学习率预训练 迭代次数一致， 改变数据我应该， 也是这么多epoch ？**_

下面超参数也仍然不变

###################################################################

SOLVER:
  OPT: "Adam"
  MAX_ITER: 18000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 128

  SCHED: "DelayedCosineAnnealingLR"

  DELAY_ITERS: 9000
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000

  FREEZE_ITERS: 2000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 6000

**Comment by sky186** [comment]
@L1aoXingyu 
sgd  base lr=0.01,         warm up,这里可视化学习率 有一个奇怪的转折， 不知道哪里导致的？
![image](https://user-images.githubusercontent.com/56809648/86340091-ffb65380-bc86-11ea-8517-d1d19a9975d8.png)

**Comment by L1aoXingyu** [comment]
> PRECISE_BN dataset 主要做什么用昵
TEST:
EVAL_PERIOD: 2000 #测试间隔
PRECISE_BN:
DATASET: 'DukeMTMC'

这个是为了重新统计 bn 的统计量，而不是用 EMA 的统计量

**Comment by L1aoXingyu** [comment]
> 提个建议，如果你们改代码， 训练迭代能用 epoch 循环吗？ 用迭代次数
真的很不直观，不同的数据应该都要各种改

非常好的建议，应该在下周发布的 0.2 版本里面就会解决这个问题，目前我的解决方案是这样的
```python
cfg.defrost()
cfg.MODEL.HEADS.NUM_CLASSES = data_loader.dataset.num_classes
cfg.SOLVER.MAX_ITER *= iters_per_epoch
cfg.SOLVER.WARMUP_ITERS *= iters_per_epoch
cfg.SOLVER.FREEZE_ITERS *= iters_per_epoch
for i in range(len(cfg.SOLVER.STEPS)):
	cfg.SOLVER.STEPS[i] *= iters_per_epoch
cfg.SOLVER.SWA.ITER *= iters_per_epoch
cfg.SOLVER.SWA.PERIOD *= iters_per_epoch
cfg.SOLVER.CHECKPOINT_PERIOD *= iters_per_epoch
cfg.TEST.EVAL_PERIOD *= iters_per_epoch
cfg.freeze()
```

配置文件里面的的 iter 表示 epoch，然后在程序内部自动转换成 iter

Any advice？

**Comment by L1aoXingyu** [comment]
> sgd base lr=0.01, warm up,这里可视化学习率 有一个奇怪的转折， 不知道哪里导致的？

你这个是因为有两个 tensorboard 的保存文件导致的

**Comment by L1aoXingyu** [comment]
@sky186 
我们更新了代码，具体自动计算 epoch 的代码在这里

https://github.com/JDAI-CV/fast-reid/blob/13bb8d5b1ccbb01d5501b77e47b0cdbae6f6fc1e/fastreid/engine/defaults.py#L483

**Comment by sky186** [comment]
@L1aoXingyu 
好的，se模块可以替换成 sge （Enhance: Improving SemanticFeature Learning in ，Convolutional
Networks, https://github.com/implus/PytorchInsight）

**Comment by L1aoXingyu** [comment]
@sky186 Thanks, I will try it later.

**Comment by sky186** [comment]
@L1aoXingyu 
多卡训练有什么需要注意的吗？
之前看到有讨论 对于circle loss  ,下面这个的意思不是很明白？

you need to tune batch size with K=4, P=4, which means batch size is 16, with 4 identities and 4 images of each identity. Besides, it needs to freeze backbone for the first 2000 iters.
You can try on market151,
batch 是 4个id，每个id 16张图，这里是一个比较关键的地方

**Comment by sky186** [comment]
@L1aoXingyu 
新的代码
python3.6 ./tools/train_net.py --config-file ./configs/Market1501/mgn_R50-ibn.yml MODEL.DEVICE "cuda:0"

File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by L1aoXingyu** [comment]
> batch 是 4个id，每个id 16张图，这里是一个比较关键的地方

就是 batch 按 id 采样，batch=64，一共是 4 个id，每个 id 16 张图

> OSError: [Errno 12] Cannot allocate memory

这个应该是你电脑的内存问题，你调小 `num_workers` 吧

**Comment by sky186** [comment]
@L1aoXingyu 
opt = Ranger RangerLars
请问代码中默认Adam, 在更新的代码中删除了这些优化方法，是因为做实验效果不好吗？您用Ranger试验过吗？
class Ranger(Optimizer):
    def __init__(self, params, lr=1e-3,  # lr
                 alpha=0.5, k=6, N_sma_threshhold=5,  # Ranger options
                 betas=(.95, 0.999), eps=1e-5, weight_decay=0,  # Adam options
                 use_gc=True, gc_conv_only=False
                 # Gradient centralization on or off, applied to conv layers only or conv + fc layers
                 ):

**Comment by finger-monkey** [comment]
> 您好！欢迎关注我们的工作~
> 看您的描述，应该是显存out of memory(OOM)了，因为按照默认设置，sbs在2000 iters之后会解冻model层，显存会出现暴增，训练时长也会变长，这些都是正常现象。如果是这样的话，建议您改小batch size（_SOLVER.IMS_PER_BATCH_）即可，当然相应的iters也需要依据batch size重新计算。
> 如果不是OOM的问题，方便把输出结果，以及config.yaml贴一下吗？

请问多卡训练，需要将 backbone 和 head 中的 BN 替换为 syncBN，这里的backbone、 head 、具体指的是哪些.py文件？如果能给出具体位置将不胜感激涕零。

**Comment by L1aoXingyu** [comment]
@sky186 试了一下这些 optimizer，效果都比较一般，如果你那边有好的实验结果，可以一起讨论一下。
