### ISSUE TITLE
ModuleNotFoundError: No module named 'fastreid'

### ISSUE THREAD

**Issue by Lavenderpb** [JDAI-CV/fast-reid#127]

**Comment by L1aoXingyu** [comment]
pls refer here

https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md

**Comment by Lavenderpb** [comment]
-bash: ./tools/train_net.py: No such file or directory

**Comment by L1aoXingyu** [comment]
There is a python file, you need to use python to execute this file like this
```
python tools/train_net.py --config-file configs_file_path
```
