### ISSUE TITLE
Have you had a try to convert .pth model trained out by fast-reid to onnx ?

### ISSUE THREAD

**Issue by arnoldfychen** [JDAI-CV/fast-reid#129]
Dear team, 
     As you know, NVIDIA TRT supports onnx-formatted models and TRT running models on Jetson platform gains a very good performance,  it would be great if  fast-reid pth models can be converted to onnx successfully, that will help us a lot in deploying models on Jetson devices.   Thanks.

**Comment by L1aoXingyu** [comment]
We are making efforts to support TRT runtime.
If we finished, we will release the tutorial as soon as possible.

**Comment by L1aoXingyu** [comment]
We have finished supporting onnx/trt export, please check the [deployment](https://github.com/JDAI-CV/fast-reid/blob/master/tools/deploy/README.md).
