### ISSUE TITLE
resume problem

### ISSUE THREAD

**Issue by longma2019** [JDAI-CV/fast-reid#131]
When the training process is resumed from a checkpoint, the learning rate will be the base LR until the end of the training.
Is it a bug in the code, or I made some mistakes?

The command is like this:
CUDA_VISIBLE_DEVICES=0 python ./tools/train_net.py --config-file ./configs/#.yml --resume  MODEL.WEIGHTS ./logs/#.pth

**Comment by L1aoXingyu** [comment]
Which LR scheduler did you use? 
There is a bug exactly in `DelayedCosineAnnealingLR` and we have fixed it but not update yet.

In recent days, we are trying hard to work for `DistributedDataParallel`, we will update new features and fix bugs maybe next week as a version update.

**Comment by longma2019** [comment]
I used DelayedCosineAnnealingLR.

Thanks for the updates.
