### ISSUE TITLE
dsr_distance.py

### ISSUE THREAD

**Issue by Mrkkew** [JDAI-CV/fast-reid#135]
thank you for your update. But there are some problems in your new code.
there is no function compute_dsr_dist in dsr_distance.py, I think it may be get_dsr_dist, but there is no topk value in get_dsr_dist function.
What's more, I have no right to download the datasets from the link given in README.md. Can you check it?

**Comment by lingxiao-he** [comment]
Thank you for your question, you can run it again, if you have any question, please contact me.

**Comment by JasAva** [comment]
Thank you for your update. @lingxiao-he, However, I tried to reproduce the partial results on PartialREID using updated code, the results (mAP/Rank-1 69.7/75.0) are still much lower than reported.
Moreover, seems that 'compute_dsr_dist still hasn't been replaced by ''get_dsr_dist', and preprocess function in the partial dataset also needs updates for other two datasets.
Looking forward to your insights on these. Thank you:)

**Comment by L1aoXingyu** [comment]
Please use the latest code and try again.
