### ISSUE TITLE
关于circleloss的线性层使用

### ISSUE THREAD

**Issue by ahzz1207** [JDAI-CV/fast-reid#136]
你好，感谢提供实现，我看到你的circleloss实现似乎跟论文中有些许出入？
你最后生成pred_logits不能直接用于softmax的acc计算， 而如果要计算分类的acc， 应该取第一次linear得到的sim_mat过softmax层对吧？（我在你的代码里似乎没找到这样做）
我是想在NLP的通用意图分类下尝试，如有结果将反馈。

**Comment by L1aoXingyu** [comment]
感谢你的提问，最后得到的 `pred_logits` 确实不能直接计算 acc，之前没有考虑到这个问题，就和普通的 `nn.Linear` 输出保持一致了，我会尽快 fix 这个问题，不过目前我们正在做 `DistributedDataParallel` 的迁移，估计会在下周 release 新版本，到时候这个问题会一并修复。
