### ISSUE TITLE
请教一下大类别训练如何调参

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#137]
我用你的代码在三个公开数据集上训练和测试rank1都有提升，但是训练我自己的数据rank1却下降了一个点，我的数据有5000个ID，每个ID大概50张图片。请问对这样的数据有哪些建议修改的参数呢

**Comment by L1aoXingyu** [comment]
你用的是哪个配置文件，你的 id 规模其实也不大，根据我的经验，用这个配置文件 [config](https://github.com/JDAI-CV/fast-reid/blob/master/configs/Base-Strongerbaseline.yml) 应该就可以 train 的比较好。

**Comment by guanyonglai** [comment]
多谢多谢，我用的 mgn_R50-ibn.yml，8000ID训练的效果比5000ID低3个点，我试一下这个配置文件

**Comment by guanyonglai** [comment]
如果多卡训，这个config里面的NORM也需要改成"syncBN"吧

**Comment by L1aoXingyu** [comment]
是的，改成 `syncBN` 更好。

**Comment by guanyonglai** [comment]
我试了这个配置，还是5000ID的结果比8000ID好，高一个点。试了很多别的网络也都没找到可以训练大类别的，不知道到底是训练参数没调好还是reid这种分类就是无法训练大类别，能给点建议吗

**Comment by guanyonglai** [comment]
大类别训练的结果就是准确率降低，loss没有小类别收敛得那么低，而且loss收敛相对较慢

**Comment by L1aoXingyu** [comment]
我们尝试了5w+ 的id，用目前的配置没有任何问题，5000ID 比8000ID 结果更好也许是新加的 3000ID 数据不干净，你可以继续增大量级，我们目前正在支持 face recognition，ID 量级会更多。

**Comment by guanyonglai** [comment]
能问一下你们reid用5w+ID训练能比1w ID提升几个点呢，

**Comment by L1aoXingyu** [comment]
5个点吧，原则上 id 越到，泛化性越强，reid 最后和人脸还是比较像的

**Comment by guanyonglai** [comment]
我的天，，能提这么多，请问下你的训练集平均一个ID多少张图片呢？我的就十几张，可能是造成增加数据结果反而变差的原因

**Comment by L1aoXingyu** [comment]
每个 camera 下 5 张左右，ID 数目取决于 camera 数目，camera 越多效果越好。

**Comment by guanyonglai** [comment]
多谢多谢！！我的数据平均每个ID跨7个camera，应该是没你的多，，正在整一批跨更多camera的数据

**Comment by L1aoXingyu** [comment]
你的ID跨了7个camera应该质量还可以，建议不要用 mgn 这种网络结构， 因为这个结构对数据要求非常高，只要不是全身的人体，就会出现 alignment 的问题。
