### ISSUE TITLE
Performance on Duke-to-Market

### ISSUE THREAD

**Issue by WangWenhao0716** [JDAI-CV/fast-reid#138]
Thanks for the excellent work you did. I have a question: in your paper, you said 
"
FastReID-MLT can achieve 92.7%(77.5%), 82.7%(69.2%) under D→M, M→D settings. The result is close to supervised learning results.
"
However, in the table of your paper:

"
FastReID-MLT   80.5 92.7  								85.7 94.1 | 69.2 82.7
"
Please tell me 77.5 VS 80.5, which is correct?

**Comment by lingxiao-he** [comment]
80.5 is correct

**Comment by WangWenhao0716** [comment]
Thanks！



发自我的iPhone


------------------ Original ------------------
