### ISSUE TITLE
AttributeError: 'Baseline' object has no attribute 'load_params_wo_fc'

### ISSUE THREAD

**Issue by HouBiaoLiu** [JDAI-CV/fast-reid#142]
When I run 
        model.load_params_wo_fc(torch.load('logs/bjstation/res50_baseline_v0.4/ckpts/model_epoch80.pth')).
It encounters the error AttributeError: 'Baseline' object has no attribute 'load_params_wo_fc'

**Comment by L1aoXingyu** [comment]
Where do you need to use `load_params_wo_fc`?

This function has been deprecated.
