### ISSUE TITLE
怎么进行推理啊？有相关文档嘛？

### ISSUE THREAD

**Issue by liuhaiyang2018** [JDAI-CV/fast-reid#143]

**Comment by liuhaiyang2018** [comment]
你好，与训练模型在什么地方啊？

**Comment by L1aoXingyu** [comment]
推理可以参考 https://github.com/JDAI-CV/fast-reid/blob/master/demo/demo.py

预训练模型需要自己去下载，训练好的模型我们预计下周上传 google driver.

**Comment by liuhaiyang2018** [comment]
现在部署只有caffe的，什么时候有tensorrt的 onnx的啊

**Comment by liuhaiyang2018** [comment]
推理可以参考 https://github.com/JDAI-CV/fast-reid/blob/master/demo/demo.py  执行这个demo使用并行处理的话，会报错误：

RuntimeError: cuda runtime error (3) : initialization error at /opt/conda/conda-bld/pytorch_1570710853631/work/aten/src/THC/THCGeneral.cpp:54

**Comment by L1aoXingyu** [comment]
> 现在部署只有caffe的，什么时候有tensorrt的 onnx的啊

这个月之内我们会支持 onnx 和 tensorRT

**Comment by nanhui69** [comment]
> 推理可以参考 https://github.com/JDAI-CV/fast-reid/blob/master/demo/demo.py
> 
> 预训练模型需要自己去下载，训练好的模型我们预计下周上传 google driver.

请问 预处理部分为什么要做两次呢？ 在 baseline 里面的也有对应的预处理？可以解释下么？
