### ISSUE TITLE
batch size 56 只有一张2080ti卡 rank1 差了 10% map 20% 能弥补吗？

### ISSUE THREAD

**Issue by zoujialong9012** [JDAI-CV/fast-reid#145]
^[[32m[07/01 15:55:55 fastreid.engine.defaults]: ^[[0mEvaluation results for SmallVeRiWild in csv format:
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: Rank-1
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m86.5%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: Rank-5
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m95.2%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: Rank-10
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m97.6%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: mAP
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m64.7%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: mINP
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m32.0%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: TPR@FPR=0.0001
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m5.2%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: TPR@FPR=0.001
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m57.2%
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0mTask: TPR@FPR=0.01
^[[32m[07/01 15:55:55 fastreid.evaluation.testing]: ^[[0m98.8%

**Comment by L1aoXingyu** [comment]
调小 image size 到 [256, 128]，去掉 non-local，用 batch size 64 训练
