### ISSUE TITLE
A problem about visualize_result

### ISSUE THREAD

**Issue by FeiYuejiao** [JDAI-CV/fast-reid#146]
Hi,

visualize_result.py in demo directory can visualized queries in ascending or descending orders by cosine similarity or AP.
But I was trying to input one specifc query and see outputs from different models. 
However, I found that that result is incompatible with that from inputing all queries in the dataset.query.
I defined a function to construct a test loader just for a specific query image.
```
def build_specific_reid_test_loader(cfg, dataset_name, img_path):
    test_transforms = build_transforms(cfg, is_train=False) # Resize test images
    dataset = DATASET_REGISTRY.get(dataset_name)(root=_root)
    query = []
    pattern = re.compile(r'([-\d]+)_c(\d)')
    query_pid, query_camid = map(int, pattern.search(img_path).groups())
    query.append((img_path, query_pid, query_camid))
    show_specific_test(query, dataset.gallery, dataset_name, img_path)

    test_items = query + dataset.gallery
    test_set = CommDataset(test_items, test_transforms, relabel=False)

    num_workers = cfg.DATALOADER.NUM_WORKERS
    batch_size = cfg.TEST.IMS_PER_BATCH
    data_sampler = samplers.InferenceSampler(len(test_set))
    batch_sampler = torch.utils.data.BatchSampler(data_sampler, batch_size, False)
    test_loader = DataLoader(
        test_set,
        batch_sampler=batch_sampler,
        num_workers=num_workers,
        collate_fn=fast_batch_collator)
    return test_loader, len(query)
```
The visulized result for Market1501/query/0113_c5s1_018801_00.jpg in input one query setting is:
![image](https://user-images.githubusercontent.com/25504824/86311711-9701b380-bc53-11ea-95db-a4c4ca1d5cba.png)
The visulized result for Market1501/query/0113_c5s1_018801_00.jpg in input  all dataset.query setting is:
![image](https://user-images.githubusercontent.com/25504824/86311822-cfa18d00-bc53-11ea-8fd3-fde5e3d0de7b.png)

**Comment by L1aoXingyu** [comment]
The query is different, one comes from `camera4` and the other comes from `camera5`.

**Comment by FeiYuejiao** [comment]
How come? They are actually one image, you can see from the img_path. But their cam_id is different?

**Comment by FeiYuejiao** [comment]
May I ask where should I modify the cam_id? They are actually one image, so should have the same cam_id.

**Comment by FeiYuejiao** [comment]
I think there may be a bug in 'build_reid_test_loader' function. From the file name we can see the cam_id should be 5 rather than 4.

**Comment by L1aoXingyu** [comment]
You can check here
https://github.com/JDAI-CV/fast-reid/blob/9fa6e0f6062a8ab9bc3dc34094f1937c99586e2e/fastreid/data/datasets/market1501.py#L83

We just -1 for camid.
