### ISSUE TITLE
large difference between the trained-out pth model inference result  and onnx  inference result 

### ISSUE THREAD

**Issue by HouBiaoLiu** [JDAI-CV/fast-reid#147]
# encoding: utf-8
"""
@author:  sherlock
@contact: sherlockliao01@gmail.com
"""

import sys

import torch
sys.path.append('../..')
sys.path.append('.')
from fastreid.config import get_cfg
from fastreid.engine import default_argument_parser, default_setup
from fastreid.modeling import build_model
#from fastreid.export.tensorflow_export import export_tf_reid_model
from fastreid.export.tf_modeling import TfMetaArch
import onnx
from torch.backends import cudnn
import torch.nn.functional as F
import io
from fastreid.utils.checkpoint import Checkpointer
import numpy as np
import onnxruntime
import cv2
cudnn.benchmark = True
def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    default_setup(cfg, args)
    return cfg
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    cfg1 = setup(args)
    cfg = cfg1.clone()
    cfg.defrost()
    
    
    cfg.MODEL.BACKBONE.PRETRAIN = False
    model = build_model(cfg)
    #model.load_state_dict( torch.load('logs/Vechile1M/bagtricks_R50-ibn_4gpu/model_0211199.pth'))
    Checkpointer(model).load('logs/Vechile1M/bagtricks_R50-ibn_4gpu/model_0211199.pth')
    
    model.cuda()
    model.eval()
    #print (model)
    layer_names = {}
    for name, layer in model.named_modules():
        layer_names[layer] = name
    print("torch ops name:", layer_names)
    dummy_inputs = torch.randn(1, 3, 256, 256).cuda()
    torch.onnx.export(model,  # model being run
                      {'images': dummy_inputs},  # model input (or a tuple for multiple inputs)
                      "reid_test.onnx",  # where to save the model (can be a file or file-like object)
    export_params=True,  # store the trained parameter weights inside the model file
    )
    onnx_model = onnx.load("reid_test.onnx")
    onnx.checker.check_model(onnx_model)
#
    
    original_image = cv2.imread("/hdata/nfs_share/Vehicle-1M/Vehicle-1M/image/149/497612.bmp")
    
    # the model expects RGB inputs
    original_image = original_image[:, :, ::-1]
    # Apply pre-processing to image.
    image = cv2.resize(original_image, (256, 256), interpolation=cv2.INTER_CUBIC)
    image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))[None]
    img = image.cuda()
    
    with torch.no_grad():
        torch_out1 = model.forward({'images': img})
        torch_out = F.normalize(torch_out1)
    
    ort_session = onnxruntime.InferenceSession("reid_test.onnx")
    
    # compute ONNX Runtime output prediction
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(img)}
    ort_outs = ort_session.run(None, ort_inputs)
    img_out_y = ort_outs[0]
    norm = np.linalg.norm(img_out_y, ord=2, axis=1, keepdims=True)
    print ('norm:', norm)
    feat = img_out_y/norm
    np.savetxt('th_re.txt', to_numpy(torch_out).T)
    np.savetxt('onnx_re.txt', feat.T)  
    # compare ONNX Runtime and PyTorch results
    np.testing.assert_allclose(to_numpy(torch_out), feat, rtol=1e-03, atol=1e-05)
    
    print("Exported model has been tested with ONNXRuntime, and the result looks good!")

**Comment by L1aoXingyu** [comment]
We are trying to support DDP training these days, and ONNX-inference will be supported after we release v0.2 next week.
Please give us some time.

PRs are welcome!

**Comment by HouBiaoLiu** [comment]
I have solved the problem. I commented the preprocess_image function, and then no difference between onnx and pytorch inference!  So the preprocess such as subtract mean or resize should be both before onnx and pytorch. And then reference only do deep network inference, but not do preprocess

**Comment by L1aoXingyu** [comment]
Good job! In the caffe deployment, we just put the preprocess before the network forward.

You can check in [caffe deploy](https://github.com/JDAI-CV/fast-reid/blob/master/tools/deploy/README.md).

**Comment by HouBiaoLiu** [comment]
Thanks! Now I meet a new problem when deploy onnx to tvm. 
 It reports "TypeError: clip() missing 1 required positional argument: 'a_max'"
I guess The error in GeneralizedMeanPooling layer! I notice in the forward process 
 x = x.clamp(min=self.eps).pow(self.p).
My question is what the defaut max argment is?  For safety should we set max in this clamp fuction?

**Comment by L1aoXingyu** [comment]
the default value for `torch.clamp` is `inf`, maybe I should set a number for this.

**Comment by fengfengcxf** [comment]
> I have solved the problem. I commented the preprocess_image function, and then no difference between onnx and pytorch inference! So the preprocess such as subtract mean or resize should be both before onnx and pytorch. And then reference only do deep network inference, but not do preprocess

hello,could yu please tell me the meaning of " reference only do deep network inference, but not do preprocess",what should i do about this?

**Comment by addisonklinke** [comment]
For those stumbling on upon this issue in the future, I want to explain my mistake since it was different from @HouBiaoLiu. It took me too long to notice this subtlety, so I hope my explanation saves others some time.

In the ONNX export [script](https://github.com/JDAI-CV/fast-reid/blob/16655448c25dfb3e9cbf35e6a1f94d1731bbbf06/tools/deploy/onnx_export.py#L125-L129), the weights from my training were not being loaded since by default `MODEL.WEIGHTS = ''` in most of the config YAMLs. Not only that, but the export script explicitly sets `MODEL.BACKBONE.PRETRAINED = False` which, if you're using a torchvision model trained on ImageNet, means you won't even be exporting with those weights loaded - you'll just get a randomly initialized model! To get the same inference accuracy as you had during training, you'll need to ensure your config file specifies the path to the `model_final.pth` file that was saved at the end of training

**Comment by viwa-creatr** [comment]
> the default value for `torch.clamp` is `inf`, maybe I should set a number for this.

Excuse me, if I want set a number for this, What number should I set？thank you
