### ISSUE TITLE
On the experiment of increasing ID

### ISSUE THREAD

**Issue by DongfeiJi** [JDAI-CV/fast-reid#148]
Hello;

Have you ever trained on large data sets?

For example, if the ID number is 10W, I use sceloss + tripletloss,

Only tripletloss leads to the optimization, but the scelossis is unchanged， seem like there is no grad.

I'd like to ask you how to train large-scale data， thanks！

**Comment by HouBiaoLiu** [comment]
no circleloss needed, refer to veriwild config!

**Comment by DongfeiJi** [comment]
> no circleloss needed, refer to veriwild config!

Thanks for your reply, i see there is no hard mining, do u know why?
And have you tried circle loss?

**Comment by L1aoXingyu** [comment]
Pls provide your config file.

**Comment by guanyonglai** [comment]
That happened to me, too. The training result of 8000 ids is not as good as 5000 ids,

**Comment by L1aoXingyu** [comment]
If you increase your ids, but cannot get good performance, maybe there is something wrong about your data.

**Comment by DongfeiJi** [comment]
> That happened to me, too. The training result of 8000 ids is not as good as 5000 ids,

What is the gpu num?

**Comment by sky186** [comment]
@DongfeiJi 
您好，请问你增加了id ,数据量比较大的时候，怎么训练效果比较好尼，损失函数需要修改吗？
