### ISSUE TITLE
strong-baseline 不需要预训练模型 BACKBONE.PRETRAIN_PATH 吗

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#149]
看了几个沿用Base-Strongerbaseline.yml的配置文件都没有载入预训练模型，这样不会对结果有影响吗，如果要载入预训练模型应该用哪个呢

**Comment by L1aoXingyu** [comment]
如果不声明 pretrain_path，那么默认用 `.cache/torch/checkpoints` 中的 pretrain model。

**Comment by guanyonglai** [comment]
会调用 .cache/torch/checkpoints 中的哪个模型呢，模型名是什么， 我可能还没下

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/86458906-930b8980-bd58-11ea-8eae-1a7a66d8a03b.png)
如果在训练过程中出现了这个 log，就说明 load 的是 imagenet pretraining 的 resnet50
