### ISSUE TITLE
The pre-training of MMT/SpCL/strong_baseline from OpenUnReID

### ISSUE THREAD

**Issue by yxgeee** [JDAI-CV/fast-reid#151]
Hi,

Thank you first for the nice work.
I noticed that you followed my results form in [projects/Cross-domain-reid](https://github.com/JDAI-CV/fast-reid/tree/master/projects/Cross-domain-reid#dukemtmc-reid---market-1501). There are some mistakes on the pre-training of `MMT/SpCL/strong_baseline`, i.e. `MMT/SpCL/strong_baseline` are all trained **directly from ImageNet-pretraining** instead of source-domain pre-training. You could see [OpenUnReID/MODEL_ZOO](https://github.com/open-mmlab/OpenUnReID/blob/master/docs/MODEL_ZOO.md#unsupervised-domain-adaptation-uda-on-object-re-id) for more details, i.e. either USL or UDA version of `MMT/SpCL/strong_baseline` are trained from ImageNet pretraining. 
Please modify them to avoid any misunderstanding. Thanks!

**Comment by zkcys001** [comment]
Hi,
Thanks for your valuable comments. 
We will fix this issue in the future version.
