### ISSUE TITLE
关于osnet，能弄个config吗？

### ISSUE THREAD

**Issue by Reggieharden** [JDAI-CV/fast-reid#154]

**Comment by L1aoXingyu** [comment]
Please give me more details about this config of osnet.

**Comment by Reggieharden** [comment]
如果调用的是osnet的模型，代码会出错。。是不是不兼容osnet？

**Comment by L1aoXingyu** [comment]
需要改一下 `MODEL.HEADS.IN_FEAT` 这个参数，因为 osnet 出来的 feature channel 和 resnet50 不一样。

**Comment by L1aoXingyu** [comment]
osnet 已经配置好文档了

**Comment by gmt710** [comment]
@Reggieharden，你好，我想请问一下，osnet真能如[deep-person-reid/MODEL_ZOO](https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO)所述，高于resnet50几个点吗？

**Comment by L1aoXingyu** [comment]
你可以和 fastreid 的 [model zoo](https://github.com/JDAI-CV/fast-reid/blob/master/docs/MODEL_ZOO.md) 比一下绝对精度，deep person reid 里面的 resnet50 精度比较低。

**Comment by gmt710** [comment]
1.是的，我也是鉴于deep person reid中 `resnet`精度比较低，就自己在fastreid下训练了osnet模型，拿掉了一些caffe不可转换的层设置，训练了个结果。
```
| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   |
|:-----------|:---------|:---------|:----------|:-------|:-------|
| Market1501 | 94.71%   | 98.13%   | 98.69%    | 85.64% | 58.52% |


```
2.以相同配置训练出来的resnet50，rank1与mAP结果差不多，差距都在0.几%以内，还没具体看deep person reid 里面的配置，所以也不太确定配置是不是需要修改。

**Comment by L1aoXingyu** [comment]
你现在的精度不是已经超过 deep-reid 里面 osnet 的精度了吗？

**Comment by gmt710** [comment]
是的啊，但是不确定是否也会和resnet一样，在strong-baseline配置下，能提高一些呢

**Comment by L1aoXingyu** [comment]
我个人觉得提高几个点不太可能，我倾向于只能在低 baseline 上提高几个点，高 baseline 是差不多的。

**Comment by gmt710** [comment]
谢谢～

**Comment by gmt710** [comment]
你好，我训练osnet时发现，刚开始时loss_triplet就很小（小数级），训练过程中基本没怎么下降，请问一下，如果这种情况是不是有什么问题呢？

**Comment by X-funbean** [comment]
> osnet 已经配置好文档了

请问osnet配置在哪里能看到呢，我在configs目录下没有找到

**Comment by L1aoXingyu** [comment]
只需要把 backbone 改成 `build_osnet_backbone`, depth 从 `x1_0, x0_75, x0_5, x0_25` 中选就可以了

**Comment by Zc229** [comment]
> 1.是的，我也是鉴于deep person reid中 `resnet`精度比较低，就自己在fastreid下训练了osnet模型，拿掉了一些caffe不可转换的层设置，训练了个结果。
> 
> ```
> | Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   |
> |:-----------|:---------|:---------|:----------|:-------|:-------|
> | Market1501 | 94.71%   | 98.13%   | 98.69%    | 85.64% | 58.52% |
> ```
> 
> 2.以相同配置训练出来的resnet50，rank1与mAP结果差不多，差距都在0.几%以内，还没具体看deep person reid 里面的配置，所以也不太确定配置是不是需要修改。 3.从deep person reid的对比结果来看，osnet增加了好几个点，的确很有诱惑力。如果在strong-baseline配置下，网络参数更少情况下，能提高几个点，简直太诱惑了。

请问您是使用哪个yaml文件跑出来的结果，我也同样使用osnet网络，但是跑不出您这个效果

**Comment by qiu-pinggaizi** [comment]
https://github.com/JDAI-CV/fast-reid/issues/154#issuecomment-2301385495
我用默认配置文件训练，损失一直不降，指标很差，请教一下你们怎么训练呢
