### ISSUE TITLE
Use 'gt_query'?

### ISSUE THREAD

**Issue by soolone** [JDAI-CV/fast-reid#155]
Does this project used files in 'gt_query' when train model with Market-1501 dataset?  
or
Where is the dataset pre-process code before training?

**Comment by L1aoXingyu** [comment]
We use files in `query` and `bounding_box_test`, you can check here.

https://github.com/JDAI-CV/fast-reid/blob/b01bc12a009196ff505ee4795d2b79861b193337/fastreid/data/datasets/market1501.py#L50
