### ISSUE TITLE
Why use Auto-Augment ？

### ISSUE THREAD

**Issue by LouisScorpio** [JDAI-CV/fast-reid#156]
在论文的Ablation Study里，使用Auto-Augment导致mAP下降了2.4%，为什么还要用auto-augment？

![image](https://user-images.githubusercontent.com/16081987/86866252-24854d80-c103-11ea-8e7f-1cec6b4973ad.png)

**Comment by L1aoXingyu** [comment]
我们发现在 MSMT 上有一些提升，所以决定加上 auto-augment，可能其对于室内到室外场景有更好的效果。

我们只是跑了一组实验看了一下，你可以尝试再更多的数据集跑跑，看看效果如何，更多关于 reid 数据增强的方法，也欢迎随时讨论。

**Comment by LouisScorpio** [comment]
> 我们发现在 MSMT 上有一些提升，所以决定加上 auto-augment，可能其对于室内到室外场景有更好的效果。
> 
> 我们只是跑了一组实验看了一下，你可以尝试再更多的数据集跑跑，看看效果如何，更多关于 reid 数据增强的方法，也欢迎随时讨论。

谢谢解答
