### ISSUE TITLE
Can you add support for the HACNN？

### ISSUE THREAD

**Issue by szxczyc** [JDAI-CV/fast-reid#157]
您好，能收录HACNN(18CVPR)到fast-reid库中吗？非常喜欢这个框架，可以开展很多有意思的尝试。
但我尝试自己迁移到fase-reid但是遇到了很多错误。
[https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/hacnn.py](url)

**Comment by L1aoXingyu** [comment]
因为这个框架对落地部署并不是特别友好，所以支持的优先级可能不会太高，我们更希望你能够在 fastreid 里面贡献 HACNN。
目前我们的工作重点是 ONNX 和 tensorRT 的支持，以及人脸模型的支持。
