### ISSUE TITLE
加载预训练模型出错

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#164]
我使用的是pytorch      1.2.0 和torchvision 0.4.0，出现如下错误。这个问题已经困扰我好久了，而且在其他地方也遇到过。请廖老师和各位高手帮忙指点迷津。非常感谢。

RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.0.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.0.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.0.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.0.downsample.1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.1.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.1.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.1.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.2.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.2.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer1.2.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.0.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.0.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.0.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.0.downsample.1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.1.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.1.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.1.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.2.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.2.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.2.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.3.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.3.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer2.3.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.0.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.0.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.0.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.0.downsample.1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.1.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.1.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.1.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.2.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.2.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.2.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.3.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.3.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.3.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.4.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.4.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.4.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.5.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.5.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer3.5.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.0.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.0.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.0.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.0.downsample.1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.1.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.1.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.1.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.2.bn1.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.2.bn2.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for layer4.2.bn3.num_batches_tracked: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).

**Comment by L1aoXingyu** [comment]
你的 pretrain model state dict 貌似是空的。

**Comment by L1aoXingyu** [comment]
更新了 code，现在不需要指定 pretrain_path，你可以再试试。
