### ISSUE TITLE
How can I prepare my own data about gallery and query?

### ISSUE THREAD

**Issue by gmt710** [JDAI-CV/fast-reid#173]
When I test my own data, I find that this problem often occurs.
```           
python ./demo/visualize_result.py --config-file './configs/Market1501/AGW_R50.yml' --vis-label --dataset-name 'Market1501' --output 'logs/market1501/agw_R50/agw_market1501_vis' --opts MODEL.WEIGHTS "./logs/market1501/agw_R50/model_final.pth"
```             
```                
assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
AssertionError: Error: all query identities do not appear in gallery
```         
I don't clearly know why this happens? If you have time, can you tell me how to make your own dataset？

**Comment by L1aoXingyu** [comment]
It's our fault and we will make a tutorial as soon as possible.

Actually, you can refer to Market1501 test set, but one word of caution, the label of testset needs to be number not string.

**Comment by gmt710** [comment]
I think it's relevant to "remove gallery samples that have the same pid and camid with query". My testset have the same pid and camid with query. The testset‘s demand is too high.
Hello, would you mind creating a QQ group for us? I think this is probably more efficient.

**Comment by L1aoXingyu** [comment]
It's better to discuss problems in issue and we don't have time to manage a QQ group.

**Comment by hp-93** [comment]
Similar error in  my own data 
![image](https://user-images.githubusercontent.com/35527573/92297657-3d2fa980-ef74-11ea-89ec-06301c6b714b.png)

**Comment by starsky68** [comment]
@hp-93 请问你的问题解决了吗？

**Comment by L1aoXingyu** [comment]
上面这个问题就是 query 的 id 没有在 gallery 里面出现，可以 check 一下测试数据的 label。

**Comment by starsky68** [comment]
@L1aoXingyu 谢谢了

**Comment by gmt710** [comment]
@hp-93 @starsky68 应该是有去除相同相机中相同ID的步骤，去除之后没有对应的ID可以去查询计算，可能会报错。

**Comment by starsky68** [comment]
@gmt710 谢谢了，我是个新手，这个步骤具体指的是？

**Comment by gmt710** [comment]
rank.py里面的，remove = (g_pids[order] == q_pid) & (g_camids[order] == q_camid)
设置的断言报错，可以通过find定位错误的

**Comment by starsky68** [comment]
@gmt710 非常感谢，我去试试

**Comment by LifeIsSoSolong** [comment]
> 上面这个问题就是 query 的 id 没有在 gallery 里面出现，可以 check 一下测试数据的 label。

你好，麻烦问一下为什么要assert query和gallery的pid camid不能完全相同？  另外我在生成我的query和gallery的时候分别把query图片的camid全部设置为1，gallery图片的camid全部设置为2，是否就可以 正确地避开这个error？

**Comment by AnhPC03** [comment]
@L1aoXingyu  @gmt710 Why ```remove gallery samples that have the same pid and camid with query```?
I don't understand the above rule.
I met the same problem as ```'Error: all query identities do not appear in gallery'```

**Comment by L1aoXingyu** [comment]
@AnhPC03 It's the reid task test protocol, and we need to find the person coming from the other cameras.

**Comment by gmt710** [comment]
@AnhPC03 ,hi, When you make your own datasets, make sure that the gallery contains at least one other camera graph with the same ID in the query.

**Comment by AnhPC03** [comment]
@L1aoXingyu @gmt710 Thank you, i think that this avoid testing on trained dataset

**Comment by addisonklinke** [comment]
@L1aoXingyu I would recommend mentioning this query vs. gallery `camid` caveat in the custom dataset guide (https://github.com/JDAI-CV/fast-reid/issues/220). My dataset does not have camera annotations, so I naively thought I could use 0 for all instances. It wasn't until reading this issue that I understood why my approach was throwing an exception

**Comment by L1aoXingyu** [comment]
@addisonklinke Thanks for your advice! I will mention the query and gallery caveat in `custom dataset guide`.

**Comment by addisonklinke** [comment]
For future readers, here's a quick snippet to list out invalid query paths whose gallery images are all from the same camera

```python
from collections import defaultdict
from fastreid.data.datasets.mine import MyDataset

dataset = MyDataset(...)
gallery_id2cams = defaultdict(set)
for path, identity, camera in dataset.gallery:
    gallery_id2cams[identity].add(camera)
invalid = []
for path, identity, camera in dataset.query:
    gallery_cams = gallery_id2cams[identity]
    diff_cams = gallery_cams - set([camera])
    if len(diff_cams) == 0:
        invalid.append(path)
print(f'{len(invalid)}/{len(dataset.query)} invalid query cameras')
```
