### ISSUE TITLE
输入归一化

### ISSUE THREAD

**Issue by huangzhenjie** [JDAI-CV/fast-reid#175]
您好，看了下代码，我想问下，你们的输入数据在送入模型时是没有归一化的吧，这样做准确率会更高吗？感谢大佬解答

**Comment by L1aoXingyu** [comment]
Here is the normalization

https://github.com/JDAI-CV/fast-reid/blob/eb880767140f1be490dc796f650374d1115f9bb3/fastreid/modeling/meta_arch/baseline.py#L65

**Comment by huangzhenjie** [comment]
thanks
