### ISSUE TITLE
啥时候可以出pytorch转到onnx的相关demo

### ISSUE THREAD

**Issue by baigang666** [JDAI-CV/fast-reid#177]
请问啥时候可以出pytorch转到onnx的相关demo，谢谢

**Comment by ym547559398** [comment]
> 请问啥时候可以出pytorch转到onnx的相关demo，谢谢

里面有啊，转tf的时候是先转到onnx的

**Comment by baigang666** [comment]
@ym547559398 谢谢   我自己写了一个demo  已经成功

**Comment by L1aoXingyu** [comment]
onnx/tensorrt export 已经支持了。

**Comment by nobody-cheng** [comment]
@baigang666 ，方便贴一下转的过程吗，我用tools/deploy/onnx_export.py 转onnx，使用同一张图片测试 onnx和torch的输出不一致

**Comment by L1aoXingyu** [comment]
@nobody-cheng Maybe you do normalization twice, the normalization will be done in the model.

https://github.com/JDAI-CV/fast-reid/blob/1d6e970260c8638688ac0a4976c1f1fbb7b3b6ee/fastreid/modeling/meta_arch/baseline.py#L66

**Comment by HaoWangDL** [comment]
@L1aoXingyu 当我使用onnx_inference，sbs-R50-ibn权重推理时，不同图像的余弦相似度也非常接近。余弦值几乎是0.99878左右。
请问怎么解决啊

**Comment by L1aoXingyu** [comment]
@HaoWangDL 你首先应该输入同一张图片，对比一下 pytorch 输出和 onnx 输出是否一致，如果不一致，那么中间某个地方应该没有对齐
