### ISSUE TITLE
Can I deploy except pixel_std?

### ISSUE THREAD

**Issue by Hwijune** [JDAI-CV/fast-reid#179]
hi @L1aoXingyu 

![image](https://user-images.githubusercontent.com/37058972/87741624-ecc38780-c81f-11ea-93dc-3e540a25265e.png)

i'm use hisilicon 3559a chipset testing.

They do not support pixel_std. only support pixel_mean

Can I deploy except pixel_std?

**Comment by L1aoXingyu** [comment]
you can train a model without pixel_std, then deploy the new model.
