### ISSUE TITLE
训练完成后，自己写的demo测试，发现结果不对，计算两幅图像距离后，同一个人和不同人，之间特征距离都比较小

### ISSUE THREAD

**Issue by baigang666** [JDAI-CV/fast-reid#182]
训练完成后，自己写的demo测试，发现结果不对，计算两幅图像距离后，同一个人和不同人，之间特征距离都比较小
以下是文件脚本的测试结果：
查询图像：/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_000301_00.jpg

0 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_000301_00.jpg
两幅图像距离 ：  5.9604645e-08
1 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_000351_00.jpg
两幅图像距离 ：  0.00012886524
2 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_001976_00.jpg
两幅图像距离 ：  0.00013148785
3 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_082596_00.jpg
两幅图像距离 ：  0.00013911724
4 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_109696_00.jpg
两幅图像距离 ：  0.00010842085
5 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s3_026007_00.jpg
两幅图像距离 ：  0.00014215708
6 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_000301_00.jpg
两幅图像距离 ：  0.00017541647
7 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_000351_00.jpg
两幅图像距离 ：  0.00015747547
8 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_000801_00.jpg
两幅图像距离 ：  0.0002257824
9 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_000976_00.jpg
两幅图像距离 ：  0.00016981363
10 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_068496_00.jpg
两幅图像距离 ：  0.00023156404
11 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0002_c2s1_123041_00.jpg
两幅图像距离 ：  0.00023680925
12 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_017426_01.jpg
两幅图像距离 ：  0.0001938343
13 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_017451_04.jpg
两幅图像距离 ：  0.00017023087
14 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_017476_02.jpg
两幅图像距离 ：  0.0001847744
15 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_017601_01.jpg
两幅图像距离 ：  0.00019276142
16 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_025851_02.jpg
两幅图像距离 ：  0.00020557642
17 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0105_c2s1_036726_01.jpg
两幅图像距离 ：  0.00016593933
18 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0464_c2s1_119341_04.jpg
两幅图像距离 ：  0.000207901
19 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0464_c2s1_119466_04.jpg
两幅图像距离 ：  0.00021898746
20 /home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0464_c2s1_119466_06.jpg
两幅图像距离 ：  0.00017267466

求大神指教，谢谢

**Comment by baigang666** [comment]
# encoding: utf-8
"""
@author:  xingyu liao
@contact: liaoxingyu5@jd.com
"""

import argparse
import os
import torch
import sys
sys.path.append('../../')

from fastreid.config import get_cfg
from fastreid.modeling.meta_arch import build_model
from fastreid.utils.checkpoint import Checkpointer
import cv2
import numpy as np
import torch.nn.functional as F


def setup_cfg(args):
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg


def get_parser():
    parser = argparse.ArgumentParser(description="Convert Pytorch to Caffe model")

    parser.add_argument(
        "--config-file",
        default="/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/config.yaml",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument(
        "--output",
        default='onnx_model',
        help='path to save converted onnx model'
    )
    parser.add_argument(
        "opts",
        help="Modify config options using the command-line",
        default=["MODEL.WEIGHTS","/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/model_final.pth"],
        nargs=argparse.REMAINDER,
    )
    return parser
def preprocessImg(img_path):
    img0 = cv2.imread(img_path)
    img0 = cv2.cvtColor(img0, cv2.COLOR_BGR2RGB)
    img0 = cv2.resize(img0, (128, 384))

    img0=img0[:,:,::-1].astype(np.float32).transpose((2,0,1))/255

    mean=[0.485,0.456,0.406]
    std=[0.229,0.224,0.205]
    im_mean=np.array(mean).reshape((3,1,1))
    im_std=np.array(std).reshape((3,1,1))
    img0-=im_mean
    img0/=im_std

    img0 = img0[np.newaxis, :, :, :]
    data0 = torch.from_numpy(img0).cuda().float()
    data_input0={"images":data0}
    return data_input0

if __name__ == '__main__':
    #1. 解析参数
    args = get_parser().parse_args()
    #2.记载模型
    cfg = setup_cfg(args)
    cfg.defrost()
    cfg.MODEL.BACKBONE.PRETRAIN=False
    model = build_model(cfg)

    model.eval()
    Checkpointer(model).load(cfg.MODEL.WEIGHTS)

    #3.提取特征
    ###############################################################
    img_path = '/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImage/C2/0001_c2s1_000301_00.jpg'
    data_input0=preprocessImg(img_path)
    with torch.no_grad():
        prediction=model(data_input0)
        pre_feat=F.normalize(prediction)
        pre_feat=pre_feat.cpu().data
    print(pre_feat)

    im0=cv2.imread(img_path)
    #cv2.imshow("StardardImage",im0)
    #cv2.waitKey()

    TestImagePath="/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImagePath.txt"
    test_list=[]
    with open(TestImagePath,'r') as file_to_read:
        while True:
            lines = file_to_read.readline()  # 整行读取数据
            if not lines:
                break
                pass
            test_list.append(lines)
    for i,path in enumerate(test_list):
        path_tmp=""
        if i!=len(test_list)-1:
            path_tmp=path[0:len(path)-1]
            print(i,path_tmp)
        else:
            path_tmp=path
            print(i,path_tmp)
        frame=cv2.imread(path_tmp)
        if frame is None:
            print("图像打开失败，请确认图像路径是否正确")
            sys.exit(1)
        path2=path_tmp
        #@1 图像预处理
        data_input1=preprocessImg(path2)
        #@2 提取特征
        with torch.no_grad():
            prediction1 = model(data_input1)
            pre_feat1 = F.normalize(prediction1)
            pre_feat1 = pre_feat1.cpu().data
        #@3 进行特征比对
        SIM =1-torch.mm(pre_feat, pre_feat1.t())
        print("两幅图像相似度 ： ", np.array(SIM)[0][0])
        #cv2.imshow("TestImage",frame)
        #cv2.waitKey()

    #################################################################

**Comment by L1aoXingyu** [comment]
感觉是你的预处理有问题，好像rgb和bgr反了。

**Comment by baigang666** [comment]
@L1aoXingyu  您可以说具体点么？ 我将那个图像先转化为rgb不对么？   
请指教，谢谢

**Comment by L1aoXingyu** [comment]
`img0=img0[:,:,::-1].astype(np.float32).transpose((2,0,1))/255`

你这一步不是有转回 bgr 了？

**Comment by baigang666** [comment]
@L1aoXingyu  大神  那一步的作用难道不是将图像由原来的HxWxC----->变换到CxHxW？

**Comment by baigang666** [comment]
@L1aoXingyu  我看那个visualize_result.py  这个文件中 图像数据预处理只有两部：一部是resize;另一部分便是to_tensor
  是不是我的预处理多了呢？ 
求大神指导，万分感谢

**Comment by baigang666** [comment]
@L1aoXingyu 大神  我改了之后  结果还是上述  但是使用你们官方提供的visualize_result.py,得到的结果就是正常 的同类的相似度特别高，不同类的相似度相对低。可以给看一下原因么？ 配置文件和权重都是一样的
谢谢

**Comment by baigang666** [comment]
@L1aoXingyu 可以帮忙看一下 我的图像预处理是否有问题么，谢谢

**Comment by L1aoXingyu** [comment]
你可以自己 check 一下 `visualize_result.py` 和你的预处理哪里不一样。

预处理只需要把 bgr 转成 rgb，然后 resize 就可以了。

**Comment by baigang666** [comment]
@L1aoXingyu 谢谢，已经成功复现和官方visualize_result.py一样结果

**Comment by Hwijune** [comment]
> @ L1aoXingyu 감사합니다. 공식적인 visualize_result.py와 동일한 결과를 성공적으로 재현했습니다

hi! @baigang666 

Can I use test code too?

**Comment by zxwang96** [comment]
> @L1aoXingyu 谢谢，已经成功复现和官方visualize_result.py一样结果

请问可以具体说明一下如何修复吗？

**Comment by gmt710** [comment]
@baigang666 Hello,  I ran the official program and met this problem too.I have no idea to solve this problem．would you mind sharing your ideas about how to correct this problem?

**Comment by baigang666** [comment]
@gmt710  hello
this is my demo:

*****************************************************************************************
# encoding: utf-8
"""
@author:  Gang Bai
@contact: gbai@innovisgroup.com
"""

import argparse
import os
import torch
import sys
sys.path.append('/home/yan/Documents/bg-file/fast-reid-master')

from fastreid.config import get_cfg
from fastreid.modeling.meta_arch import build_model
from fastreid.utils.checkpoint import Checkpointer
import cv2
import numpy as np
import torch.nn.functional as F

save=False  #是否保存模型为ONNX格式
def setup_cfg(args):
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg


def get_parser():
    parser = argparse.ArgumentParser(description="Convert Pytorch to Caffe model")

    parser.add_argument(
        "--config-file",
        default="/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/config.yaml",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument(
        "--output",
        default='onnx_model',
        help='path to save converted onnx model'
    )
    parser.add_argument(
        "--opts",
        help="Modify config options using the command-line",
        default=["MODEL.WEIGHTS","/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/model_final.pth"],
        nargs=argparse.REMAINDER,
    )
    return parser
def preprocessImg(img_path):
    img0 = cv2.imread(img_path)
    img0 = cv2.cvtColor(img0, cv2.COLOR_BGR2RGB)
    img0 = cv2.resize(img0, (128, 384))
    img0 = img0.transpose((2, 0, 1))
    img0 = img0[np.newaxis, :, :, :]
    data0 = torch.from_numpy(img0).cuda().float()
    data_input0={"images":data0}
    return data_input0
def ComptueSIM(v_a,v_b):
    la=len(v_a)
    lb=len(v_b)
    if la==lb:
        Vector_a=v_a
        Vector_b=v_b
        a=0
        b1=0
        b2=0
        for i in range(la):
            a+=Vector_a[i]*Vector_b[i]
            b1+=Vector_a[i]*Vector_a[i]
            b2+=Vector_b[i]*Vector_b[i]
        similarity=a/((b1*b2)**0.5)
        return similarity
    else:
        return -1


if __name__ == '__main__':
    #1. 解析参数
    args = get_parser().parse_args()
    #2.加载模型
    cfg = setup_cfg(args)
    cfg.defrost()
    cfg.MODEL.BACKBONE.PRETRAIN=False
    model = build_model(cfg)

    Checkpointer(model).load(cfg.MODEL.WEIGHTS)
    model.eval()
    #3.提取特征
    ###############################################################

    img_path = '/home/yan/Documents/bg-file/fast-reid-master/datasets/Market-1501-v15.09.15/query/181_320.jpg'
    #img_path = '/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/0002_c1s1_000551_00.jpg'
    data_input0=preprocessImg(img_path)
    with torch.no_grad():
        prediction=model(data_input0)
        pre_feat=F.normalize(prediction)
        pre_feat=pre_feat.cpu().data


    np_array=np.asarray(pre_feat).reshape(2048)
    print(np_array)
    im0=cv2.imread(img_path)
    #cv2.imshow("StardardImage",im0)
    #cv2.waitKey()

    Res = {}
    '''
    #################从文件中读取数据######################################
    TestImagePath="/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImagePath.txt"
    test_list=[]
    
    with open(TestImagePath,'r') as file_to_read:
        while True:
            lines = file_to_read.readline()  # 整行读取数据
            if not lines:
                break
                pass
            test_list.append(lines)
    for i,path in enumerate(test_list):
        path_tmp=""
        if i!=len(test_list)-1:
            path_tmp=path[0:len(path)-1]
            print(i,path_tmp)
        else:
            path_tmp=path
            print(i,path_tmp)
        frame=cv2.imread(path_tmp)
        if frame is None:
            print("图像打开失败，请确认图像路径是否正确")
            break
        path2=path_tmp
        #@1 图像预处理
        data_input1=preprocessImg(path2)
        #@2 提取特征
        with torch.no_grad():
            prediction1 = model(data_input1)
            pre_feat1 = F.normalize(prediction1)
            pre_feat1 = pre_feat1.cpu().data
        #@3 进行特征比对
        np_array1=np.asanyarray(pre_feat1).reshape(2048)
        SIM=ComptueSIM(np_array,np_array1)
        print("两幅图像距离 ： ", SIM)
        Res[path2]=SIM
        #cv2.imshow("TestImage",frame)
        #cv2.waitKey()
    print("特征比对结束")
    #######################################################################
    '''
    #####################从文件夹中读取数据###################################
    import os
    File_path='/home/yan/Documents/bg-file/fast-reid-master/datasets/Market-1501-v15.09.15/bounding_box_test'
    for fname in os.listdir(File_path):
        # @1 图像预处理
        data_input1 = preprocessImg(File_path+"/"+fname)
        # @2 提取特征
        with torch.no_grad():
            prediction1 = model(data_input1)
            pre_feat1 = F.normalize(prediction1)
            pre_feat1 = pre_feat1.cpu().data
        # @3 进行特征比对
        np_array1 = np.asanyarray(pre_feat1).reshape(2048)
        SIM = ComptueSIM(np_array, np_array1)
        print("两幅图像距离 ： ", SIM)
        Res[fname] = SIM
    ######################################################

    #取出前top-5
    Final_res=sorted(Res.items(),key=lambda d:d[1],reverse=True)
    print("排序结束")
    Res_len=len(Final_res)

    if Res_len<5:
        for i in range(Res_len):
            frame=cv2.imread(Final_res[i][0])
            cv2.imshow(str(i),frame)
            cv2.waitKey()
    else:
        for i in range(5):
            print(Final_res[i])
            if i>4:
                break
    print("TOP5---展示结束")
************************************************************************************

**Comment by baigang666** [comment]
@L1aoXingyu 图像预处理  归一化重复做了，删除图像预处理中归一化部分 就好了

**Comment by gmt710** [comment]
@baigang666 Thanks very much. 
I delete the lines of mean and std, but it also get high Similarity between different person. It's so strange. Maybe somewhere I haven't discovered.
Greatly thanks for your sharing.

**Comment by Hwijune** [comment]
@L1aoXingyu hi i'm testing caffe demo. i get the right result?

![image](https://user-images.githubusercontent.com/37058972/88366291-c3789d80-cdc3-11ea-80c9-1be74959b111.png)

```
# encoding: utf-8
"""
@author:  xingyu liao
@contact: liaoxingyu5@jd.com
"""
import sys
import caffe
import tqdm
import glob
import os
import cv2
import numpy as np
from operator import itemgetter
from shutil import copyfile

caffe.set_mode_gpu()

import argparse


def get_parser():
    parser = argparse.ArgumentParser(description="Caffe model inference")

    parser.add_argument(
        "--model-def",
        default="logs/test_caffe/baseline_R50.prototxt",
        help="caffe model prototxt"
    )
    parser.add_argument(
        "--model-weights",
        default="logs/test_caffe/baseline_R50.caffemodel",
        help="caffe model weights"
    )
    parser.add_argument(
        "--input",
        nargs="+",
        help="A list of space separated input images; "
             "or a single glob pattern such as 'directory/*.jpg'",
    )
    parser.add_argument(
        "--testlist",
        nargs="+",
        help="A list of space separated input images; "
             "or a single glob pattern such as 'directory/*.jpg'",
    )
    parser.add_argument(
        "--output",
        default='caffe_output',
        help='path to save converted caffe model'
    )
    parser.add_argument(
        "--height",
        type=int,
        default=256,
        help="height of image"
    )
    parser.add_argument(
        "--width",
        type=int,
        default=128,
        help="width of image"
    )
    return parser


def preprocess(image_path, image_height, image_width):
    original_image = cv2.imread(image_path)
    # the model expects RGB inputs
    original_image = original_image[:, :, ::-1]

    # Apply pre-processing to image.
    image = cv2.resize(original_image, (image_width, image_height), interpolation=cv2.INTER_CUBIC)
    image = image.astype("float32").transpose(2, 0, 1)[np.newaxis]  # (1, 3, h, w)
    image = (image - np.array([0.485 * 255, 0.456 * 255, 0.406 * 255]).reshape((1, -1, 1, 1))) / np.array(
        [0.229 * 255, 0.224 * 255, 0.225 * 255]).reshape((1, -1, 1, 1))

    #img0 = cv2.imread(image_path)
    #img0 = cv2.cvtColor(img0, cv2.COLOR_BGR2RGB)
    #img0 = cv2.resize(img0, (128, 256))
    #img0=img0[:,:,::-1].astype(np.float32).transpose((2,0,1))/255
    #mean=[0.485,0.456,0.406]
    #std=[0.229,0.224,0.205]
    #im_mean=np.array(mean).reshape((3,1,1))
    #im_std=np.array(std).reshape((3,1,1))
    #img0-=im_mean
    #img0/=im_std
    #img0 = img0[np.newaxis, :, :, :]
    
    return image


def normalize(nparray, order=2, axis=-1):
    """Normalize a N-D numpy array along the specified axis."""
    norm = np.linalg.norm(nparray, ord=order, axis=axis, keepdims=True)
    return nparray / (norm + np.finfo(np.float32).eps)


if __name__ == "__main__":
    args = get_parser().parse_args()

    net = caffe.Net(args.model_def, args.model_weights, caffe.TEST)
    net.blobs['blob1'].reshape(1, 3, args.height, args.width)
    
    
    if not os.path.exists(args.output): os.makedirs(args.output)
    rank_arr=[]
    if args.input:
        if os.path.isdir(args.input[0]):
            args.input = glob.glob(os.path.expanduser(args.input[0]))
            assert args.input, "The input path(s) was not found"
        for path in tqdm.tqdm(args.input):
            image = preprocess(path, args.height, args.width)
            net.blobs['blob1'].data[...] = image
            feat = net.forward()['output']
            feat_query = normalize(feat[..., 0, 0], axis=1)
            

            #============== gallery file_read
            TestImagePath='/home_sw1/phj8498/fast-reid/datasets/Market-1501-v15.09.15/list.txt'#args.testlist
            test_list=[]
            with open(TestImagePath,'r') as file_to_read:
                while True:
                    lines = file_to_read.readline()  # read entire
                    if not lines:
                        break
                        pass
                    test_list.append(lines)
            # gallery file cosine dist
            for i,path in tqdm.tqdm(enumerate(test_list)):
                path_tmp=""
                if i!=len(test_list)-1:
                    path_tmp=path[0:len(path)-1]
                    #print(i,path_tmp)
                else:
                    path_tmp=path[:-1]
                    #print(i,path_tmp)
                frame=cv2.imread(path_tmp)
                if frame is None:
                    print("Image failed to open, please confirm that the image path is correct")
                    sys.exit(1)

                path2=path_tmp
                #image preprocessing
                image2 = preprocess(path2, args.height, args.width)
                net.blobs['blob1'].data[...] = image2
                feat2 = net.forward()['output']
                feat_gallery = normalize(feat2[..., 0, 0], axis=1)
                
                #print(feat_query)
                #print(feat_gallery)
                #print(feat_gallery.T)
                
                #print(feat_query)
                file_dict = dict()
                SIM =1-np.dot(feat_query, feat_gallery.T)
                file_dict['path'] = path_tmp
                file_dict['value'] = float(np.array(SIM)[0][0])
                rank_arr.append(file_dict)
                #print("Similarity between two images :", np.array(SIM)[0][0])
        #rint(rank_arr)
        rank_arr = sorted(rank_arr, key=itemgetter('value','path'))
        #print(rank_arr)
        
        image_num = '-5'
        for i in range(10): #20개 하면 성능 떨어짐   
            print(rank_arr[i]['path'])
            print(rank_arr[len(rank_arr)-1-i]['path'])
            copyfile(rank_arr[i]['path'], 'caffe_res/'+str(i)+image_num+'.jpg')
            #opyfile(rank_arr[len(rank_arr)-1-i]['path'], 'caffe_res/'+str(len(rank_arr)-1-i)+'.jpg')
        #print(args.input[0])
        #print(type(args.input))
        copyfile(args.input[0], 'caffe_res/original'+image_num+'.jpg')
            #copyfile(src, dst)
        #print(type(rank_arr[0]))
        #print(sorted(rank_arr, key = lambda x:float(x)))

        #print(rank_arr[:5])
        #print(rank_arr[-5:])
```

**Comment by gmt710** [comment]
You can caculate the SIM on small dataset.If the different person get low SIM distance(SIM =1-np.dot(feat_query, feat_gallery.T)), we're the same.

**Comment by gmt710** [comment]
@Hwijune ,How is it going?

**Comment by Hwijune** [comment]
> @Hwijune ,Hello, how is it going?

i'm just testing. multi camera dataset and youtube videos

**Comment by Hwijune** [comment]
> > @Hwijune ,Hello, how is it going?
> 
> @gmt710  i'm just testing. multi camera dataset and youtube videos

![image](https://user-images.githubusercontent.com/37058972/88638731-dc03f300-d0f6-11ea-9184-7ce08ede9526.png)

**Comment by gmt710** [comment]
The result is same?Do you use bagtricks_R50?

**Comment by Hwijune** [comment]
> The result is same?Do you use bagtricks_R50?

use a agw_R50. 

performance is good in most situations.

**Comment by gmt710** [comment]
It's so weird.I can't use agw_R50.

**Comment by Hwijune** [comment]
> It's so weird.I can't use agw_R50.

can i see you result ??

**Comment by gmt710** [comment]
Sorry,I didn't save the picture. My result display different person have high cosine similarity.

**Comment by gmt710** [comment]
Do you use intel/caffe?

**Comment by gmt710** [comment]
@baigang666 ，可不可以问一下，您用的什么版本的onnx转成功的呢？

**Comment by nanhui69** [comment]
> @gmt710 hello this is my demo:
> 
> # encoding: utf-8
> """ @author: Gang Bai @contact: [gbai@innovisgroup.com](mailto:gbai@innovisgroup.com) """
> 
> import argparse import os import torch import sys sys.path.append('/home/yan/Documents/bg-file/fast-reid-master')
> 
> from fastreid.config import get_cfg from fastreid.modeling.meta_arch import build_model from fastreid.utils.checkpoint import Checkpointer import cv2 import numpy as np import torch.nn.functional as F
> 
> save=False #是否保存模型为ONNX格式 def setup_cfg(args): cfg = get_cfg() cfg.merge_from_file(args.config_file) cfg.merge_from_list(args.opts) cfg.freeze() return cfg
> 
> def get_parser(): parser = argparse.ArgumentParser(description="Convert Pytorch to Caffe model")
> 
> ```
> parser.add_argument(
>     "--config-file",
>     default="/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/config.yaml",
>     metavar="FILE",
>     help="path to config file",
> )
> parser.add_argument(
>     "--output",
>     default='onnx_model',
>     help='path to save converted onnx model'
> )
> parser.add_argument(
>     "--opts",
>     help="Modify config options using the command-line",
>     default=["MODEL.WEIGHTS","/home/yan/Documents/bg-file/fast-reid-master/logs/market1501/mgn_R50-ibn/model_final.pth"],
>     nargs=argparse.REMAINDER,
> )
> return parser
> ```
> 
> def preprocessImg(img_path): img0 = cv2.imread(img_path) img0 = cv2.cvtColor(img0, cv2.COLOR_BGR2RGB) img0 = cv2.resize(img0, (128, 384)) img0 = img0.transpose((2, 0, 1)) img0 = img0[np.newaxis, :, :, :] data0 = torch.from_numpy(img0).cuda().float() data_input0={"images":data0} return data_input0 def ComptueSIM(v_a,v_b): la=len(v_a) lb=len(v_b) if la==lb: Vector_a=v_a Vector_b=v_b a=0 b1=0 b2=0 for i in range(la): a+=Vector_a[i]*Vector_b[i] b1+=Vector_a[i]*Vector_a[i] b2+=Vector_b[i]_Vector_b[i] similarity=a/((b1_b2)**0.5) return similarity else: return -1
> 
> if **name** == '**main**': #1. 解析参数 args = get_parser().parse_args() #2.加载模型 cfg = setup_cfg(args) cfg.defrost() cfg.MODEL.BACKBONE.PRETRAIN=False model = build_model(cfg)
> 
> ```
> Checkpointer(model).load(cfg.MODEL.WEIGHTS)
> model.eval()
> #3.提取特征
> ###############################################################
> 
> img_path = '/home/yan/Documents/bg-file/fast-reid-master/datasets/Market-1501-v15.09.15/query/181_320.jpg'
> #img_path = '/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/0002_c1s1_000551_00.jpg'
> data_input0=preprocessImg(img_path)
> with torch.no_grad():
>     prediction=model(data_input0)
>     pre_feat=F.normalize(prediction)
>     pre_feat=pre_feat.cpu().data
> 
> 
> np_array=np.asarray(pre_feat).reshape(2048)
> print(np_array)
> im0=cv2.imread(img_path)
> #cv2.imshow("StardardImage",im0)
> #cv2.waitKey()
> 
> Res = {}
> '''
> #################从文件中读取数据######################################
> TestImagePath="/home/yan/Documents/bg-file/fast-reid-master/tools/deploy/Image/TestImagePath.txt"
> test_list=[]
> 
> with open(TestImagePath,'r') as file_to_read:
>     while True:
>         lines = file_to_read.readline()  # 整行读取数据
>         if not lines:
>             break
>             pass
>         test_list.append(lines)
> for i,path in enumerate(test_list):
>     path_tmp=""
>     if i!=len(test_list)-1:
>         path_tmp=path[0:len(path)-1]
>         print(i,path_tmp)
>     else:
>         path_tmp=path
>         print(i,path_tmp)
>     frame=cv2.imread(path_tmp)
>     if frame is None:
>         print("图像打开失败，请确认图像路径是否正确")
>         break
>     path2=path_tmp
>     #@1 图像预处理
>     data_input1=preprocessImg(path2)
>     #@2 提取特征
>     with torch.no_grad():
>         prediction1 = model(data_input1)
>         pre_feat1 = F.normalize(prediction1)
>         pre_feat1 = pre_feat1.cpu().data
>     #@3 进行特征比对
>     np_array1=np.asanyarray(pre_feat1).reshape(2048)
>     SIM=ComptueSIM(np_array,np_array1)
>     print("两幅图像距离 ： ", SIM)
>     Res[path2]=SIM
>     #cv2.imshow("TestImage",frame)
>     #cv2.waitKey()
> print("特征比对结束")
> #######################################################################
> '''
> #####################从文件夹中读取数据###################################
> import os
> File_path='/home/yan/Documents/bg-file/fast-reid-master/datasets/Market-1501-v15.09.15/bounding_box_test'
> for fname in os.listdir(File_path):
>     # @1 图像预处理
>     data_input1 = preprocessImg(File_path+"/"+fname)
>     # @2 提取特征
>     with torch.no_grad():
>         prediction1 = model(data_input1)
>         pre_feat1 = F.normalize(prediction1)
>         pre_feat1 = pre_feat1.cpu().data
>     # @3 进行特征比对
>     np_array1 = np.asanyarray(pre_feat1).reshape(2048)
>     SIM = ComptueSIM(np_array, np_array1)
>     print("两幅图像距离 ： ", SIM)
>     Res[fname] = SIM
> ######################################################
> 
> #取出前top-5
> Final_res=sorted(Res.items(),key=lambda d:d[1],reverse=True)
> print("排序结束")
> Res_len=len(Final_res)
> 
> if Res_len<5:
>     for i in range(Res_len):
>         frame=cv2.imread(Final_res[i][0])
>         cv2.imshow(str(i),frame)
>         cv2.waitKey()
> else:
>     for i in range(5):
>         print(Final_res[i])
>         if i>4:
>             break
> print("TOP5---展示结束")
> ```

请问 这个baseline.py 怎么调用了两次预处理啊？这个对么？
