### ISSUE TITLE
Why the pretrain_path is empty when using bagtricks_R50.yml

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#184]
Why the pretrain_path is empty when using bagtricks_R50.yml

**Comment by L1aoXingyu** [comment]
If you use the ImageNet pretrain model, it will find the model path automatically through this code below

https://github.com/JDAI-CV/fast-reid/blob/ee634df2900996233473cb95a80029bd456cce97/fastreid/modeling/backbones/resnet.py#L268

**Comment by xiaopanchen** [comment]
Thank you
