### ISSUE TITLE
How to train the model with specific multi gpus in a single machine?

### ISSUE THREAD

**Issue by hfutzzw** [JDAI-CV/fast-reid#185]

**Comment by hfutzzw** [comment]
The training script: 
`CUDA_VISIBLE_DEVICES=8,9 python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --num-gpus 2 `
The training process  stayed in iteration 0, while the  single gpu training could operate normally.
![image](https://user-images.githubusercontent.com/30337787/87902616-ae7ed000-ca8c-11ea-9312-be294ecba42b.png)

**Comment by hfutzzw** [comment]
If I adopt the default port generation method in your code, it will report the following mistakes, and  we assign a specific port :12345
![image](https://user-images.githubusercontent.com/30337787/87902899-54323f00-ca8d-11ea-97f7-28e67b666fab.png)

**Comment by L1aoXingyu** [comment]
I think this command will work

```
CUDA_VISIBLE_DEVICES=8,9 python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --num-gpus 2
```

Are you sure your machine has 10 GPUs?

**Comment by hfutzzw** [comment]
When I modify the command `CUDA_VISIBLE_DEVICES=8,9 python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --num-gpus 2` to   `CUDA_VISIBLE_DEVICES=8,9 python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml ` it works.

**Comment by L1aoXingyu** [comment]
But in this way, you can only use 1 GPU.

**Comment by hfutzzw** [comment]
Yes, the single-gpu training, does the default multi-gpu training adopts the distributed manner? 
![image](https://user-images.githubusercontent.com/30337787/87904319-9c069580-ca90-11ea-9ed0-a0179eeb7b6a.png)

**Comment by hfutzzw** [comment]
Does you test your current released master code with multi-gpu training, thank you.

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/87904863-df153880-ca91-11ea-94cd-05e253b3d16f.png)

![image](https://user-images.githubusercontent.com/19245504/87905017-3ddab200-ca92-11ea-8665-c2da640c467f.png)


It can train normally and you can find the GPU utilization is about 90%.

**Comment by hfutzzw** [comment]
![image](https://user-images.githubusercontent.com/30337787/87905903-26042d80-ca94-11ea-88ab-d7818e7e612b.png)
It report the above mistakes.

**Comment by hfutzzw** [comment]
When I running the code on  another 8-GPU machine, the code running  normally. I guess it may related to machine type.
Thanks for your patience and contribution to Re-ID community.
