### ISSUE TITLE
when I running export2tf.py Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by XuShoweR** [JDAI-CV/fast-reid#188]
1. full code you wrote or full changes you made (`git diff`)
original code
2. what exact command you run:
python export2tf.py
3. __full logs__ you observed:

[07/21 18:10:14 fastreid]: Full config saved to /data/xuzy/ReID/fast-reid/tools/deploy/logs/config.yaml
[07/21 18:10:14 fastreid.utils.env]: Using a generated random seed 14181094
Exporting a ResNet model via ONNX ...
Segmentation fault (core dumped)

Python version:3.6.2
ubuntu 16.04

[GCC 5.4.0]
ONNX version:
1.7.0 source
ONNX-TF version:
1.6.0 source
Tensorflow version:
2.2.0

**Comment by L1aoXingyu** [comment]
It's a experimental feature for tensorflow export, so there will be bugs.

**Comment by dsnsabari** [comment]
@L1aoXingyu , do you have any updated code for converting the model into tensorflow 2 ?
