### ISSUE TITLE
Training results of market501,cuhk03 and msmt17

### ISSUE THREAD

**Issue by fengfengcxf** [JDAI-CV/fast-reid#190]
I have tried to combine market501,cuhk03 and msmt17 to trian the sbs_r50，but it seems the test results in cuhk03 and msmt17 are poor,could you please guide me to train those three datasets together...or tell me if the evaluation is reasonable or not?
![image](https://user-images.githubusercontent.com/68675033/88249550-58ea3380-ccd7-11ea-802b-37ca03000a50.png)

**Comment by L1aoXingyu** [comment]
You can check this issue

https://github.com/JDAI-CV/fast-reid/issues/163#issuecomment-673923126
