### ISSUE TITLE
请问您的算法支持断点训练吗？该如何做呢？

### ISSUE THREAD

**Issue by finger-monkey** [JDAI-CV/fast-reid#194]

**Comment by L1aoXingyu** [comment]
it's very easy, just add --resume, for example

```
python tools/train_net.py --config-file configs_file_path --resume

**Comment by finger-monkey** [comment]
> it's very easy, just add --resume, for example
> 
> ```
> python tools/train_net.py --config-file configs_file_path --resume
> ```
3Q , 大佬
