### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by crossover10** [JDAI-CV/fast-reid#202]
[07/30 18:04:36 fastreid.engine.defaults]: Auto-scaling the config to num_classes=30671, max_Iter=130200, wamrup_Iter=21700, freeze_Iter=0, delay_Iter=0, step_Iter=[65100, 108500], ckpt_Iter=43400, eval_Iter=43400.
[07/30 18:04:37 fastreid.modeling.backbones.resnet]: State dict keys error! Please check the state dict.
Traceback (most recent call last):
  File "./tools/train_net.py", line 81, in <module>
    args=(args,),
  File "/root/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 67, in main
    trainer = Trainer(cfg)
  File "/root/fast-reid/fastreid/engine/defaults.py", line 206, in __init__
    model = self.build_model(cfg)
  File "/root/fast-reid/fastreid/engine/defaults.py", line 377, in build_model
    model = build_model(cfg)
  File "/root/fast-reid/fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/root/fast-reid/fastreid/modeling/meta_arch/baseline.py", line 27, in __init__
    self.backbone = build_backbone(cfg)
  File "/root/fast-reid/fastreid/modeling/backbones/build.py", line 27, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg)
  File "/root/fast-reid/fastreid/modeling/backbones/resnet.py", line 325, in build_resnet_backbone
    raise e
  File "/root/fast-reid/fastreid/modeling/backbones/resnet.py", line 311, in build_resnet_backbone
    state_dict = torch.load(pretrain_path, map_location=torch.device('cpu'))['model']
KeyError: 'model'

**Comment by crossover10** [comment]
i have download the resnet50_ibn_a.pth.tar ,but still not work

**Comment by L1aoXingyu** [comment]
try to use the latest code and then set `BACKBONE.PRETRAIN` to `""`, it will automatically download the pretrain weights.

**Comment by crossover10** [comment]
> try to use the latest code and then set `BACKBONE.PRETRAIN` to `""`, it will automatically download the pretrain weights.

thanks，i  got it

**Comment by muzishen** [comment]
I find the same problem if I use the latest code with a pre-trained model (i.e., resnet50-ibn-a) and default veri config.
How can I solve this problem with KeyError 'model'.

**Comment by L1aoXingyu** [comment]
@muzishen Make sure `BACKBONE.PRETRAIN_PATH` to `""` if you want to use official pretrain ibn-model.

**Comment by muzishen** [comment]
> 
> 
> @muzishen Make sure `BACKBONE.PRETRAIN_PATH` to `""` if you want to use official pretrain ibn-model.

I have set the config with `BACKBONE.PRETRAIN_PATH: my pre train ibn-model path` . 
I don't know whether my understanding is wrong

**Comment by muzishen** [comment]
@L1aoXingyu         https://github.com/JDAI-CV/fast-reid/blob/e1aaeb358b2f77dfb773b38ab4b15597fc5a92f7/fastreid/modeling/backbones/resnet.py#L316  
1. If I take it out (i.e., `state_dict = torch.load(pretrain_path, map_location=torch.device('cpu'))),` it seems to work.
2. But I am not sure if the pre-training model has been successfully loaded.

[32m[08/02 10:38:21 fastreid.modeling.backbones.resnet]: [0mLoading pretrained model from /cache/resnet50_ibn_a.pth.tar
[32m[08/02 10:38:21 fastreid.modeling.backbones.resnet]: [0mSome model parameters are not in the checkpoint:
  [34mconv1.weight[0m
  [34mbn1.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.0.conv1.weight[0m
  [34mlayer1.0.bn1.IN.{weight, bias}[0m
  [34mlayer1.0.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.0.conv2.weight[0m
  [34mlayer1.0.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.0.conv3.weight[0m
  [34mlayer1.0.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.0.downsample.0.weight[0m
  [34mlayer1.0.downsample.1.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.1.conv1.weight[0m
  [34mlayer1.1.bn1.IN.{weight, bias}[0m
  [34mlayer1.1.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.1.conv2.weight[0m
  [34mlayer1.1.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.1.conv3.weight[0m
  [34mlayer1.1.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.2.conv1.weight[0m
  [34mlayer1.2.bn1.IN.{weight, bias}[0m
  [34mlayer1.2.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.2.conv2.weight[0m
  [34mlayer1.2.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer1.2.conv3.weight[0m
  [34mlayer1.2.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.0.conv1.weight[0m
  [34mlayer2.0.bn1.IN.{weight, bias}[0m
  [34mlayer2.0.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.0.conv2.weight[0m
  [34mlayer2.0.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.0.conv3.weight[0m
  [34mlayer2.0.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.0.downsample.0.weight[0m
  [34mlayer2.0.downsample.1.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.1.conv1.weight[0m
  [34mlayer2.1.bn1.IN.{weight, bias}[0m
  [34mlayer2.1.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.1.conv2.weight[0m
  [34mlayer2.1.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.1.conv3.weight[0m
  [34mlayer2.1.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.2.conv1.weight[0m
  [34mlayer2.2.bn1.IN.{weight, bias}[0m
  [34mlayer2.2.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.2.conv2.weight[0m
  [34mlayer2.2.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.2.conv3.weight[0m
  [34mlayer2.2.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.3.conv1.weight[0m
  [34mlayer2.3.bn1.IN.{weight, bias}[0m
  [34mlayer2.3.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.3.conv2.weight[0m
  [34mlayer2.3.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer2.3.conv3.weight[0m
  [34mlayer2.3.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.0.conv1.weight[0m
  [34mlayer3.0.bn1.IN.{weight, bias}[0m
  [34mlayer3.0.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.0.conv2.weight[0m
  [34mlayer3.0.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.0.conv3.weight[0m
  [34mlayer3.0.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.0.downsample.0.weight[0m
  [34mlayer3.0.downsample.1.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.1.conv1.weight[0m
  [34mlayer3.1.bn1.IN.{weight, bias}[0m
  [34mlayer3.1.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.1.conv2.weight[0m
  [34mlayer3.1.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.1.conv3.weight[0m
  [34mlayer3.1.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.2.conv1.weight[0m
  [34mlayer3.2.bn1.IN.{weight, bias}[0m
  [34mlayer3.2.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.2.conv2.weight[0m
  [34mlayer3.2.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.2.conv3.weight[0m
  [34mlayer3.2.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.3.conv1.weight[0m
  [34mlayer3.3.bn1.IN.{weight, bias}[0m
  [34mlayer3.3.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.3.conv2.weight[0m
  [34mlayer3.3.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.3.conv3.weight[0m
  [34mlayer3.3.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.4.conv1.weight[0m
  [34mlayer3.4.bn1.IN.{weight, bias}[0m
  [34mlayer3.4.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.4.conv2.weight[0m
  [34mlayer3.4.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.4.conv3.weight[0m
  [34mlayer3.4.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.5.conv1.weight[0m
  [34mlayer3.5.bn1.IN.{weight, bias}[0m
  [34mlayer3.5.bn1.BN.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.5.conv2.weight[0m
  [34mlayer3.5.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer3.5.conv3.weight[0m
  [34mlayer3.5.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.0.conv1.weight[0m
  [34mlayer4.0.bn1.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.0.conv2.weight[0m
  [34mlayer4.0.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.0.conv3.weight[0m
  [34mlayer4.0.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.0.downsample.0.weight[0m
  [34mlayer4.0.downsample.1.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.1.conv1.weight[0m
  [34mlayer4.1.bn1.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.1.conv2.weight[0m
  [34mlayer4.1.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.1.conv3.weight[0m
  [34mlayer4.1.bn3.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.2.conv1.weight[0m
  [34mlayer4.2.bn1.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.2.conv2.weight[0m
  [34mlayer4.2.bn2.{weight, bias, running_mean, running_var}[0m
  [34mlayer4.2.conv3.weight[0m
  [34mlayer4.2.bn3.{weight, bias, running_mean, running_var}[0m
  [34mNL_2.0.g.{weight, bias}[0m
  [34mNL_2.0.W.0.{weight, bias}[0m
  [34mNL_2.0.W.1.{weight, bias, running_mean, running_var}[0m
  [34mNL_2.0.theta.{weight, bias}[0m
  [34mNL_2.0.phi.{weight, bias}[0m
  [34mNL_2.1.g.{weight, bias}[0m
  [34mNL_2.1.W.0.{weight, bias}[0m
  [34mNL_2.1.W.1.{weight, bias, running_mean, running_var}[0m
  [34mNL_2.1.theta.{weight, bias}[0m
  [34mNL_2.1.phi.{weight, bias}[0m
  [34mNL_3.0.g.{weight, bias}[0m
  [34mNL_3.0.W.0.{weight, bias}[0m
  [34mNL_3.0.W.1.{weight, bias, running_mean, running_var}[0m
  [34mNL_3.0.theta.{weight, bias}[0m
  [34mNL_3.0.phi.{weight, bias}[0m
  [34mNL_3.1.g.{weight, bias}[0m
  [34mNL_3.1.W.0.{weight, bias}[0m
  [34mNL_3.1.W.1.{weight, bias, running_mean, running_var}[0m
  [34mNL_3.1.theta.{weight, bias}[0m
  [34mNL_3.1.phi.{weight, bias}[0m
  [34mNL_3.2.g.{weight, bias}[0m
  [34mNL_3.2.W.0.{weight, bias}[0m
  [34mNL_3.2.W.1.{weight, bias, running_mean, running_var}[0m
  [34mNL_3.2.theta.{weight, bias}[0m
  [34mNL_3.2.phi.{weight, bias}[0m
[32m[08/02 10:38:21 fastreid.engine.defaults]: [0mFreeze layer group "backbone" training for 1620 iterations
[32m[08/02 10:38:21 fastreid.utils.checkpoint]: [0mNo checkpoint found. Training model from scratch
[32m[08/02 10:38:21 fastreid.engine.train_loop]: [0mStarting training from iteration 0

**Comment by L1aoXingyu** [comment]
@muzishen Because official pretrain ibn-model has been updated, you need to download it again or set `PRETRAIN_PATH` to `""`, and it will automatically download.

**Comment by muzishen** [comment]
@L1aoXingyu I thought about it, so I downloaded it via a link with `GETTING_STARTED.md` yesterday.

**Comment by L1aoXingyu** [comment]
@muzishen `GETTING_STARTED.md` is the old version, the official new version is here https://github.com/XingangPan/IBN-Net.

**Comment by muzishen** [comment]
@L1aoXingyu Thank you. I'll try it !

**Comment by muzishen** [comment]
I downloaded the latest model and still have this problem.
`MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: '/cache/resnet50_ibn_a-d9d0bb7b.pth'`

**Comment by L1aoXingyu** [comment]
> I downloaded the latest model and still have this problem.
> 
> `MODEL:
> 
>   BACKBONE:
> 
>     WITH_IBN: True
> 
>     PRETRAIN: True
> 
>     PRETRAIN_PATH: '/cache/resnet50_ibn_a-d9d0bb7b.pth'`

delete pretrain path in your config

**Comment by muzishen** [comment]
How do I configure a custom pre-training model path?  I don't understand.

**Comment by L1aoXingyu** [comment]
It will find the path automatically，you can check the  code by yourself. 
The pretrain path is left for unofficially model, for  example if you train a pretrain model by yourself, you can set this and modify some codes.
