### ISSUE TITLE
onnx转tensorRT的问题

### ISSUE THREAD

**Issue by zt1112** [JDAI-CV/fast-reid#204]
pth->onnx时没有问题，onnx->trt时遇到[8] Assertion failed: trt_dtype == nvinfer1::DataType::kHALF && cast_dtype == ::ONNX_NAMESPACE::TensorProto::FLOAT的问题
显卡使用的是Tesla P40 ，只支持int8，trt_export.py是只支持在半精度显卡上运行吗？
my env : pytorch1.3 onnx1.7.0 tensorrt6

run:
python trt_export.py --name "reid" --output outputs/trt_model/ --onnx-model ./outputs/onnx_model/reid.onnx --height 384 --width 128

output:
----------------------------------------------------------------
Input filename:   ./outputs/onnx_model/reid.onnx
ONNX IR version:  0.0.4
Opset version:    9
Producer name:    pytorch
Producer version: 1.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
While parsing node number 0 [Cast]:
ERROR: builtin_op_importers.cpp:727 In function importCast:
[8] Assertion failed: trt_dtype == nvinfer1::DataType::kHALF && cast_dtype == ::ONNX_NAMESPACE::TensorProto::FLOAT
[2020-07-31 15:39:51.626] [error] error: could not parse onnx engine
[2020-07-31 15:39:51.626] [error] error: could not deserialize or build engine
Segmentation fault

**Comment by L1aoXingyu** [comment]
Which model do you use?

**Comment by zt1112** [comment]
> Which model do you use?
Thanks for reply.
I trained the model with ./configs/Market1501/sbs_R50-ibn.yml.

**Comment by zt1112** [comment]
Thanks for reply.
I trained the model with ./configs/Market1501/sbs_R50-ibn.yml.

> Which model do you use?

**Comment by L1aoXingyu** [comment]
Maybe ibn and non-local will occur some problems, and I just test vanilla ResNet50 to convert TensorRT. You can update tensorRT and try again.

Maybe you can remove nl first and check if it can be converted, then remove ibn, and do the same thing.

**Comment by L1aoXingyu** [comment]
I just test non-local, it can be converted, and maybe it's instancenorm problem.

**Comment by zt1112** [comment]
Yes, I updated tensorRT6 to tensorRT 7, it works.
But when save engine, the following error occurred, Is there any possible reason？

[2020-07-31 19:15:57.199] [info] fp16 support: false
[2020-07-31 19:15:57.199] [info] int8 support: true
[2020-07-31 19:15:57.199] [info] Max batchsize: 1
[2020-07-31 19:15:57.199] [info] Max workspace size: 22777216000
[2020-07-31 19:15:57.199] [info] Number of DLA core: 0
[2020-07-31 19:15:57.199] [info] Max DLA batchsize: 268435456
[2020-07-31 19:15:57.199] [info] Current use DLA core: 0
[2020-07-31 19:15:57.199] [info] build engine...
Detected 1 inputs and 1 output network tensors.
[2020-07-31 19:19:06.024] [info] serialize engine to ./outputs/trt_model/reid.engine
[2020-07-31 19:19:06.024] [info] save engine to ./outputs/trt_model/reid.engine...
Segmentation fault



> Maybe ibn and non-local will occur some problems, and I just test vanilla ResNet50 to convert TensorRT. You can update tensorRT and try again.
> 
> Maybe you can remove nl first and check if it can be converted, then remove ibn, and do the same thing.

**Comment by L1aoXingyu** [comment]
You can check if the engine if saved, then you can just load the trt engine to inference. You can check the difference between trt outputs and pytorch outputs.

**Comment by zt1112** [comment]
@L1aoXingyu Unfortunately the trt engine not saved.
Have you tried convert onnx to trt with IBN? 
When i set WITH_IBN: false and WITH_NL: true, it works well. But if set WITH_IBN: true , it will report error "Segmentation fault" when mEngine->serialize().

**Comment by L1aoXingyu** [comment]
Maybe instance norm will occur errors when converting to TensorRT. And I don't try to convert model with ibn layer.

**Comment by LilySys** [comment]
Is the problem solved？

**Comment by LilySys** [comment]
> @L1aoXingyu Unfortunately the trt engine not saved. Have you tried convert onnx to trt with IBN? When i set WITH_IBN: false and WITH_NL: true, it works well. But if set WITH_IBN: true , it will report error "Segmentation fault" when mEngine->serialize().

Is the problem solved?

**Comment by gejc2000** [comment]
问题解决了么
