### ISSUE TITLE
what's the format of input img size

### ISSUE THREAD

**Issue by GlassyWing** [JDAI-CV/fast-reid#205]
The config as flollow is confused, so which format should be right: (width, height) or (height width)

```
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256 128]
```

**Comment by L1aoXingyu** [comment]
height, width

**Comment by GlassyWing** [comment]
> height, width

Thanks for reply, and how to preprocess the image in the inference ?  Is the pix need to be normlized or scaled to 0-1?

**Comment by GlassyWing** [comment]
I'd test it, the image need to be standared but there is no need to scaled to 0-1
