### ISSUE TITLE
onnx_trt

### ISSUE THREAD

**Issue by fengfengcxf** [JDAI-CV/fast-reid#206]
how to get pytrt?  what's the difference between pytrt with tensorrt's python api, ,just like import tensorrt

**Comment by fengfengcxf** [comment]
it comes from tiny-tensorrt, right?
https://github.com/zerollzeng/tiny-tensorrt

**Comment by L1aoXingyu** [comment]
Yes, I'm considering if using `torchtrt` instead of `pytrt`.

Any suggestion?

**Comment by fengfengcxf** [comment]
thanks for your excellent research，，，i have tried pytrt, but i got the seem problem about DataType in trt7.  
![image](https://user-images.githubusercontent.com/68675033/89368411-12043100-d70e-11ea-842a-bb585cac6213.png)
so i changed it to tensorrt, it seems works. now i want to try to transfer the InstanceNormalization in ibn structure, but it exits the error that : "InstanceNormalization does not support dynamic inputs"

**Comment by zt1112** [comment]
I meet the same problem. And TensorRT7.1 supports dynamic inputs, you can try it.

> thanks for your excellent research，，，i have tried pytrt, but i got the seem problem about DataType in trt7.
> ![image](https://user-images.githubusercontent.com/68675033/89368411-12043100-d70e-11ea-842a-bb585cac6213.png)
> so i changed it to tensorrt, it seems works. now i want to try to transfer the InstanceNormalization in ibn structure, but it exits the error that : "InstanceNormalization does not support dynamic inputs"

**Comment by fengfengcxf** [comment]
Thank you very much.... I have made it. It seems trt7.1 is work well.
