### ISSUE TITLE
完整的行人重识别Demo

### ISSUE THREAD

**Issue by zengwbz** [JDAI-CV/fast-reid#215]
ReID模型前一般是行人检测模型，但实际场景中ReID的实用性(robust)不是很好，考虑使用行人跟踪算法，例如FairMOT替换行人检测模型，有没有相关这方面的介绍或者实验方案，指点一下。。谢谢

**Comment by L1aoXingyu** [comment]
实际业务中可以使用 MOT 算法对单摄像头下的行人进行跟踪，但是一般的方案都是 tracking by detection，也就是说还是依赖于一个好的检测网络，然后的跨摄像头的时候就用 reid 算法进行跨境跟踪。
