### ISSUE TITLE
pytorch1.3 is not support 

### ISSUE THREAD

**Issue by miraclebiu** [JDAI-CV/fast-reid#236]
in ./fastreid/solver/optim/adam.py

**Comment by miraclebiu** [comment]
TypeError: zeros_like() received an invalid combination of arguments - got (Parameter, memory_format=torch.memory_format), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor input, bool requires_grad)
      didn't match because some of the keywords were incorrect: memory_format

**Comment by L1aoXingyu** [comment]
We only officially support pytorch 1.6 now.

**Comment by miraclebiu** [comment]
> We only officially support pytorch 1.6 now.

so install.md should modify

**Comment by L1aoXingyu** [comment]
fixed.
