### ISSUE TITLE
Why Pair-wise Circle loss explosion?

### ISSUE THREAD

**Issue by kevinbro96** [JDAI-CV/fast-reid#244]
I add the pair-wise circle loss, but the loss value is very huge, up to 300-400.
I used your defaut  set:  _m=0.25, _s =128, _scale =1.0.
Should set the _scale very small like 0.001? But it is diffierent from circle loss paper.

**Comment by L1aoXingyu** [comment]
We are looking forward to the official open-source code of circle loss.

**Comment by L1aoXingyu** [comment]
Pairwise circle loss is updated, you can try it.
