### ISSUE TITLE
您好，请教下如何才能在做dataset的时候保留相机编号为字符串形式呢，即把 relable_cam 改成False，

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#248]
您的代码里会把相机编号统一转成整数形式，我尝试把 relable_cam 改成False，但是经过Dataloader之后camid的输出就变成了['<map object at 0x7f6b3bc27190>', '<map object at 0x7f6b3bc27390>', '<map object at 0x7f6b3bc27b90>']，请问如何修改呢？还是你的代码里相机编号一定要转成整数

**Comment by L1aoXingyu** [comment]
你可以试试最新的 code，不再会强制要求 camid 是一个整数了。

**Comment by TCHeish** [comment]
For enable dataset COMBINEALL option
should add one more line 

 camid = self.dataset_name + "_" + str(camid)

right?

https://github.com/JDAI-CV/fast-reid/blob/57710a9df7e17ec0eef5a756065d8339ca9f4096/fastreid/data/datasets/bases.py#L106

**Comment by L1aoXingyu** [comment]
yes, you are right. A dataset prefix needs to be added for relabeling.
