### ISSUE TITLE
DefaultPredictor using F.normalize twice

### ISSUE THREAD

**Issue by TCHeish** [JDAI-CV/fast-reid#250]
Is there any reason using  F.normalize twice after extract feature from model?

https://github.com/JDAI-CV/fast-reid/blob/0d2c477060e7d013ffbf4e02e91ab2615f195cbf/fastreid/engine/defaults.py#L157

features = F.normalize(predictions)
features = F.normalize(features).cpu().data

Thanks!

**Comment by L1aoXingyu** [comment]
fixed
