### ISSUE TITLE
关于训练engine中的data_loader_iter

### ISSUE THREAD

**Issue by luuuyi** [JDAI-CV/fast-reid#251]
作者你好，我有注意到你在train_loop.py中定义了一个run_step函数，这个函数不断从self._data_loader_iter中用next函数取batch，但据我了解，dataloader被取完以后还需要再做一遍iter(data_loader)，这样next(self._data_loader_iter)才不会报错，但是我没看到你在代码哪个位置这样做了，能麻烦解释下这个疑惑么

**Comment by L1aoXingyu** [comment]
你可以看看下面的 code

https://github.com/JDAI-CV/fast-reid/blob/57710a9df7e17ec0eef5a756065d8339ca9f4096/fastreid/data/samplers/data_sampler.py#L49
