### ISSUE TITLE
 state_dict = torch.load(pretrain_path, map_location=torch.device('cpu'))['model']  # ibn-net KeyError: 'model'

### ISSUE THREAD

**Issue by yukaizhou** [JDAI-CV/fast-reid#253]
state_dict = torch.load(pretrain_path, map_location=torch.device('cpu'))['model']  # ibn-net
KeyError: 'model'

**Comment by yukaizhou** [comment]
当我使用ResNet50-ibn训练时， 加载预训练模型时报错，求指教，谢谢

**Comment by L1aoXingyu** [comment]
请使用最新的 code
