### ISSUE TITLE
Does distill model support deploy to caffe ?

### ISSUE THREAD

**Issue by gmt710** [JDAI-CV/fast-reid#254]
Hello,I’ve trained distill model and get better performance.
Does distill model support deploy to caffe ?
How to do it about yaml file? Can we use R50's yaml ?

**Comment by L1aoXingyu** [comment]
Distillation is actually a training technique and it has nothing to do with the model architecture. 
So if you choose the model which is supported to convert to caffe, then after distilling, it sill can convert to caffe format.
