### ISSUE TITLE
Details about the performance of VeRI-Wild dataset

### ISSUE THREAD

**Issue by yanbai1993** [JDAI-CV/fast-reid#257]
Thank you for your good job on person and vehicle ReID.
For the veri-wild dataset, have you removed the images with the same camera id and same vehicle id as query image in the gallery set?

**Comment by JinkaiZheng** [comment]
> Thank you for your good job on person and vehicle ReID.
> For the veri-wild dataset, have you removed the images with the same camera id and same vehicle id as query image in the gallery set?

Hi~ We do not remove the images with the same camera id and same vehicle id as query image in the gallery set.
Best regards.

**Comment by JinkaiZheng** [comment]
> Thank you for your good job on person and vehicle ReID.
> For the veri-wild dataset, have you removed the images with the same camera id and same vehicle id as query image in the gallery set?

Hi~ Sorry for my wrong answer last time. We **did remove** the images with the same camera id and same vehicle id as query image in the gallery set.

Best regards.
