### ISSUE TITLE
pytorch to caffe problem

### ISSUE THREAD

**Issue by caicai2526** [JDAI-CV/fast-reid#262]
你好，在使用训练完的pytorch转caffe模型的时候，两个模型输出特征不一样，之后我进行一层一层的特征对比，发现pytorch中有non loal的操作，在转为的caffe模型中没有，导致在caffe模型的relu_blob19后的特征不一样，请问这个应该怎么修改

**Comment by L1aoXingyu** [comment]
non-local 不支持直接转 caffe，需要自己在 caffe 里面自己手写 layer
