### ISSUE TITLE
How to train the efficientnet? 

### ISSUE THREAD

**Issue by clw5180** [JDAI-CV/fast-reid#267]
I try to modify the code, but it's a little bit hard for me ....

**Comment by L1aoXingyu** [comment]
You don't need to modify the code, just change some configurations as below

```python
BACKBONE:
	NAME: "build_effnet_backbone"
	DEPTH: "b4"
  	LAST_STRIDE: 1
  	FEAT_DIM: 1792
  	PRETRAIN: True
  	PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet34_ibn_a-94bc1577.pth"
```

**Comment by clw5180** [comment]
> You don't need to modify the code, just change some configurations as below
> 
> ```python
> BACKBONE:
> 	NAME: "build_effnet_backbone"
> 	DEPTH: "b4"
>   	LAST_STRIDE: 1
>   	FEAT_DIM: 1792
>   	PRETRAIN: True
>   	PRETRAIN_PATH: "PATH TO YOUR PRETRAIN MODEL"
> ```

非常感谢您，另外我对比了一下您的项目和罗老师那边的baseline，r101 ibn的结果差不多，但是相同的rerank参数，这边基本没变化，但那边涨点明显，您推测可能是什么原因呢

**Comment by L1aoXingyu** [comment]
我之前试了一下 re-rank，应该可以涨很多点的，不至于基本没变化，后面我用 faiss 优化过检索速度，也许是那个时候 code 改了一些出来问题，我等会儿验证一下 re-rank 是否有问题。

**Comment by L1aoXingyu** [comment]
我试了一下，这是 rerank 之前的
![image](https://user-images.githubusercontent.com/19245504/93744637-c0175c00-fc24-11ea-8abf-2407df062c40.png)
这是 rerank 之后的
![image](https://user-images.githubusercontent.com/19245504/93744662-cc9bb480-fc24-11ea-9fea-2358ef76fd35.png)
还是涨点非常明显，特别是 mAP

**Comment by clw5180** [comment]
> @clw5180
> 
> 我试了一下，这是 rerank 之前的
> ![image](https://user-images.githubusercontent.com/19245504/93744637-c0175c00-fc24-11ea-8abf-2407df062c40.png)
> 这是 rerank 之后的
> ![image](https://user-images.githubusercontent.com/19245504/93744662-cc9bb480-fc24-11ea-9fea-2358ef76fd35.png)
> 还是涨点非常明显，特别是 mAP，使用的是默认参数

打扰您了，那我再研究一下吧，非常感谢！

**Comment by gmt710** [comment]
@L1aoXingyu ，廖老师，您好。如果想直接测试一个模型rerank前后的结果，可以直接修改yaml文件么？

**Comment by gmt710** [comment]
@clw5180 ，可行的

**Comment by nobody-cheng** [comment]
@clw5180 请问你是用efficientnet作为backbone精度是否有提升

**Comment by gmt710** [comment]
@L1aoXingyu @clw5180 ，两位好，我尝试了下Effnet，B4的性能好像不如ResNet50。是不是跟ResNet152一样的情况呢？
```
| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   |
|:-----------|:---------|:---------|:----------|:-------|:-------|
| Market1501 | 93.53%   | 97.68%   | 98.60%    | 83.34% | 53.52% |
```

**Comment by huanghoujing** [comment]
基于Base-bagtricks.yml的设定：
```yml
_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    NAME: "build_effnet_backbone"
    FEAT_DIM: 1536
    DEPTH: "b3"
    PRETRAIN_PATH: ""

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/bagtricks_efficient_net_b3"
```
ImageNet预训练模型为`https://dl.fbaipublicfiles.com/pycls/dds_baselines/161305060/EN-B3_dds_8gpu.pyth`，EfficientNet B3的性能和ResNet18相当。如下
```
| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   |
|:-----------|:---------|:---------|:----------|:-------|:-------|
| Market1501 | 91.78%   | 97.18%   | 98.34%    | 79.42% | 46.55% |
```

请教一下，有没有哪位跑过这个模型，这个结果是否正常?
