### ISSUE TITLE
Pedestrian alignment

### ISSUE THREAD

**Issue by fengfengcxf** [JDAI-CV/fast-reid#269]
Did you have tried Pedestrian alignment to preprocess those datasets？i don't know wether it is helpful to use Pedestrian alignment methods improving adaptability in practical application scenarios.

**Comment by L1aoXingyu** [comment]
Actually, I don't try pedestrian alignment to preprocess the datasets. The reasons are below:
1. I need to perform pose estimation to get the keypoints and then do the alignment when training and testing. It will bring extra overhead.
2. When detector is bad, you need to align the pedestrian, but in my situation, the detector is very good. So I don't need to consider the alignment problem.

**Comment by fengfengcxf** [comment]
thanks for your incere answer. The reason why i have asked this question is that i had tested our models in  some small space scene in door where the angle that camera is installed may causes distortion of pedestrian.
