### ISSUE TITLE
八卡分布式训练报错c10::Error

### ISSUE THREAD

**Issue by DongfeiJi** [JDAI-CV/fast-reid#270]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
<>
```
2. what exact command you run:
python tools/train_net.py --config-file ./configs/Market1501/sbs_R101-ibn.yml --num-gpus 8
3. what you observed (including __full logs__):
```
<terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal instruction was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42>
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:

```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in

**Comment by L1aoXingyu** [comment]
可以2卡或者4卡训练吗？

**Comment by DongfeiJi** [comment]
> 可以2卡或者4卡训练吗？

我用的2080ti，2卡或者4卡也不可以
这个错误不是一直有，清空所有用户进程第一次提交可以训，第二次就会报错，
分布式训的时候，终止train后也会有残留进程一直卡在显存里面。

**Comment by L1aoXingyu** [comment]
你把进程全部 kill 之后，可以8卡训练吗？

**Comment by DongfeiJi** [comment]
> 你把进程全部 kill 之后，可以8卡训练吗？

马上提交不可以，等个几十分钟就可以了，随机性的。。。。。

**Comment by DongfeiJi** [comment]
> 你把进程全部 kill 之后，可以8卡训练吗？

这个问题还是比较好复现的，直接跑8卡，暂停掉，再跑就会出现

**Comment by L1aoXingyu** [comment]
我这边是4卡的 P40，每次停掉之后再跑是没有问题的，我觉得还是进程残留，没有完全 kill 掉，这可能和你们的服务器有关。

**Comment by DongfeiJi** [comment]
有可能，我四卡也会出现问题。还有一个现象，就是跑r101ibn，batch只设置64，但是会在刚开始训练的时候加载模型，显存波动很大，导致OOM，我的卡显存只有11G……2080ti可以训batch为64的r101-ibn么





------------------ 原始邮件 ------------------
发件人: Xingyu Liao <notifications@github.com&gt;
发送时间: 2020年9月17日 16:16
收件人: JDAI-CV/fast-reid <fast-reid@noreply.github.com&gt;
抄送: Dongfei Ji <648513181@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[JDAI-CV/fast-reid] 八卡分布式训练报错c10::Error (#270)






我这边是4卡的 P40，每次停掉之后再跑是没有问题的，我觉得还是进程残留，没有完全 kill 掉，这可能和你们的服务器有关。

**Comment by L1aoXingyu** [comment]
11g 单卡应该跑不了 r101-ibn，可以试试 amp 混合精度训练，应该可以减小一半显存。
