### ISSUE TITLE
If we want to train kd model, do we need to train on the same dataset?(same ID numbers)

### ISSUE THREAD

**Issue by gmt710** [JDAI-CV/fast-reid#271]
Hello, I found that training the teacher model on the combined big dataset and training the student model on the small dataset are better than both the teacher model and the student model on the merged big dataset. When the number of ID is inconsistent, KL loss function should not be trained and wrong, but from the test results, it improves the compactness within the class.

**Comment by L1aoXingyu** [comment]
Hmmm, interesting! Which distill loss function were you used?

More specifically, the teacher model is trained on the combined big dataset, and the student model is trained on the small dataset. Then kd model is trained on the small dataset?
Which dataset were you used for testing?

**Comment by gmt710** [comment]
yes, kd model is trained on the small dataset. I set MODEL.HEADS.NUM_CLASSES = big dataset number.
Market I used.
