### ISSUE TITLE
something wrong using get_norm.

### ISSUE THREAD

**Issue by KRYSTALLJY** [JDAI-CV/fast-reid#272]
When I run
python ./tools/train_net.py --config-file ./configs/Market1501/mgn_R50-ibn.yml MODEL.DEVICE "cuda:0"

Error occurs:
    nn.Conv2d(1024, 2048, 1, bias=False), get_norm(bn_norm, 2048,num_splits))),#
TypeError: get_norm() takes 2 positional arguments but 3 were given

**Comment by L1aoXingyu** [comment]
fixed, you can update the code and try again.
