### ISSUE TITLE
Where to download the resnet pretrain model?

### ISSUE THREAD

**Issue by ShowTsai** [JDAI-CV/fast-reid#275]
The ```PRETRAIN_PATH``` in ```fast-reid/configs/Base-bagtricks.yml``` is:
```"/export/home/lxy/.cache/torch/checkpoints/resnet50-19c8e357.pth"```.
Where to download the file?
Thanks.

**Comment by AnhPC03** [comment]
@ShowTsai You can choose pretrained model in [model zoo](https://github.com/JDAI-CV/fast-reid/blob/master/docs/MODEL_ZOO.md)

**Comment by L1aoXingyu** [comment]
@ShowTsai This is the imagenet pretrain model, you can delete `PRETRAIN_PATH` and then it will download automatically.
Or you can download it by using this way 
```python
from torchvision.models import resnet50
resnet50(pretrained=True)
```

**Comment by ShowTsai** [comment]
Thanks!
BTW, is this the only pretrained model used in this project?

**Comment by L1aoXingyu** [comment]
The different backbone has its own imagenet-pretrained model.
