### ISSUE TITLE
About the version of torch, i.e. from torch.cuda import amp

### ISSUE THREAD

**Issue by shengjie-shi** [JDAI-CV/fast-reid#276]
firstly really appreciate for your excellent work!

I got an issue when trying to implement your code.
The required torch version is 1.6.0 cause one module "amp" will be used in ./fastreid/engine/train_loop.py.
However, on the server I have no other choice but only torch==1.4.0+cu100, which dose not contain "amp"..
Tried to replace torch.cuda.amp with apex.amp but still does not work (seems they are not equally)

Could you please tell me if it is possible to  find some substitutions so that I can run it with torch==1.4.0 or just omit torch.cuda.amp?

Thanks a lot

**Comment by L1aoXingyu** [comment]
You can just remove codes related `torch.amp`
https://github.com/JDAI-CV/fast-reid/blob/df823da09a1b24befbafd3bd3a5b938b7ef6de3f/fastreid/engine/train_loop.py#L211
Then it will work.

**Comment by shengjie-shi** [comment]
many thx for your fast reply! I'll try it out
