### ISSUE TITLE
Hello, I want to look at the features that the model focuses on by using the class activation map. How do I do this

### ISSUE THREAD

**Issue by CompliceU** [JDAI-CV/fast-reid#279]
Hello, I want to look at the features that the model focuses on by using the class activation diagram. How do I do this

**Comment by CompliceU** [comment]
@L1aoXingyu

**Comment by L1aoXingyu** [comment]
Do you want to visualize like this?
![Uploading image.png…]()

**Comment by CompliceU** [comment]
yes,i hope i can make acmap on my pictures, and then i can change my dataset to finetune my model.thx @L1aoXingyu

**Comment by CompliceU** [comment]
> Do you want to visualize like this?
> ![image](https://user-images.githubusercontent.com/19245504/94223830-76c85480-ff23-11ea-8211-ccee0b2bb0d1.png)
yes, do you have any plan to add this function?

**Comment by L1aoXingyu** [comment]
I am busy with hyperparameter optimization recently, so I don't have any plan for visualization.

**Comment by gmt710** [comment]
@CompliceU ,may this helps.https://github.com/KaiyangZhou/deep-person-reid.git

**Comment by CompliceU** [comment]
@gmt710  Thanks a lot for your kindness, have you try it before?

**Comment by gmt710** [comment]
yes, I've tried this(https://blog.csdn.net/qq_35975447/article/details/108651337).
You can modify it with your own.

**Comment by TelBotDev** [comment]
> I am busy with automatic hyperparameter optimization recently, so I don't have any plan for visualization.

Looking forward to adding this feature. 

Today I tried to follow your code and use a hook to get the intermediate feature map, but it didn't work.

_Why didn't it succeed? Because it reported A LOT OF errors that I could not solve._
