### ISSUE TITLE
train_net.py执行时出错

### ISSUE THREAD

**Issue by 81961916** [JDAI-CV/fast-reid#280]
File "./tools/train_net.py", line 14, in <module>
    from fastreid.config import get_cfg
  File "./fastreid/config/__init__.py", line 7, in <module>
    from .config import CfgNode, get_cfg
  File "./fastreid/config/config.py", line 14, in <module>
    from ..utils.file_io import PathManager
  File "./fastreid/utils/file_io.py", line 319
    _PATH_HANDLERS: MutableMapping[str, PathHandler] = OrderedDict()
                  ^
SyntaxError: invalid syntax

**Comment by ShowTsai** [comment]
Which python version you use?

**Comment by L1aoXingyu** [comment]
Please use python3.

**Comment by xiejiahong999** [comment]
> Which python version you use?

I meet the same error and my python version is 3.5.3

**Comment by ShowTsai** [comment]
@xiejiahong999 please use python3.6 or above
