### ISSUE TITLE
about the datasets' "camid "

### ISSUE THREAD

**Issue by yyyyykp** [JDAI-CV/fast-reid#285]
Excuse me, If I use my own datasets, how should I set the "camid"?
If I set them to the same id, will there be any negative effects?

**Comment by L1aoXingyu** [comment]
There will be no negative effects if you don't know the exact camera id.

**Comment by yyyyykp** [comment]
> There will be no negative effects if you don't know the exact camera id.

but i find in
[fastreid/evaluation/rank.py](https://github.com/JDAI-CV/fast-reid/blob/master/fastreid/evaluation/rank.py)
Line 108
it said "Key: for each query identity, its gallery images from the same camera view are discarded."
Does this mean that I need to set the id in query images and gallery  images to be different?

**Comment by L1aoXingyu** [comment]
This is in the test phase and there will no negative effect in training phase.

**Comment by yyyyykp** [comment]
> This is in the test phase and there will no negative effect in training phase.

Thanks for your reply,  now I set the camid in query images to "2", and the camid in gallery images to "3". Could I get the correct result in the **test** phase?  or is there anything else i need to do？

**Comment by L1aoXingyu** [comment]
If you don't have camera information, you can set all query images' cameras different from gallery images' cameras. Then you can get the result.

**Comment by yyyyykp** [comment]
> If you don't have camera information, you can set all query images' cameras different from gallery images' cameras. Then you can get the result.

i get it! Thanks a lot!
