### ISSUE TITLE
How to pass dataset kwargs through config file

### ISSUE THREAD

**Issue by addisonklinke** [JDAI-CV/fast-reid#290]
I noticed that several dataset classes have kwargs in addition to the `root='datasets'` that's provided in the `ImageDataset` base class' `__init__` signature. For instance

* Market1501
    * `market_1501_500k=False`
* CUHK03
    * `split_id=0`
    * `cuhk03_labeled=True`
    * `cuhk03_classic_split=False`
* VehicleID
    * `test_list=''`
* VeRiWild
    * `query_list=''`
    * `gallery_list=''`

I do not see any documentation on how the YAML configuration file can be used to run `train_net.py` with something other than the above default values. In the training script procedure, I noticed the dataset gets built from the registry in `data/build.py:build_reid_train_loader()` which only passes the `combineall` kwarg the the dataset class initializer

```
dataset = DATASET_REGISTRY.get(d)(root=_root, combineall=cfg.DATASETS.COMBINEALL)
```

In order to support the other kwargs above, it seems the above line would have to be modified in the source code. For instance, to support Market1501's kwarg

```
other_kwargs = {
    'market_1501_500k': cfg.DATASETS.get('MARKET_1501_500k', False)
}
dataset = DATASET_REGISTRY.get(d)(root=_root, combineall=cfg.DATASETS.COMBINEALL, **other_kwargs)
```

However, this would get rather cumbersome adding support for all the various kwargs used by different datasets. Do you have a recommended approach to handle this situation? Perhaps we could create `other_kwargs` such that it contains all config keys under `DATASETS` which are not commonly shared

```
known_keys = ['NAMES', 'TESTS', 'COMBINEALL']
other_kwargs = {k.lower(): v for k, v in cfg.DATASETS.items() if k not in known_keys}
```

**Comment by L1aoXingyu** [comment]
Good question, let me think about it.

**Comment by L1aoXingyu** [comment]
@addisonklinke Hi, I just pushed a commit that solved this problem, you can pass other kwargs following the way below

```python
class Trainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg):
		other_kwargs = {
				'market_1501_500k': cfg.DATASETS.get('MARKET_1501_500k', False)}
        return build_reid_train_loader(cfg, **other_kwargs)
```
