### ISSUE TITLE
Hyper-Parameter Optimization 

### ISSUE THREAD

**Issue by L1aoXingyu** [JDAI-CV/fast-reid#293]
This guide explains how to train your model with hyperparameters optimization.

## Before You Start

Following **Getting Started** to setup the environment and install requirements.txt dependencies.

We provide two search algorithms, `HyperOptSearch` and `TuneBOHB`. You can refer [here](https://docs.ray.io/en/latest/tune/api_docs/suggestion.html) to learn more information about search algorithms in `ray[tune]`. In addition, we provide four trial schedulers, `ASHA`, `HyperBand`, `PBT`, and `BOHB`. More information about trial schedulers can be found [here](https://docs.ray.io/en/latest/tune/api_docs/schedulers.html).

## Design Hyperparameters Search Space

There are many hyperparameters used for various training settings, such as batch size, learning rate, weight decay, and so on. Better initial guess will produce better results, so it's important to initialize these values range properly before tuning.

Each search algorithm has a specific way of defining the search space, for example, you can define `bohb` hyperparameters space as below 

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/train_hpo.py#L178-L190

Here, we just want to search `batch_size` and `num_instance`. You can define your own hyperparameters search space.

Then, you need to modify function `update_config` to make the hyperparameter valid.

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/train_hpo.py#L96-L118

At last, you can decide which hyperparameters can be displayed on the console output.

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/train_hpo.py#L206

## Define Fitness Score

Fitness is the value we seek to maximize. In fastreid, we have defined a default fitness score as a weighted combination of metrics: Rank@1 and mAP.

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/hporeid/tune_hooks.py#L56

Then just pass the name `score` to metric, and `max` to mode.

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/train_hpo.py#L138

## HPO Train

Then you can train hyperparameter optimization with BOHB(Bayesian Optimization with HyperBand) search algorithm with 20 trials like the following command line

```bash
python3 projects/HPOReID/train_hpo.py --config-file projects/HPOReID/configs/baseline.yml --srch-algo "bohb" --num-trials 20
```
If you don't have enough resource, you can allocate the specific GPU and CPU from `resources_per_trial` 

https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/projects/HPOReID/train_hpo.py#L213

- - - 
Frequently asked questions about `ray[tune]` can be found [here](https://docs.ray.io/en/latest/tune/tutorials/overview.html#frequently-asked-questions).

**Comment by huangzhenjie** [comment]
What is the method of hyper-parameter optimization and are there any papers about it?

**Comment by L1aoXingyu** [comment]
This project supports [Hyperband](https://arxiv.org/abs/1603.06560), [bohb](https://arxiv.org/abs/1807.01774) and [population-based training](https://arxiv.org/abs/1711.09846).

**Comment by huangzhenjie** [comment]
when i try to train, the error is "train_hpo.py: error: unrecognized arguments: --srch-algo", What should I do?

**Comment by L1aoXingyu** [comment]
Use the latest code and try again.

**Comment by huangzhenjie** [comment]
I would like to ask what configuration is required for the machine to run Hyper-Parameter Optimization, thanks.

**Comment by L1aoXingyu** [comment]
Nothing special for machine configuration.

**Comment by huangzhenjie** [comment]
but when I try to train it, the error is "TuneError: Insufficient cluster resources to launch trial: trial requested 12 CPUs, 1 GPUs, but the cluster has only 8 CPUs, 1 GPUs, 8.64 GiB heap, 2.98 GiB objects (1.0 node:172.28.40.63, 1.0 accelerator_type:GTX)."
