### ISSUE TITLE
更换不同的数据集需要修改pixel_mean和pixel_std吗？

### ISSUE THREAD

**Issue by Sunbees** [JDAI-CV/fast-reid#295]
你好，使用不同的数据集PIXEL_MEAN和PIXEL_STD需要根据数据集计算吗？还是只要保持原来的默认参数？
期待解答

**Comment by L1aoXingyu** [comment]
pixel_mean 和 pixel_std 都是 imagenet 数据集上的结果，如果还是使用 imagenet pretrain model，那么可以一直使用这个 pixel_mean 和 pixel_std.

**Comment by yyyyykp** [comment]
> pixel_mean 和 pixel_std 都是 imagenet 数据集上的结果，如果还是使用 imagenet pretrain model，那么可以一直使用这个 pixel_mean 和 pixel_std.

你好，请问如果我修改了数据集的SIZE_TRAIN和SIZE_TEST，PIXEL_MEAN和PIXEL_STD还需要重新计算吗？

**Comment by L1aoXingyu** [comment]
不用，这个和 size 没关系

**Comment by yyyyykp** [comment]
> 不用，这个和 size 没关系
好的 谢谢~
