### ISSUE TITLE
about multi-gpus training and batchsize

### ISSUE THREAD

**Issue by yyyyykp** [JDAI-CV/fast-reid#302]
Hello, If i use multi-gpus to train the model, should i set **BACKBONE.NORM** and **HEADS.NORM** to syncBN？
And I want to modify the batchsize, Now I just set **SOLVER.IMS_PER_BATCH** = 128 in [configs/Base-bagtricks.yml](https://github.com/JDAI-CV/fast-reid/blob/master/configs/Base-bagtricks.yml).  In order to get a better result, should i modify other parameters, such as the **DATALOADER.NUM_INSTANCE**?

**Comment by L1aoXingyu** [comment]
According to my experiments, `syncBN` and `BN` have no much difference when using large batchsize.
Usually you need to modify `NUM_INSTANCE` if you want to increase the batchsize. 
This is related to your data distribution. The default values are related to open dataset, such as Market1501, DukeMTMC. You can just try some values by yourself and decide which values are better.

**Comment by yyyyykp** [comment]
> According to my experiments, `syncBN` and `BN` have no much difference when using large batchsize.
> Usually you need to modify `NUM_INSTANCE` if you want to increase the batchsize.
> This is related to your data distribution. The default values are related to open datasets, such as Market1501, DukeMTMC. You can just try some values by yourself and decide which values are better.

thanks, i get it.
