### ISSUE TITLE
I download the SBS Resnet101-ibn for market1501.and when i use it for fine-tune,the checkpoint is incompatible with the model. 其他层匹配，non_local模块不匹配，例如checkpoint中NL_2.0.g.weight 为[1 ,512,1,1]而模型为[256,512,1,1]

### ISSUE THREAD

**Issue by chongyangwang-song** [JDAI-CV/fast-reid#303]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
<put diff or code here>
```
2. what exact command you run:
3. what you observed (including __full logs__):
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:

```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in

**Comment by dli2016** [comment]
I meet the same problem ...

**Comment by L1aoXingyu** [comment]
我现在把 nl 改回来了，可以使用新版 code 再试试。
