### ISSUE TITLE
PartialReID Project

### ISSUE THREAD

**Issue by caicai2526** [JDAI-CV/fast-reid#309]
PartialReID的pytorch模型如何转为caffe模型？

**Comment by L1aoXingyu** [comment]
projects 里面的模型支持优先级不高，转 caffe 可能会有一些问题，需要自己搞定

**Comment by caicai2526** [comment]
> projects 里面的模型支持优先级不高，转 caffe 可能会有一些问题，需要自己搞定

好的，谢谢。
转的caffe模型遇到这样的问题，是什么原因啊？
RuntimeError: 

(Tensor self, ...) -> (Tensor 0):
Expected a value of type 'Tensor' for argument 'self' but instead found type 'List[Tensor]'.
Empty lists default to List[Tensor]. Add a variable annotation to the assignment to create an empty list of another type (torch.jit.annotate(List[T, []]) where T is the type of elements in the list for Python 2)
:
  File "C:\Users\Chengfei Cai\.conda\envs\FastReID\lib\site-packages\torchvision\ops\poolers.py", line 68
        """
        # Compute level ids
        s = torch.sqrt(torch.cat([box_area(boxlist) for boxlist in boxlists]))
                       ~~~~~~~~~ <--- HERE

        # Eqn.(1) in FPN paper
