### ISSUE TITLE
关于文章模型的复现

### ISSUE THREAD

**Issue by m250317460** [JDAI-CV/fast-reid#310]
我是一名刚读研的同学，目前研究方向是车辆重识别，想要复现一下这篇文章中的模型，但是自己知识还不太够，所以创建了一个QQ讨论组，想和大家一起完成文章的复现。群号是：1136870868。欢迎各位进群讨论

**Comment by alicera** [comment]
同学有车辆重识别图片?
Could you provide the images with google drive?
Thanks
P.S. I know the dataset link, but I cant download.

**Comment by m250317460** [comment]
I Just have veri-776 dataset,if necessary i'm glad to share with you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JDAI-CV/fast-reid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JDAI-CV/fast-reid] 关于文章模型的复现 (#310)





 
同学有车辆重识别图片?
 Could you provide the images with google drive?
 Thanks
 P.S. I know the dataset link, but I cant download.

**Comment by alicera** [comment]
I want it.
Thanks.

I only find this https://github.com/PKU-IMRE/VERI-Wild

**Comment by m250317460** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JDAI-CV/fast-reid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JDAI-CV/fast-reid] 关于文章模型的复现 (#310)





 
I want it.
 Thanks.
 
I only find this https://github.com/PKU-IMRE/VERI-Wild
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

VeRi.zip (945.51M, 2021年05月08日 20:05 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e61313224f5d1f4a7ebda3c4036041f03595456545307061e030405571b025252031c500303001d0b58030a0553545505525051663e36665633581c1c5f46300e&code=3a12f660
