### ISSUE TITLE
Unexpected PRETRAIN_PATH in Base-bagtricks.yml

### ISSUE THREAD

**Issue by 0x4f5da2** [JDAI-CV/fast-reid#314]
https://github.com/JDAI-CV/fast-reid/blob/a5dac37beafc39fb47fe947ee3595eb0fe794794/configs/Base-bagtricks.yml#L12

**Comment by KRYSTALLJY** [comment]
You have to download the resnet50-19c8e357.pth and the change the path.

**Comment by 0x4f5da2** [comment]
> You have to download the resnet50-19c8e357.pth and the change the path.

Simply remove this line will solve the problem, the model will be automatically downloaded
