### ISSUE TITLE
Fail to run HPOReID

### ISSUE THREAD

**Issue by KrystalCWT** [JDAI-CV/fast-reid#315]
When I tried to run 
python3 projects/HPOReID/train_hpo.py --config-file projects/HPOReID/configs/baseline.yml --srch-algo "bohb"

errors occur： Do you know why?

2020-10-19 14:33:31,868     ERROR function_runner.py:233 -- Runner Thread raised error.
(pid=68853) Traceback (most recent call last):
(pid=68853)   File "/home//.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 227, in run
(pid=68853)     self._entrypoint()
(pid=68853)   File "/home//.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 290, in entrypoint
(pid=68853)     self._status_reporter.get_checkpoint())
(pid=68853)   File "/home//.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 499, in _trainable_func
(pid=68853)     output = train_func(config, checkpoint_dir=checkpoint_dir)
(pid=68853)   File "projects/HPOReID/train_hpo.py", line 132, in train_reid_tune
(pid=68853)     trainer.train()
(pid=68853)   File "fastreid/engine/defaults.py", line 365, in train
(pid=68853)     ), "No evaluation results obtained during training!"
(pid=68853) AssertionError: No evaluation results obtained during training!
(pid=68853) Exception in thread Thread-2:
(pid=68853) Traceback (most recent call last):
(pid=68853)   File "/home/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
(pid=68853)     self.run()
(pid=68853)   File "/home/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 246, in run
(pid=68853)     raise e
(pid=68853)   File "/home//.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 227, in run
(pid=68853)     self._entrypoint()
(pid=68853)   File "/home/ligck/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 290, in entrypoint
(pid=68853)     self._status_reporter.get_checkpoint())
(pid=68853)   File "/home//.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 499, in _trainable_func
(pid=68853)     output = train_func(config, checkpoint_dir=checkpoint_dir)
(pid=68853)   File "projects/HPOReID/train_hpo.py", line 132, in train_reid_tune
(pid=68853)     trainer.train()
(pid=68853)   File "/fastreid/engine/defaults.py", line 365, in train
(pid=68853)     ), "No evaluation results obtained during training!"
(pid=68853) AssertionError: No evaluation results obtained during training!
(pid=68853)
(pid=68853) ERROR [10/19 14:33:31 fastreid.engine.train_loop]: Exception during training:

**Comment by L1aoXingyu** [comment]
Before run hpo experiments, make sure that you can train reid models normally.

Could you load the train set and test set?

**Comment by gmt710** [comment]
@KRYSTALLJY There is no really wrong key message here. 
You may need to post what follows this line..((pid=68853) ERROR [10/19 14:33:31 fastreid.engine.train_loop]: Exception during training:)
