### ISSUE TITLE
error when change FEAT_DIM

### ISSUE THREAD

**Issue by KRYSTALLJY** [JDAI-CV/fast-reid#317]
I want to change FEAT_DIM from 2048 to 512.
but error occurs:

in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 2048 elements not 512

Do you know how to solve it?

**Comment by L1aoXingyu** [comment]
`FEAT_DIM` means the backbone output feature dimension.

If you want to reduction the embedding feature, you can modify `MODEL.HEADS.EMBEDDING_FEAT`.

**Comment by KRYSTALLJY** [comment]
> `FEAT_DIM` means the backbone output feature dimension.
> 
> If you want to reduction the embedding feature, you can modify `MODEL.HEADS.EMBEDDING_FEAT`.

Yes. I have already modified MODEL.HEADS.EMBEDDING_FEAT. but it shows 
![image](https://user-images.githubusercontent.com/18640795/96689991-b749af80-13b5-11eb-9e8c-b605672e2f4b.png)

**Comment by KRYSTALLJY** [comment]
> MODEL.HEADS.EMBEDDING_FEAT

![image](https://user-images.githubusercontent.com/18640795/96690304-15769280-13b6-11eb-8769-c0dec3dd29c6.png)
I change MODEL.BACKBONE.FEAT_DIM =512, and it turns out to be:
![image](https://user-images.githubusercontent.com/18640795/96690422-3f2fb980-13b6-11eb-8248-7d11e8cf2f7b.png)

**Comment by KRYSTALLJY** [comment]
I change _C.MODEL.HEADS.EMBEDDING_DIM = 512 , but it shows that
![Uploading image.png…]()

**Comment by KRYSTALLJY** [comment]
> `FEAT_DIM` means the backbone output feature dimension.
> 
> If you want to reduction the embedding feature, you can modify `MODEL.HEADS.EMBEDDING_FEAT`.

I change _C.MODEL.HEADS.EMBEDDING_DIM = 512 , but it shows that
![image](https://user-images.githubusercontent.com/18640795/96690964-ead90980-13b6-11eb-86f0-91a85aa8a2c0.png)

**Comment by KRYSTALLJY** [comment]
> `FEAT_DIM` means the backbone output feature dimension.
> 
> If you want to reduction the embedding feature, you can modify `MODEL.HEADS.EMBEDDING_FEAT`.

Solved it! Thanks!
