### ISSUE TITLE
MSMT17数据集

### ISSUE THREAD

**Issue by hhh5446** [JDAI-CV/fast-reid#319]
请问：1.MSMT17数据集在哪儿可以下呢？
           2.train_list.txt格式是什么样的呢？

**Comment by scuizhibin** [comment]
我也再找V2版本的数据

**Comment by L1aoXingyu** [comment]
msmt17 现在不能在公开的网上找到资源，需要自己想办法，train_list.txt 格式直接解压之后就有

**Comment by scuizhibin** [comment]
大佬，你有mgmt17v2的数据集合吗？&nbsp;有的话能分享一下吗？


---原始邮件---
发件人: &quot;Xingyu ***@***.***&gt;
发送时间: 2021年4月7日(周三) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JDAI-CV/fast-reid] MSMT17数据集 (#319)




 
msmt17 现在不能在公开的网上找到资源，需要自己想办法，train_list.txt 格式直接解压之后就有
 
&mdash;
