### ISSUE TITLE
模型准确率不对

### ISSUE THREAD

**Issue by aceyw** [JDAI-CV/fast-reid#322]
您好，我使用你们提供的模型（https://github.com/JDAI-CV/fast-reid/blob/master/docs/MODEL_ZOO.md）进行测试，

发现测试准确率和说的（https://github.com/JDAI-CV/fast-reid/blob/master/docs/MODEL_ZOO.md）不一样，每个模型都差别好几个点呢。

**Comment by L1aoXingyu** [comment]
因为模型版本已经修改过了，我们提供的模型是老版的code，你可以去 https://github.com/JDAI-CV/fast-reid/releases/tag/v0.1.1 下载代码，然后再测试。
