### ISSUE TITLE
How to add focal loss to baseline?

### ISSUE THREAD

**Issue by ShowTsai** [JDAI-CV/fast-reid#324]
There are only ```CrossEntropyLoss```, ```TripletLoss``` and ```CircleLoss``` in ```meta_arch/baseline.py```.
How to add ```FocalLoss``` here?
Thanks.

**Comment by AnhPC03** [comment]
```
        if "CrossEntropyLoss" in loss_names:
            loss_dict['loss_cls'] = cross_entropy_loss(
                cls_outputs,
                gt_labels,
                self._cfg.MODEL.LOSSES.CE.EPSILON,
                self._cfg.MODEL.LOSSES.CE.ALPHA,
            ) * self._cfg.MODEL.LOSSES.CE.SCALE

        if "TripletLoss" in loss_names:
            loss_dict['loss_triplet'] = triplet_loss(
                pred_features,
                gt_labels,
                self._cfg.MODEL.LOSSES.TRI.MARGIN,
                self._cfg.MODEL.LOSSES.TRI.NORM_FEAT,
                self._cfg.MODEL.LOSSES.TRI.HARD_MINING,
            ) * self._cfg.MODEL.LOSSES.TRI.SCALE

        if "CircleLoss" in loss_names:
            loss_dict['loss_circle'] = circle_loss(
                pred_features,
                gt_labels,
                self._cfg.MODEL.LOSSES.CIRCLE.MARGIN,
                self._cfg.MODEL.LOSSES.CIRCLE.ALPHA,
            ) * self._cfg.MODEL.LOSSES.CIRCLE.SCALE

        if "FocalLoss" in loss_names:
            loss_dict['loss_focal'] = focal_loss(
                pred_features,
                gt_labels,
                self._cfg.MODEL.LOSSES.FC.ALPHA,
                self._cfg.MODEL.LOSSES.FC.GAMMA,
            ) * self._cfg.MODEL.LOSSES.FC.SCALE

        return loss_dict
```
I used this and worked. Maybe this changed will help you

**Comment by ShowTsai** [comment]
Thanks!
But ```FC``` should be ```FL```

**Comment by AnhPC03** [comment]
> Thanks!
> But `FC` should be `FL`.

Yess, my mistake :)

**Comment by howieraem** [comment]
> ```
>         if "CrossEntropyLoss" in loss_names:
>             loss_dict['loss_cls'] = cross_entropy_loss(
>                 cls_outputs,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.CE.EPSILON,
>                 self._cfg.MODEL.LOSSES.CE.ALPHA,
>             ) * self._cfg.MODEL.LOSSES.CE.SCALE
> 
>         if "TripletLoss" in loss_names:
>             loss_dict['loss_triplet'] = triplet_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.TRI.MARGIN,
>                 self._cfg.MODEL.LOSSES.TRI.NORM_FEAT,
>                 self._cfg.MODEL.LOSSES.TRI.HARD_MINING,
>             ) * self._cfg.MODEL.LOSSES.TRI.SCALE
> 
>         if "CircleLoss" in loss_names:
>             loss_dict['loss_circle'] = circle_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.CIRCLE.MARGIN,
>                 self._cfg.MODEL.LOSSES.CIRCLE.ALPHA,
>             ) * self._cfg.MODEL.LOSSES.CIRCLE.SCALE
> 
>         if "FocalLoss" in loss_names:
>             loss_dict['loss_focal'] = focal_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.FL.ALPHA,
>                 self._cfg.MODEL.LOSSES.FL.GAMMA,
>             ) * self._cfg.MODEL.LOSSES.FL.SCALE
> 
>         return loss_dict
> ```
> 
> I used this and worked. Maybe this changed will help you



> ```
>         if "CrossEntropyLoss" in loss_names:
>             loss_dict['loss_cls'] = cross_entropy_loss(
>                 cls_outputs,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.CE.EPSILON,
>                 self._cfg.MODEL.LOSSES.CE.ALPHA,
>             ) * self._cfg.MODEL.LOSSES.CE.SCALE
> 
>         if "TripletLoss" in loss_names:
>             loss_dict['loss_triplet'] = triplet_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.TRI.MARGIN,
>                 self._cfg.MODEL.LOSSES.TRI.NORM_FEAT,
>                 self._cfg.MODEL.LOSSES.TRI.HARD_MINING,
>             ) * self._cfg.MODEL.LOSSES.TRI.SCALE
> 
>         if "CircleLoss" in loss_names:
>             loss_dict['loss_circle'] = circle_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.CIRCLE.MARGIN,
>                 self._cfg.MODEL.LOSSES.CIRCLE.ALPHA,
>             ) * self._cfg.MODEL.LOSSES.CIRCLE.SCALE
> 
>         if "FocalLoss" in loss_names:
>             loss_dict['loss_focal'] = focal_loss(
>                 pred_features,
>                 gt_labels,
>                 self._cfg.MODEL.LOSSES.FL.ALPHA,
>                 self._cfg.MODEL.LOSSES.FL.GAMMA,
>             ) * self._cfg.MODEL.LOSSES.FL.SCALE
> 
>         return loss_dict
> ```
> 
> I used this and worked. Maybe this changed will help you

Thanks for your suggestion. I wonder if focal loss will perform any better than cross entropy loss? Is it required to tune alpha and gamma?

**Comment by AnhPC03** [comment]
@howieraem I has tried focal loss and the result was worse than (cross entropy loss + triplet loss) as in default. But you should try tune alpha and gammar for use focal loss with other loss for experiment better result.
