### ISSUE TITLE
SBS(R101-ibn)模型训练，日志显示最高rank1 73.19%,如何达到论文中所说的84%

### ISSUE THREAD

**Issue by spy78111** [JDAI-CV/fast-reid#327]
训练日志如下: 日志显示最高rank1 73.19%,如何达到论文中所说的84%
[32m[10/30 22:04:04 fastreid.utils.events]: [0m eta: 10:52:59  iter: 54799  total_loss: 5.938  loss_cls: 5.41  loss_triplet: 0.5259  time: 0.4892  data_time: 0.0007  lr: 2.54e-04  max_mem: 7729M
[32m[10/30 22:05:49 fastreid.utils.events]: [0m eta: 10:51:45  iter: 54999  total_loss: 5.908  loss_cls: 5.292  loss_triplet: 0.5132  time: 0.4893  data_time: 0.0005  lr: 2.54e-04  max_mem: 7729M
[32m[10/30 22:07:33 fastreid.utils.events]: [0m eta: 10:50:31  iter: 55199  total_loss: 6.98  loss_cls: 6.402  loss_triplet: 0.5537  time: 0.4893  data_time: 0.0006  lr: 2.53e-04  max_mem: 7729M
[32m[10/30 22:09:17 fastreid.utils.events]: [0m eta: 10:48:53  iter: 55399  total_loss: 6.588  loss_cls: 5.942  loss_triplet: 0.5643  time: 0.4894  data_time: 0.0003  lr: 2.52e-04  max_mem: 7729M
[32m[10/30 22:11:01 fastreid.utils.events]: [0m eta: 10:47:12  iter: 55599  total_loss: 6.737  loss_cls: 6.191  loss_triplet: 0.5395  time: 0.4894  data_time: 0.0005  lr: 2.51e-04  max_mem: 7729M
[32m[10/30 22:12:43 fastreid.utils.events]: [0m eta: 10:44:55  iter: 55799  total_loss: 6.577  loss_cls: 6.062  loss_triplet: 0.59  time: 0.4894  data_time: 0.0008  lr: 2.50e-04  max_mem: 7729M
[32m[10/30 22:14:25 fastreid.utils.events]: [0m eta: 10:42:38  iter: 55999  total_loss: 6.254  loss_cls: 5.714  loss_triplet: 0.4743  time: 0.4894  data_time: 0.0005  lr: 2.50e-04  max_mem: 7729M
[32m[10/30 22:16:10 fastreid.utils.events]: [0m eta: 10:41:07  iter: 56199  total_loss: 6.737  loss_cls: 6.166  loss_triplet: 0.5172  time: 0.4894  data_time: 0.0008  lr: 2.49e-04  max_mem: 7729M
[32m[10/30 22:17:52 fastreid.utils.events]: [0m eta: 10:38:21  iter: 56399  total_loss: 6.587  loss_cls: 6.052  loss_triplet: 0.5474  time: 0.4894  data_time: 0.0004  lr: 2.48e-04  max_mem: 7729M
[32m[10/30 22:19:36 fastreid.utils.events]: [0m eta: 10:36:39  iter: 56599  total_loss: 6.076  loss_cls: 5.548  loss_triplet: 0.5173  time: 0.4895  data_time: 0.0007  lr: 2.47e-04  max_mem: 7729M
[32m[10/30 22:21:19 fastreid.utils.events]: [0m eta: 10:35:44  iter: 56799  total_loss: 5.825  loss_cls: 5.319  loss_triplet: 0.5058  time: 0.4895  data_time: 0.0005  lr: 2.46e-04  max_mem: 7729M
[32m[10/30 22:23:02 fastreid.utils.checkpoint]: [0mSaving checkpoint to logs/msmt17/sbs_R101-ibn/model_0056999.pth
[32m[10/30 22:23:04 fastreid.engine.defaults]: [0mPrepare testing set
[32m[10/30 22:23:04 fastreid.data.datasets.bases]: [0m=> Loaded MSMT17 in csv format: 
[36m| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 3060    | 11659      | 15          |
| gallery  | 3060    | 82161      | 15          |[0m
[32m[10/30 22:23:04 fastreid.evaluation.evaluator]: [0mStart inference on 93820 images
[32m[10/30 22:23:06 fastreid.evaluation.evaluator]: [0mInference done 11/733. 0.0302 s / batch. ETA=0:02:19
[32m[10/30 22:23:37 fastreid.evaluation.evaluator]: [0mInference done 125/733. 0.0358 s / batch. ETA=0:02:39
[32m[10/30 22:24:07 fastreid.evaluation.evaluator]: [0mInference done 238/733. 0.0360 s / batch. ETA=0:02:10
[32m[10/30 22:24:37 fastreid.evaluation.evaluator]: [0mInference done 349/733. 0.0361 s / batch. ETA=0:01:42
[32m[10/30 22:25:07 fastreid.evaluation.evaluator]: [0mInference done 469/733. 0.0362 s / batch. ETA=0:01:09
[32m[10/30 22:25:37 fastreid.evaluation.evaluator]: [0mInference done 590/733. 0.0362 s / batch. ETA=0:00:37
[32m[10/30 22:26:07 fastreid.evaluation.evaluator]: [0mInference done 705/733. 0.0362 s / batch. ETA=0:00:07
[32m[10/30 22:26:15 fastreid.evaluation.evaluator]: [0mTotal inference time: 0:03:09.994933 (0.260982 s / batch per device)
[32m[10/30 22:26:15 fastreid.evaluation.evaluator]: [0mTotal inference pure compute time: 0:00:26 (0.036299 s / batch per device)
[32m[10/30 22:31:41 fastreid.evaluation.testing]: [0mEvaluation results in csv format: 
[36m| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   |
|:-----------|:---------|:---------|:----------|:-------|:-------|
| MSMT17     | 73.19%   | 84.54%   | 88.04%    | 44.58% | 6.04%  |[0m

**Comment by spy78111** [comment]
是否还需要预处理，后处理，例如行人对齐，重排等操作

**Comment by L1aoXingyu** [comment]
@spy78111 请提供一下你的训练配置，比如用了几个 gpu 等信息

**Comment by spy78111** [comment]
我用了四个GPU,配置是默认的，网络用的是sbs_R50

**Comment by spy78111** [comment]
另外数据的配置是 list_train.txt 对应bounding_box_train图片，list_gallery.txt对应bounding_box_test图片库，list_query.txt对应query图片库，是这样配置吗，有没有特别的要求？

**Comment by L1aoXingyu** [comment]
@spy78111 建议你先用单卡跑一下，数据的配置就是代码里面写的那样，不需要特殊的要求
