### ISSUE TITLE
在用baseline训练时，triplet loss 有一段先上升又下降的过程，如何解释这个现象，谢谢！（训练曲线如下）

### ISSUE THREAD

**Issue by chongyangwang-song** [JDAI-CV/fast-reid#328]
![QQ截图20201102202251](https://user-images.githubusercontent.com/52644922/97867777-72286480-1d49-11eb-978a-e8ca35651659.png)

**Comment by L1aoXingyu** [comment]
@chongyangwang-song 你用的是 bot 还是 sbs 呢？

**Comment by chongyangwang-song** [comment]
@L1aoXingyu  我用的是bot

**Comment by chongyangwang-song** [comment]
@L1aoXingyu 我自己在三元组和交叉熵损失之外又构建了并加入了另一种损失。结果训练过程中三元组损失收敛很快，一直在下降，而且在80轮左右就将为0了。最后结果反而更差，我一直在想为什么bot训练的三元组损失会有先上升又下降的过程。

**Comment by L1aoXingyu** [comment]
我觉得是 id loss 和 metric loss 中间存在打架的问题。
