### ISSUE TITLE
怎么加载之前的权重继续训练呀？

### ISSUE THREAD

**Issue by bixiaopeng0** [JDAI-CV/fast-reid#331]
我把预训练模型替换成model_final.pth会报错的，怎么在之前的模型继续训练一下呀？

**Comment by L1aoXingyu** [comment]
如果是训练中断，想要继续训练，直接在训练命令后面加上 `--resume` 就可以了。

如果是希望 load 一个 train 好的模型，在另外一个数据集上 finetune，可以参考这个 issue
https://github.com/JDAI-CV/fast-reid/issues/325
