### ISSUE TITLE
How to get CUHK-SYSU for person ReID

### ISSUE THREAD

**Issue by HeliosZhao** [JDAI-CV/fast-reid#332]
Thanks for sharing!~

 Well, you include CUHK-SYSU in your datasets.  But I get this dataset from http://www.ee.cuhk.edu.hk/~xgwang/PS/dataset.html, which does not contain ID information.

So how to get the dataset you use?

**Comment by L1aoXingyu** [comment]
You can crop the person and get the id information from the label files.
