### ISSUE TITLE
人体编码？

### ISSUE THREAD

**Issue by lfxx** [JDAI-CV/fast-reid#335]
您好，人脸识别现在可以通过对脸部编码输出128位特征向量计算出相似度，效果挺好的．想知道人体重识别可以做到这种程度吗，参考项目：https://github.com/ageitgey/face_recognition

**Comment by L1aoXingyu** [comment]
因为人脸输入比较小，同时人脸是一个刚体，所以可以把维度压缩到比较低，对于 reid 来说，也可以进行降维，但是在 id 规模比较小的时候掉点会很明显，当 id 规模到10w+，一般我们会降维到 512.
