### ISSUE TITLE
 pair-wise circle loss

### ISSUE THREAD

**Issue by bixiaopeng0** [JDAI-CV/fast-reid#336]
大佬，你实验过pair-wise形式的circle loss吗，loss能收敛到多少呀？
我用在reid上，发现不收敛呀，用的默认参数。

**Comment by L1aoXingyu** [comment]
我之前实验 pair-wise cirlce loss 也特别大，可能 loss 的实现形式有问题，等官方 release code 吧

**Comment by L1aoXingyu** [comment]
我实现了一版新的 code，估计下周 release。

**Comment by bixiaopeng0** [comment]
厉害了👍




| |
毕晓鹏
|
|
邮箱：bixiaopeng1996@163.com
|

签名由 网易邮箱大师 定制

On 12/16/2020 23:19, Xingyu Liao wrote:

我实现了一版新的 code，估计下周 release。

**Comment by L1aoXingyu** [comment]
已经更新了
