### ISSUE TITLE
显存占用超高疑问？

### ISSUE THREAD

**Issue by yukaizhou** [JDAI-CV/fast-reid#337]
V100,32G。使用resnet50-ibn-a，batch-size为32，跑起来用了26G，这个是不是太不合理了？请问可能的原因有哪些？期待您的回复！

**Comment by L1aoXingyu** [comment]
请按照 issue 要求提供你的训练配置和 command line

**Comment by yukaizhou** [comment]
训练配置：
MODEL:
  META_ARCHITECTURE: "Baseline"
  FREEZE_LAYERS: ["backbone"]

  BACKBONE:
    NAME: "build_resnet_backbone"

    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    WITH_NL: False
    PRETRAIN: True
    PRETRAIN_PATH: ""


  HEADS:
    NAME: "EmbeddingHead"
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "gempool"
    NECK_FEAT: "before"
    CLS_LAYER: "arcSoftmax" # circleSoftmax, arcSoftmax, linear
    SCALE: 30
    MARGIN: 0.4


  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3   # 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 2.


DATASETS:
  NAMES: ("Market501",)
  TESTS: ("Market501",)

INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]
  DO_AUTOAUG: False
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32


  SCHED: "WarmupMultiStepLR"   # "WarmupCosineAnnealingLR"
  STEPS: [40, 90]
  GAMMA: 0.1
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 10000
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True


OUTPUT_DIR: "./logs/TRAIN/sbs_R50-ibn"


命令行为：CUDA_VISIBLE_DEVICES=1 python tools/train_net.py

**Comment by L1aoXingyu** [comment]
看你的配置文件是正常的，是不是你在跑别的程序占用了显存

**Comment by yukaizhou** [comment]
谢谢楼主的回复！已经排查到问题了，是自己的问题。再次感谢！还想问下，当指定非 0 卡训练时，会自动开启一个线程在0卡 ，请问这个是为什么？ 期待您的回复!!

**Comment by yanty123** [comment]
> 谢谢楼主的回复！已经排查到问题了，是自己的问题。再次感谢！还想问下，当指定非 0 卡训练时，会自动开启一个线程在0卡 ，请问这个是为什么？ 期待您的回复!!

您好 请问您那边是什么问题呢，我在训练的时候也遇到了显存占用超高导致batch size开不大的情况。

**Comment by lee3397** [comment]
在单张2080ti上推理一张256*128的图片显存占用快6个G了，这正常吗？
