### ISSUE TITLE
visualize_result.py problem

### ISSUE THREAD

**Issue by chernbo** [JDAI-CV/fast-reid#340]
## Instructions To Reproduce the 🐛 Bug:

I did not add additional code

firstly I run  this code CUDA_VISIBLE_DEVICES=1 python ./tools/train_net.py --config-file configs/Market1501/bagtricks_R50.yml  for training and  testing'
than I run this code   CUDA_VISIBLE_DEVICES=1  python demo/visualize_result.py --config-file logs/market1501/bagtricks_R50/config.yaml \
--parallel --vis-label --dataset-name 'Market1501' --output logs/market1501/bagtricks_R50 \
--opts MODEL.WEIGHTS logs/market1501/bagtricks_R50/model_final.pth for visualizing_reuslt.py
but it said that AttributeError: 'Tensor' object has no attribute 'flags'.
![image](https://user-images.githubusercontent.com/47548611/99179322-58c6e580-2757-11eb-9629-1dfee3b0d0ff.png)

**Comment by sunxia233** [comment]
Hi, I also encountered this problem, did you solve this problem?

**Comment by chernbo** [comment]
Not resolved yet. Some model can be successful such as BoT, but others model will say this problem.

**Comment by gmt710** [comment]
fast-reid-master\fastreid\evaluation\reid_evaluation.py
···
query_features = query_features.numpy()
gallery_features = gallery_features.numpy()
···
maybe this is needed.

**Comment by chernbo** [comment]
@gmt710  I don't know what you mean, can you tell me in more detail

**Comment by gmt710** [comment]
add the line before evaluate_rank

**Comment by chernbo** [comment]
@gmt710 Thanks for your suggesstion ,I check reid_evalution.py ,but it have this line of code.
![image](https://user-images.githubusercontent.com/47548611/100316072-c0512080-2ff4-11eb-8aa4-bcc7fb3ced6f.png)

**Comment by sunxia233** [comment]
I commented out line 114
#index.add(g_feats)
in rank.py and set use_distmat=True is worked

**Comment by chernbo** [comment]
@sunxia233  Thank you very much for your valuable suggestions!  It works！
