### ISSUE TITLE
别的开源代码里面多卡训练为啥没看到NORM方式用"syncBN"

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#344]
之前作者说这是为了多卡训练，所以要把BN改成syncBN。但是我比较好奇，为啥别的一些开源代码没有涉及到这么改呢？别的开源在多卡训练的时候把BN改成syncBN也会有效吗

**Comment by L1aoXingyu** [comment]
多卡训练中，syncBN 一般用在单卡里面图片比较少的情况，比如 two stage detection 和 segmentation，在 reid 里面不用 syncBN 效果不会怎么受影响。
