### ISSUE TITLE
when use train-net.py,it takes error. 

### ISSUE THREAD

**Issue by boy-new-2019** [JDAI-CV/fast-reid#347]
I utilize the dataset VERI-WILD,it takes error:keyerror:119082.jpg 0 23
that's why?

**Comment by starcream** [comment]
same problem.except that mine is 119083.jpg。 Have you solved this?

**Comment by terrynx** [comment]
same problem， Have you solved this?

**Comment by JinkaiZheng** [comment]
> I utilize the dataset VERI-WILD,it takes error:keyerror:119082.jpg 0 23
> that's why?

Hi~ Maybe you can try my TXT files. [VERI-Wild_train_test_split](https://pan.baidu.com/s/1kWr043EGoTBmLZKoa4GyAw) (Code: 2333)

Best wishes!
