### ISSUE TITLE
请问为什么你这里的batch设置的4ID*16imgs（batch=64），却能得到不错的结果

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#350]
别的开源代码的batch一般设置的是16个ID*每个ID4张图片，而你这里恰恰相反是4个ID*每个ID16张图片。别的开源代码如果像你这么设置效果会比较差，但为什么你这么设置就可以呢？

**Comment by garyliu0816** [comment]
instance_num指的是ID的数量吧
每个ID的图片数量 = batch_size / instance_num

**Comment by L1aoXingyu** [comment]
这主要是由于使用 id circle loss 的原因，必须要把 batch 里面的 id 变小一点，这样设置主要是因为公开数据集的问题，在大规模数据集上可以将 id 设置大一些。

**Comment by faedtodd** [comment]
> instance_num指的是ID的数量吧
> 每个ID的图片数量 = batch_size / instance_num

self.num_pids_per_batch = batch_size // self.num_instances
------fastreid/data/samplers/triplet_sampler.py

**Comment by L1aoXingyu** [comment]
最后回复一下这个问题，因为公开数据集规模比较小，所以通过调参发现 batch64 里面采4个id，每个 id 采16张图效果比较好，但是在我的私库以及大规模的公开数据集上验证，发现 batch64 里面采 16 个 id，每个 id 采 4 张图效果会更好。所以说小规模数据集的结论不太靠谱，更多的需要在大规模数据集上进行验证。
