### ISSUE TITLE
Official wechat group（PS: the author here.）

### ISSUE THREAD

**Issue by gmt710** [JDAI-CV/fast-reid#354]
Welcome to join the fast-reid official communication group.
If you have any questions, you can communicate with the author or a group of people who are using fast-reid. ***The number of people in the group is more than 200, please leave a message to add the group.***
PS: the author here.

![46cee8c1-c14f-4a08-8adc-ef08008d6398](https://user-images.githubusercontent.com/34018741/131303664-42adb5d2-2c54-40eb-adf0-91e5f1a44416.jpg)

*If the QR code fails, please leave me a message.*

**Comment by 404289680** [comment]
能拉我进去吗，看不到二维码了

**Comment by gmt710** [comment]
@404289680 ,I've updated it.

**Comment by terrynx** [comment]
二维码已过期，能更新一下么

**Comment by gmt710** [comment]
@terrynx , 已更新。

**Comment by TimVerion** [comment]
二维码已过期，能更新一下么

**Comment by gmt710** [comment]
@TimVerion ，你看下下面的日期，再试试？

**Comment by TimVerion** [comment]
抱歉，可能是我这里网络的问题加载不出来二维码

**Comment by gmt710** [comment]
@TimVerion ,github图片不显示问题，[可以参考此处](https://blog.csdn.net/qq_38232598/article/details/91346392).

**Comment by TimVerion** [comment]
> @TimVerion ,github图片不显示问题，[可以参考此处](https://blog.csdn.net/qq_38232598/article/details/91346392)或者[我csdn上更新的二维码](https://blog.csdn.net/qq_35975447/article/details/110140006)。

非常感激，现在显示正常，已入群。

**Comment by X-funbean** [comment]
过期了，请问可以更新一下吗，谢谢

**Comment by gmt710** [comment]
@X-funbean 好了。

**Comment by JiangZongKang** [comment]
Upadate

> Welcome to join the fast-reid official communication group.
> If you have any questions, you can communicate with the author or a group of people who are using fast-reid.
> PS: the author here.
> 
![微信图片_20210301104719](https://user-images.githubusercontent.com/22634440/109446029-d949f180-7a7b-11eb-8813-26e424008983.png)
61aa09dff5a8.png)
> 
> _If the QR code fails, please leave me a message._

**Comment by HaoWangDL** [comment]
可以更新下二维码么？

**Comment by HaoWangDL** [comment]
@gmt710 您好，可以更新下二维码吗？我在使用onnx_inferencet做前向推理时，采用余弦相似度，输出的相似度值几乎一致，寻求帮助！

**Comment by L1aoXingyu** [comment]
updated！

**Comment by oceanlvr** [comment]
plz update QRCODE :) THANKS

**Comment by L1aoXingyu** [comment]
Try it again.

**Comment by aixiaoq** [comment]
过期了，请问可以更新一下吗，谢谢

**Comment by YP-Liu** [comment]
同楼上，请问可以更新下吗？谢谢。

**Comment by gmt710** [comment]
群人数已经超过200人了，不能通过分享群二维码的形式拉人了，正在想办法，耐心等待~

**Comment by L1aoXingyu** [comment]
今晚回去弄，稍等

**Comment by gmt710** [comment]
@aixiaoq @YP-Liu 作者在首页ReadME中放了一个微信二维码，通过加这个微信，会定时拉人进群。如果需要可以加一下。

**Comment by bmxbmx3** [comment]
我扫码了，但是该微信号没人回复

**Comment by zqs1996** [comment]
> > @TimVerion ,github图片不显示问题，[可以参考此处](https://blog.csdn.net/qq_38232598/article/details/91346392)或者[我csdn上更新的二维码](https://blog.csdn.net/qq_35975447/article/details/110140006)。
> 
> 非常感激，现在显示正常，已入群。

你好，能拉进群一下吗？添加的微信没人回复
