### ISSUE TITLE
请问在market上训练最高准确率的配置该怎么写

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#356]
## ❓ How to do something using fastreid

目前在market上训练最高准确率的配置文件是哪一个呢

NOTE:
我用了下面这个配置发现top1只有93

MODEL:
  META_ARCHITECTURE: "Baseline"

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "syncBN" # syncBN
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/guanyonglai/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "EmbeddingHead"
    NORM: "syncBN" # syncBN
    WITH_BNNECK: True
    POOL_LAYER: "avgpool"
    NECK_FEAT: "after" 
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 96 # orig=64

  SCHED: "WarmupMultiStepLR"
  STEPS: [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 60

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True

**Comment by L1aoXingyu** [comment]
应该是 sbs 里面 r101-ibn 是最高的配置，不过在 market 上过拟合并没有什么意义。
