### ISSUE TITLE
请问如果增加batch应该增加ID还是图片数

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#359]
我用mgn_R50-ibn.yml训练的，原配置的batch是64=4ID*16imgs，我把batch改成96，不管是4ID*24imgs还是24ID*4imgs，发现效果都不如原配置。请问增加batch训练应该怎么增加呢

**Comment by L1aoXingyu** [comment]
增加 batch 一般是增加 id，比如 batch64 是 4个id，每个 id 16 张图，如果跑 batch128，那么是 8 个ID，保证每个 id 的图片张数不变。
