### ISSUE TITLE
Is there a sample script on how to do basic pytorch inference?

### ISSUE THREAD

**Issue by joaqo** [JDAI-CV/fast-reid#361]
I see there are some samples for how to run inference for onnx and tensorrt but I haven't found one for pytorch, the closest thing I've seen is the eval script.

I was just looking for simple way to load my model.pth file from disk, load it into a pytorch model, run some images through the it, get their embeddings, and compare their distances.

Is this somewhere in the doc I am missing?

Thanks for the awesome project by the way!

**Comment by L1aoXingyu** [comment]
check `demo/demo.py`

**Comment by joaqo** [comment]
Thanks!
