### ISSUE TITLE
How to split VehicleID test dataset 800/1600/2400？

### ISSUE THREAD

**Issue by DongfeiJi** [JDAI-CV/fast-reid#362]
Hi~
I wonder how to split VehicleID test dataset 800/1600/2400？

**Comment by lxc86739795** [comment]
> Hi~
> I wonder how to split VehicleID test dataset 800/1600/2400？

Hi,
The testing set of VehicleID has been officially divided into three subsets with 800/1600/2400 IDs. The splitting files can be found in the package of the dataset.
During testing, for each of the 800/1600/2400 IDs, one image is sampled as a gallery image to obtain a gallery set with 800/1600/2400 images which rest images are used as query images.

Hope can help you.
