### ISSUE TITLE
changing '"resize" from PIL to cv2, results drops from 85 to 65 in MSMT17 datasets. 

### ISSUE THREAD

**Issue by yian2271368** [JDAI-CV/fast-reid#363]
hi, I used PIL(the original code) to train the msmt17 v2 datasets, and if use PIL in the test code, it can get 85 rank-1, but if i use cv2's resize(same interpolation), the results drops to 65. Of course, all other settings remains the same.(includes RBB,BGR, or channels axes). I can not figure out why changing resize package changes the results such a lot. Is that the model robustness issue?

**Comment by gmt710** [comment]
Do you use the same input ?
All use (img-mean)/ std ?

**Comment by yian2271368** [comment]
@gmt710 yes, the input is all the same. But you know, after resizing, there are some differences in pixel numbers, but i think that should not cause such a huge differences.

**Comment by gmt710** [comment]
Maybe somewhere is different. you can check it.
I've ever changed PIL to cv2 when I test. It doesn't have huge differences.

**Comment by yian2271368** [comment]
did you change PIL to CV2 in this code? I did change this in my previous project, and it did not make huge differences, but in this one, it did .

**Comment by gmt710** [comment]
Yes, you can compare the output of each step.

**Comment by yian2271368** [comment]
ok, actually i did compare, but i did not get where is wrong. The only thing i change is in data/transforms/common.py, where the model load the image. But anyway, I will keep checking.

**Comment by L1aoXingyu** [comment]
Why did you input the network BRG images?

**Comment by yian2271368** [comment]
thanks!
