### ISSUE TITLE
请问怎么样才能支持CPU训练呢？

### ISSUE THREAD

**Issue by rawli** [JDAI-CV/fast-reid#366]
## ❓ 请问怎么样才能支持CPU训练呢？
我用CPU训练报了如下错误，请问fastreid支不支持CPU训练呢？如果支持的话需要怎么做？

D:\pycharm-workspace\fast-reid>python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cpu"
Traceback (most recent call last):
  File "./tools/train_net.py", line 13, in <module>
    from fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch
  File ".\fastreid\engine\__init__.py", line 6, in <module>
    from .train_loop import *
  File ".\fastreid\engine\train_loop.py", line 14, in <module>
    from apex import amp
  File "D:\python\Lib\site-packages\apex\__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "D:\python\Lib\site-packages\apex\interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "D:\python\Lib\site-packages\apex\interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "D:\python\Lib\site-packages\zope\interface\declarations.py", line 706, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

**Comment by L1aoXingyu** [comment]
你的 python 版本是什么？

**Comment by rawli** [comment]
> 你的 python 版本是什么？

3.8.6

**Comment by chenbinghui1** [comment]
@rawli 我用gpu的时候也是这个错误 请问您解决了吗

**Comment by rawli** [comment]
> @rawli 我用gpu的时候也是这个错误 请问您解决了吗
没有，最近没在搞这个。

**Comment by chenbinghui1** [comment]
@rawli 哦 刚解决了 要用源码装apex 先把之前的卸载了 如下
pip3 uninstall apex && git clone https://www.github.com/nvidia/apex && cd apex && python3 setup.py install && rm -rf ../apex

**Comment by rawli** [comment]
> @rawli 哦 刚解决了 要用源码装apex 先把之前的卸载了 如下
> pip3 uninstall apex && git clone https://www.github.com/nvidia/apex && cd apex && python3 setup.py install && rm -rf ../apex

你是有GPU吧？我用这种方法试过了，CPU下没用。我现在没有GPU，等GPU到了之后再试。

**Comment by gmt710** [comment]
@chenbinghui1 @rawli ,  可以参考这里面的环境
 https://blog.csdn.net/qq_35975447/article/details/106664593
 https://blog.csdn.net/qq_35975447/article/details/106714173

**Comment by rawli** [comment]
> @chenbinghui1 @rawli , 可以参考这里面的环境
> https://blog.csdn.net/qq_35975447/article/details/106664593
> https://blog.csdn.net/qq_35975447/article/details/106714173

我看一下，谢谢！
