### ISSUE TITLE
随机种子设置无效

### ISSUE THREAD

**Issue by xn1997** [JDAI-CV/fast-reid#368]
我在
https://github.com/JDAI-CV/fast-reid/blob/0428a270e3f59f5190e30f9a01b434500047e5d4/fastreid/data/build.py#L45
https://github.com/JDAI-CV/fast-reid/blob/0428a270e3f59f5190e30f9a01b434500047e5d4/fastreid/data/build.py#L47
https://github.com/JDAI-CV/fast-reid/blob/0428a270e3f59f5190e30f9a01b434500047e5d4/fastreid/data/build.py#L49
https://github.com/JDAI-CV/fast-reid/blob/0428a270e3f59f5190e30f9a01b434500047e5d4/fastreid/engine/defaults.py#L120
这四处函数中传入了同一个随机种子
但是我训练时，发现每次训练的loss变化并不相同，感觉随机种子并没有生效。
请问是我的设置哪里有问题吗？
非常感谢。

**Comment by L1aoXingyu** [comment]
除了 sampler 之外，数据增强里面也有随机性，网络初始化里面也有随机性。

**Comment by xn1997** [comment]
> 除了 sampler 之外，数据增强里面也有随机性，网络初始化里面也有随机性。

谢谢，问题已经解决了。

**Comment by xn1997** [comment]
解决方案写在了这里https://github.com/xn1997/pytorch-grad-cam/issues/1#issuecomment-777257144
