### ISSUE TITLE
关于cuhk03-np数据集的训练

### ISSUE THREAD

**Issue by soulredeem** [JDAI-CV/fast-reid#370]
按照cuhk03-np的数据组织方式，即与market1501类似地将数据集分为train、query和gallery，训练了10w次以上的迭代，采用market1501的方式进行评测，得到的最高的mAP为29.55%、Rank-1为25.36%，由于在目前公布的评测结果中没有关于cuhk03的结果，在此请教下您，这个结果(mAP和Rank-1都比较低，并且mAP高于Rank-1）是否正常，在这个数据集上做评测是不是不能用market1501的方式做评测，如果可以用这个方式的话是否需要在数据集组织上做一些特定的调整？

**Comment by L1aoXingyu** [comment]
sorry for the late reply.
cuhk 需要使用另外一个 evaluation metrics
https://github.com/JDAI-CV/fast-reid/blob/254a489eb1b5267fdc6a4c25a6e2e7f0872ed6e9/fastreid/evaluation/rank.py#L178
这里设为 `True`

**Comment by soulredeem** [comment]
> sorry for the late reply.
> cuhk 需要使用另外一个 evaluation metrics
> https://github.com/JDAI-CV/fast-reid/blob/254a489eb1b5267fdc6a4c25a6e2e7f0872ed6e9/fastreid/evaluation/rank.py#L178
> 
> 
> 这里设为 `True`

设置为True后，调用的函数eval_cuhk03返回参数为<all_cmc, mAP>，与评估函数所要获取的参数<cmc, all_AP, all_INP>不一致，需要在调用函数中补充下INP的返回值，具体如下：
评估函数入口：
https://github.com/JDAI-CV/fast-reid/blob/96fd58c48fd29d7026a212361f32586d27075093/fastreid/evaluation/reid_evaluation.py#L100
实际调用函数：
https://github.com/JDAI-CV/fast-reid/blob/96fd58c48fd29d7026a212361f32586d27075093/fastreid/evaluation/rank.py#L96

暂且将INP参数以空值返回使得程序正常运行后进行测试，得到的mAP仍为29.55%，Rank1略有提升，为29.94%，可见使用该评估方式得到的结果相较之前的结果并没有明显改善，您是否有做过这个数据集的对比实验，我的这个结果是否正常，是否本框架在cuhk03-np这个数据集上无法取到比较好的结果
