### ISSUE TITLE
内存占用挺大的，当有千万量级的图片的时候300多g内存都撑爆了，请问

### ISSUE THREAD

**Issue by 404289680** [JDAI-CV/fast-reid#374]
内存占用大是图片都加载到内存了吗。。

**Comment by L1aoXingyu** [comment]
Actually, the images will not be loaded into the RAM.

When the image scale reaches tens of millions, maybe it will need more RAM. Maybe this is pytorch dataloader's problem, you can refer to this issue
https://github.com/pytorch/pytorch/issues/13246

**Comment by 404289680** [comment]
感谢，我看看怎么解决

**Comment by raymondchu-z** [comment]
![image-20210111151706664](https://gitee.com/Raymond-Z/typora/raw/master/image/20210111151708.png)
同样遇到内存占用大的问题，250G都占用完了。
我是在运行visualize_result.py时发生错误的，数据量如下
![image-20210111152549949](https://gitee.com/Raymond-Z/typora/raw/master/image/20210111152551.png)

**Comment by L1aoXingyu** [comment]
这个应该是 evaluation 的时候出现的 out of memory，I am working on it.
