### ISSUE TITLE
pairwise_cosface

### ISSUE THREAD

**Issue by 404289680** [JDAI-CV/fast-reid#378]
请问pairwise_cosface是替代CrossEntropyLoss 还是替代TripletLoss

**Comment by 404289680** [comment]
我用最新的代码训练，TripletLoss非常小接近0，1e-5左右，请问这是正常的吗，老板会收敛到零点几

**Comment by L1aoXingyu** [comment]
pairwise 是 metric loss，用来替代 triplet 的。

最后的 rank1 和 mAP 有差距吗？

**Comment by 404289680** [comment]
还没训练完，训练完我再看看，请问pairwise_cosface用默认参数就行吗，所以loss用的是CrossEntropyLoss加pairwise_cosface对吗

**Comment by L1aoXingyu** [comment]
pairwise loss 在公开数据集上效果不太行，比较适合 shallow data，也就是每个 id 图片比较少的场景，公开数据集每个 id 的图片都比较多。
