### ISSUE TITLE
Cannot reproduce the results on Market using SBS(R50-ibn)

### ISSUE THREAD

**Issue by longma2020** [JDAI-CV/fast-reid#381]
With the config file in the repo the best result I could get on Market using SBS(R50-ibn) is as follows:
MAX_EPOCH: 120
One GPU
| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   | metric   |
| Market1501 | 92.73%   | 97.36%   | 98.52%    | 79.23% | 45.84% | 85.98%   |
Total training time: 1:40:12

The result of Rank-1 shown in the model Zoo is 95.7%

How can I improve the result?

**Comment by L1aoXingyu** [comment]
Please provide the config file.

**Comment by longma2020** [comment]
The only change to the default config is the MAX_EPOCH (=120). The default MAX_EPOCH is 60, whose performance is poorer.

**Comment by L1aoXingyu** [comment]
Maybe you use multi-gpu.
