### ISSUE TITLE
转化后的tensorrt模型怎么以run_on_loader方式做inference

### ISSUE THREAD

**Issue by qiuminghilllittlewan** [JDAI-CV/fast-reid#383]
你好，我已经将bot模型转换成了tensorrt模型，但是trt_inference.py 文件只支持单次的推理，怎么以run_on_loader的方式对多张图像同时进行推理，谢谢！

**Comment by L1aoXingyu** [comment]
在转 tensorrt 的时候，把 batchsize 设置为你希望的 batch 数目，就可以支持多图同时推理了。

**Comment by qiuminghilllittlewan** [comment]
这个可以实现，但是我每一次要推理的图像数目是不固定的，能不能像run_on_loader这种，设置batch_size=32,小于32张图像都可以一次性推理，而不是只能固定32

**Comment by L1aoXingyu** [comment]
可能需要升级 tensorrt，支持 dynamic input

**Comment by qiuminghilllittlewan** [comment]
好的，多谢！

**Comment by liaodaihai** [comment]
> 在转 tensorrt 的时候，把 batchsize 设置为你希望的 batch 数目，就可以支持多图同时推理了。

请问一下，我在转换tensorrt的时候把batchsize设置为8但是推理的时候，batchsize设置为8就会报错，是做什么问题呢？

**Comment by L1aoXingyu** [comment]
推理的时候，每次送到 engine 里面的输入必须是 8 batch
