### ISSUE TITLE
超参数配置

### ISSUE THREAD

**Issue by tangchent** [JDAI-CV/fast-reid#385]
我有一个疑问就是您提供的默认配置和论文中写的配置有些不同，比如论文中VeRi数据集的batch_size是16 ids * 4 imgs，而代码中的VeRi配置是4ids * 16imgs，论文中Loss使用Tri和Cirlceloss，但是VeRi配置是CE和Tri。
我尝试过使用论文中的配置，但是并没有训练出很好的结果。请问默认配置文件中的超参数是否还需要调整，如果要调整的话有什么需要注意的地方吗？

**Comment by L1aoXingyu** [comment]
Circle loss in paper means circle ID loss, which is used as `circleSoftmax` in `MODEL.BACKBONE.HEADS`.

所有的配置以 repo 里面的为准，不需要做任何修改，如果无法复现，可以提 issue。
因为最近 code 做了重构和较大的更新，所以之前的 config 也许无法复现结果，我们后续有时间会重新跑一下，下面这个 issue 里面提供了 vehicleid 相关的复现 config。

https://github.com/JDAI-CV/fast-reid/issues/334
