### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by 404289680** [JDAI-CV/fast-reid#387]
File "./fastreid/engine/defaults.py", line 377, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "./fastreid/engine/train_loop.py", line 147, in train
    self.after_epoch()
  File "./fastreid/engine/train_loop.py", line 181, in after_epoch
    h.after_epoch()
  File "./fastreid/engine/hooks.py", line 367, in after_epoch
    self._do_eval()
  File "./fastreid/engine/hooks.py", line 342, in _do_eval
    results = self._func()
  File "./fastreid/engine/defaults.py", line 332, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fastreid/engine/defaults.py", line 468, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP_ENABLED)
  File "./fastreid/evaluation/evaluator.py", line 153, in inference_on_dataset
    results = evaluator.evaluate()
  File "./fastreid/evaluation/reid_evaluation.py", line 100, in evaluate
    cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "./fastreid/evaluation/rank.py", line 200, in evaluate_rank
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "rank_cy.pyx", line 21, in rank_cy.evaluate_cy
TypeError: evaluate_cy() takes at least 8 positional arguments (7 given)

**Comment by L1aoXingyu** [comment]
Did you use the latest version of fastreid?

**Comment by 404289680** [comment]
yes

**Comment by L1aoXingyu** [comment]
Type `git diff`, what's showed?

**Comment by 404289680** [comment]
diff --git a/tools/deploy/trt_export.py b/tools/deploy/trt_export.py
old mode 100644
new mode 100755
diff --git a/tools/deploy/trt_inference.py b/tools/deploy/trt_inference.py
old mode 100644
new mode 100755
diff --git a/tools/plain_train_net.py b/tools/plain_train_net.py
old mode 100644
new mode 100755
diff --git a/tools/train_net.py b/tools/train_net.py
old mode 100644
new mode 100755

**Comment by 404289680** [comment]
this is only part

**Comment by 404289680** [comment]
i only changed NaiveIdentitySampler

**Comment by L1aoXingyu** [comment]
Please provide more information, such as your command line, did you compile the cython-based evaluation code? Can you run it normally in the old version?

**Comment by 404289680** [comment]
i can run it normally in the old version

**Comment by 404289680** [comment]
python tools/train_net.py --config-file logs/reid10w/r50ir/config.yaml --eval-only \
MODEL.WEIGHTS logs/reid10w/r50ir/model_0029.pth MODEL.DEVICE "cuda:0"

**Comment by 404289680** [comment]
i have tow different version codes in the same machine

**Comment by L1aoXingyu** [comment]
Maybe you can add the official wechat group, it will be more effective for discussion.

**Comment by 404289680** [comment]
sorry,i forget make
