### ISSUE TITLE
不能复现VeRi模型的结果

### ISSUE THREAD

**Issue by wlgcqh** [JDAI-CV/fast-reid#396]
使用model zoo中realease的VeRi模型，
python tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml --eval-only MODEL.WEIGHTS checkpoints/veri_sbs_R50-ibn.pth  MODEL.DEVICE "cuda:0"
测试结果为：
[01/28 11:32:17 fastreid.evaluation.testing]: Evaluation results in csv format:
| Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:-----------|:---------|:---------|:----------|:------|:-------|:---------|
| VeRi       | 95.17    | 97.74    | 98.93     | ###71.27 | 22.19  | 83.22    |

report的结果：
Method | Pretrained | Rank@1 | mAP | mINP | download
SBS(R50-ibn) | ImageNet | 97.0% | 81.9% | 46.3% | model
@L1aoXingyu @JinkaiZheng

**Comment by lxc86739795** [comment]
感谢反馈！

我们已发现bug所在，之前上传的model中bnneck层与新代码中对应层（bottleneck）的名称不一致，导致该bnneck参数没能正确读入，目前我们正在修复bug，稍后将上传更新的model。

**Comment by TelBotDev** [comment]
Dear, is this Rank-1 normal, considering that `97 - 96.84 = 1.16`. It is my first try of this perfect framework.
```
| Dataset   | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:----------|:---------|:---------|:----------|:------|:-------|:---------|
| VeRi      | 96.84    | 98.39    | 99.34     | 80.65 | 42.70  | 88.75    |
```

**Comment by TelBotDev** [comment]
> Dear, considering that `97 - 96.84 = 1.16`, is this Rank-1 normal? It is my first try of this perfect framework.
> 
> ```
> | Dataset   | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
> |:----------|:---------|:---------|:----------|:------|:-------|:---------|
> | VeRi      | 96.84    | 98.39    | 99.34     | 80.65 | 42.70  | 88.75    |
> ```
> 
> I use
> `export CUDA_VISIBLE_DEVICES=0; python3 tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml --num-gpus 1` to train and use
> `python3 tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml --num-gpus 1 --eval-only MODEL.WEIGHTS logs/veri/sbs_R50-ibn/model_best.pth`
> to test on the best model.

Sorry. How to close my reply. Because I have saw [the reply](https://github.com/JDAI-CV/fast-reid/issues/419#issuecomment-795403149) latter after I have replied this.
> 0.5 以内我们认为是实验波动。
