### ISSUE TITLE
评估模型达不到给出的结果

### ISSUE THREAD

**Issue by liyiersan** [JDAI-CV/fast-reid#398]
按照文档运行：python tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --eval-only \
MODEL.WEIGHTS market_agw_R50.pth  MODEL.DEVICE "cuda:0"
显示的结果如下：
![image](https://user-images.githubusercontent.com/35948100/106363173-f77bdf00-6361-11eb-8827-28ee10a5b733.png)
和model_zoo给出的差远了。

**Comment by cxh1996** [comment]
你应该使用AGW_R50.yml而不是bagtricks_R50.yml吧

**Comment by liyiersan** [comment]
谢谢谢谢，问题已解决。改用AGW_R50.yml之后，确实和model_zoo一样了，但是get_started文件里面写的是用bagtricks_R50.yml，这是为什么呢？

**Comment by L1aoXingyu** [comment]
@liyiersan 不同的 pretrain model 是用不同的 config train 出来的，需要一一匹配，否则会出现网络某些层不一致的问题，导致权重无法完全 load 进去。
