### ISSUE TITLE
使用自己训练好的模型测试demo出错

### ISSUE THREAD

**Issue by dongchaoqun** [JDAI-CV/fast-reid#40]
# encoding: utf-8
"""
@author:  liaoxingyu
@contact: sherlockliao01@gmail.com
"""

import argparse
import os

import cv2
import numpy as np
import torch
from torch import nn
from torch.backends import cudnn
import sys
sys.path.append('..')

from fastreid.config import get_cfg
from fastreid.data.transforms import ToTensor
from fastreid.modeling import build_model
from fastreid.utils.checkpoint import Checkpointer
from fastreid.data.datasets import DATASET_REGISTRY

cudnn.benchmark = True

def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg

def get_parser():
    parser = argparse.ArgumentParser(description="FastReID demo for builtin models")
    parser.add_argument(
        "--config-file",
        default="/home/dongchaoqun/fast-reid/projects/StrongBaseline/home/dongchaoqun/config.yaml",
        metavar="FILE",
        help="path to config file",
    )

    parser.add_argument(
        "--input",
        default=["/home/dongchaoqun/fast-reid/fastreid/data/datasets/Market-1501-v15.09.15/bounding_box_test/1203_c5s3_076337_01.jpg",
                 "/home/dongchaoqun/fast-reid/fastreid/data/datasets/Market-1501-v15.09.15/bounding_box_test/1182_c6s3_038217_01.jpg",
                 "/home/dongchaoqun/fast-reid/fastreid/data/datasets/Market-1501-v15.09.15/bounding_box_test/1183_c5s3_006943_05.jpg"],
        nargs="+",
        help="A list of space separated input images; "
             "or a single glob pattern such as 'directory/*.jpg'",
    )

    parser.add_argument(
        "--output",
        default="traced_module/",
        help="A file or directory to save export jit module.",

    )

    parser.add_argument(
        "--export-jitmodule",
        action='store_true',
        help="If export reid model to traced jit module"
    )

    parser.add_argument(
        "--opts",
        help="Modify config options using the command-line 'KEY VALUE' pairs",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser

class ReidDemo(object):
    """
    ReID demo example
    """

    def __init__(self, cfg):
        self.cfg = cfg.clone()
        #print(self.cfg)
        if cfg.MODEL.WEIGHTS.endswith('.pt'):
            self.model = torch.jit.load(cfg.MODEL.WEIGHTS)
        else:
            self.model = build_model(cfg)
            
            #print(self.model)
            # load pre-trained model
            Checkpointer(self.model).load(cfg.MODEL.WEIGHTS)

            self.model.eval()
            # self.model = nn.DataParallel(self.model)
            self.model.cuda()

        num_channels = len(cfg.MODEL.PIXEL_MEAN)
        self.mean = torch.tensor(cfg.MODEL.PIXEL_MEAN).view(1, num_channels, 1, 1)
        self.std = torch.tensor(cfg.MODEL.PIXEL_STD).view(1, num_channels, 1, 1)

    def preprocess(self, img):
        img = cv2.resize(img, tuple(self.cfg.INPUT.SIZE_TEST[::-1]))
        img = ToTensor()(img)[None, :, :, :]
        return img.sub_(self.mean).div_(self.std)

    @torch.no_grad()
    def predict(self, img_path):
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        data = self.preprocess(img)
        output = self.model.inference(data.cuda())
        feat = output.cpu().data.numpy()
        #print(feat)
        return feat

    @classmethod
    @torch.no_grad()
    def export_jit_model(cls, cfg, model, output_dir):
        example = torch.rand(1, len(cfg.MODEL.PIXEL_MEAN), *cfg.INPUT.SIZE_TEST)
        example = example.cuda()
        # if isinstance(model, (nn.DistributedDataParallel, nn.DataParallel)):
        #     model = model.module
        # else:
        #     model = model
        traced_script_module = torch.jit.trace_module(model, {"inference": example})
        traced_script_module.save(os.path.join(output_dir, "traced_reid_module.pt"))

if __name__ == '__main__':
    args = get_parser().parse_args()
    cfg = setup_cfg(args)
    reidSystem = ReidDemo(cfg)

    if args.export_jitmodule and not isinstance(reidSystem.model, torch.jit.ScriptModule):
        reidSystem.export_jit_model(cfg, reidSystem.model, args.output)

    feats = [reidSystem.predict(data) for data in args.input]
    #print(feats)

    cos_12 = np.dot(feats[0], feats[1].T).item()
    cos_13 = np.dot(feats[0], feats[2].T).item()
    cos_23 = np.dot(feats[1], feats[2].T).item()

    print('cosine similarity is {:.4f}, {:.4f}, {:.4f}'.format(cos_12, cos_13, cos_23))

Traceback (most recent call last):
  File "/home/dongchaoqun/fast-reid/demo/demo.py", line 133, in <module>
    reidSystem = ReidDemo(cfg)
  File "/home/dongchaoqun/fast-reid/demo/demo.py", line 92, in __init__
    Checkpointer(self.model).load(cfg.MODEL.WEIGHTS)
TypeError: __init__() missing 1 required positional argument: 'dataset'
请问这个问题应该如何解决，在注释掉Checkpointer(self.model).load(cfg.MODEL.WEIGHTS)这句话后却可以运行，同时请问如何使用自己的模型做测试，谢谢。

**Comment by L1aoXingyu** [comment]
我更新了repo，你可以 `git pull origin master` 然后再试试

**Comment by dongchaoqun** [comment]
感谢您的回答，demo测试已经通过。目前想做实时的行人重识别，是不是通过行人检测模型与您的模型结合即可实现。

**Comment by L1aoXingyu** [comment]
是的，detection+这个 repo 中的算法就可以实现实时的行人重识别了，可能需要做一些模型加速和量化来实现。
这个repo后续有计划加入部署方面的内容，敬请期待。
