### ISSUE TITLE
图像检索功能如何使用

### ISSUE THREAD

**Issue by yunchangxiaoguan** [JDAI-CV/fast-reid#400]
## ❓ How to do something using fastreid

请问project里面的fastretri要如何使用呢，我在里面只看到了如何训练，比如怎样建立搜索库，怎么输入一张图片找到与他相似的图片，这些在哪里可以实现嘛，谢谢

**Comment by L1aoXingyu** [comment]
高效检索的代码偏向工程，和这个代码库本身没什么关系，你可以去看 [faiss](https://github.com/facebookresearch/faiss) 或者 [milvus](https://github.com/milvus-io/milvus).

**Comment by yunchangxiaoguan** [comment]
> 高效检索的代码偏向工程，和 fastreid 本身没什么关系，你可以去看 [faiss](https://github.com/facebookresearch/faiss) 或者 [milvus](https://github.com/milvus-io/milvus).

好的，谢谢大佬，fastretri这块应该是基础吧，就是通过这块来提取特征，后面faiss那些搭建搜索库这种

**Comment by L1aoXingyu** [comment]
是的

**Comment by onlinehuazai** [comment]
请问重识别功能怎么用，运行那个文件？
