### ISSUE TITLE
Link to VERI-Wild Baseline checkpoint is dead

### ISSUE THREAD

**Issue by joaqo** [JDAI-CV/fast-reid#401]
Hi, this is a very simple bug, the link to the checkpoint of VERI-Wild Baseline in the [MODEL_ZOO](https://github.com/JDAI-CV/fast-reid/blob/master/MODEL_ZOO.md#veri-wild-baseline) is dead. 

This is the dead link:

https://github.com/JDAI-CV/fast-reid/releases/download/v0.1.1/veriwild_bot_R50-ibn.pth

Couldn't find any checkpoints for any vehicle-reid models, is there a reason for this?

Thanks for the great repo!

**Comment by lxc86739795** [comment]
The models are updated. Please try them.

**Comment by joaqo** [comment]
Just tried it, working really well, thanks!
