### ISSUE TITLE
代码里怎么没有看到IBN-b的结构

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#402]
我直接把原来的IBN-a结构换成IBN-b结构发现训到后面loss为nan了，请问如果换成IBN-b结构有什么需要注意呢

**Comment by L1aoXingyu** [comment]
你可以自己换成 ibn-b，我没有试过 ibn-b，之前从别人那里获得的信息是 ibn-a 效果更好，所以就没有加 ibn-b。
