### ISSUE TITLE
Issue about the Cost of Evaluation

### ISSUE THREAD

**Issue by workingcoder** [JDAI-CV/fast-reid#404]
First of all, I would like to thank the team from JD company for providing this FastReID open-source framework.

As for the problem I encountered when using this framework, I found that the evaluation process consumes a lot of memory, especially when using large data sets such as the MSMT17 dataset. When I use the MSMT17 dataset, the program stops in the evaluation phase, even though my machine has 64g of memory. And then,  after a while, the program will be killed by the system.

This issue seriously restricts the use of FastReID in research. So I hope you can optimize the code of the evaluation process and reduce its one-time consumption of a large amount of memory.

Looking forward to your response!

**Comment by workingcoder** [comment]
By the way, this problem is not caused by the dataloader of test data.
![image](https://user-images.githubusercontent.com/26352836/106710464-f16f5200-6630-11eb-9e23-66e886e0c79c.png)
From this picture, we can notice that the inference has been completed.
It just stops at the evaluation phase, when calculating Rank-n, mAP, etc.

**Comment by L1aoXingyu** [comment]
Thanks for your suggestion, and I will check this problem soon.

**Comment by kishansairam9** [comment]
@L1aoXingyu any update on the fix?

**Comment by L1aoXingyu** [comment]
Maybe update tomorrow or the day after it.

**Comment by QuentinAI** [comment]
> Maybe update tomorrow or the day after it.

你好，请问这个问题解决了吗，同样在训练的eval时，Inferenc结束进行evaluation出现内存爆掉，程序中止情况
