### ISSUE TITLE
Image retrieval 

### ISSUE THREAD

**Issue by Zumbalamambo** [JDAI-CV/fast-reid#405]
## ❓ How to do something using fastreid

Describe what you want to do, including:

1. what inputs you will provide, if any:
Input query image
2. what outputs you are expecting:
Matching image from the database 

is it possible to use this algorithm for place recognition task? Please provide an example

**Comment by L1aoXingyu** [comment]
What do you mean by "recognition tasks"? Image classification?

**Comment by Zumbalamambo** [comment]
Place recognition by Image retrieval

**Comment by L1aoXingyu** [comment]
Actually, place recog. can be a retrieval task or classification task, it depends on your need.

**Comment by Zumbalamambo** [comment]
Since it's large scale (1000+), being able to perform retrieval might be better than classification

**Comment by L1aoXingyu** [comment]
You can try it.
Btw, maybe you can reference google landmark competition.

**Comment by Zumbalamambo** [comment]
Is there any template on how I'm supposed to prepare the input dataset?

**Comment by L1aoXingyu** [comment]
`FastRetri` is an example. Actually, you only need to write the code about data load.

https://github.com/JDAI-CV/fast-reid/blob/master/projects/FastRetri/fastretri/datasets.py

**Comment by shnulailai** [comment]
How to inference the project(dataset is CUB)?What is the structure of  cub100-2011 when inference?

**Comment by L1aoXingyu** [comment]
It's same as the training phase.

**Comment by shnulailai** [comment]
廖大神您好：
&nbsp; &nbsp; &nbsp; 我已经训练好projects/FastRetri中的CUB数据集模型，在推理的过程中，出现的几个问题很困扰，如果有空的话能否帮忙看一下问题出在哪里？
1.首先，推理模块的数据集存放的方式，您看看是不是这样的？
datasets/CUB_200_2011
新加了gallery文件夹和query文件夹

query文件夹存放了两张图片


gallery文件夹存放的一些图片，其中有两张与query库中的test1.jpg,test2.jpg一模一样

2.执行推理运行代码，sh run_demo.sh

一直出现以下的错误，也不知道这个query库和gallery库的数据哪里来的？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JDAI-CV/fast-reid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月23日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JDAI-CV/fast-reid] Image retrieval  (#405)





 
It's the same as the training phase.

**Comment by L1aoXingyu** [comment]
看不到错误是什么

**Comment by ulanbator** [comment]
廖神，为什么图片搜索模型的权重没有发布呢？

**Comment by L1aoXingyu** [comment]
我们暂时只发布 person/vehicle reid model weights
