### ISSUE TITLE
Discrepancy between evaluation scores and visualization results

### ISSUE THREAD

**Issue by joaqo** [JDAI-CV/fast-reid#409]
Hi, I've been using fast-reid for some time, and its absolutely great, but I've been having some issues with the evaluation numbers showing me much better results than the results I actually get when I look at the visualizations fast-reid produces, or in real world usage.

Let me provide an example to show what I mean:

One training job is getting me these evaluation results:

```
  | Datasets   | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
  |:-----------|:---------|:---------|:----------|:------|:-------|:---------|
  | VRIC       | 80.93    | 93.92    | 96.02     | 86.76 | 86.76  | 83.85    |
```

So I think that in the visualizations I am going to get mostly matches in the top row, as I have 80% rank-1, which seems to be quite good. But the visualization images are mostly like this:

![10](https://user-images.githubusercontent.com/14966348/107559205-88e91d80-6bba-11eb-8366-7055d1172c02.jpg)

Where most of the top row results are errors (this is a custom dataset I am using, but it has happened in others). Anyone know a reason for why this could be happening? Am I just misinterpreting what the evaluation numbers mean?

Thanks!

**Comment by L1aoXingyu** [comment]
The visualization rank list shows the worst result by default. This means the first query show is the lowest AP query.

If you want to show a great result, you can change the sort.

**Comment by joaqo** [comment]
Gotcha, thanks. I am still getting some weird results, things like 100% confidence on wrong predictions on gallery images that are completely different from the query image, or failing to overfit a 300 image dataset, but it is possible I am doing something wrong. Thanks anyway.

**Comment by creativesalam** [comment]
Hi @joaqo, 

I am facing the same issue, have you figured it out? Thanks!
