### ISSUE TITLE
AssertionError: Invalid type <class 'fastreid.config.config.CfgNode'> for key MODEL

### ISSUE THREAD

**Issue by twj1999** [JDAI-CV/fast-reid#412]
when i run:
./tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml MODEL.DEVICE "cuda:0"

it appeared :

Traceback (most recent call last):
  File "./tools/train_net.py", line 12, in <module>
    from fastreid.config import get_cfg
  File "./fastreid/config/__init__.py", line 8, in <module>
    from .defaults import _C as cfg
  File "./fastreid/config/defaults.py", line 22, in <module>
    _C.MODEL = CN()
  File "./fastreid/config/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/twj/anaconda3/envs/fastreid/lib/python3.6/site-packages/yacs/config.py", line 100, in __setattr__
    type(value), name, _VALID_TYPES

AssertionError: Invalid type <class 'fastreid.config.config.CfgNode'> for key MODEL; valid types = {<class 'list'>, <class 'float'>, <class 'str'>, <class 'tuple'>, <class 'bool'>, <class 'int'>, <class 'dict'>}

我使用的是VeRi数据集，放在了项目的datasets目录下：datasets/VeRi/image_train(和image_test)，用的项目自带的VeRi对应的sbs_R50-ibn.yml配置文件，编译应该是通过了，训练的时候遇到了该问题。

实在没能自己解决，所以请求作者您帮忙看下，谢谢！

**Comment by L1aoXingyu** [comment]
去掉 `MODEL.DEVICE "cuda:0"` 会报错吗

**Comment by twj1999** [comment]
您好：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; 原谅我没有及时查看github回复，感谢您的专门邮件询问。
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 我刚才尝试了去掉 MODEL.DEVICE "cuda:0"的操作，还是会报同样的错误。事实上，我运行“./tools/train_net.py -h”指令（ see more options查看更多选项）也是汇报这个错误。


&nbsp;&nbsp; 为了方便您发现问题所在，我阐述下我运行项目的步骤经过：


&nbsp;&nbsp; 1.conda创建环境并安装一系列安装包，以配置项目运行环境
&nbsp;&nbsp; 2.由于文章中的“If you use backbones supported by fastreid, you do not need to do anything. It will automatically download the pre-train models. ”，我没有额外设置预训练模型，直接进行compile.
&nbsp;&nbsp; 3.运行cd fastreid/evaluation/rank_cylib; make all进行了编译，结果如下：
python3 setup.py build_ext --inplace
running build_ext
rm -rf build
python3 test_cython.py
*** Compare running time ***
=&gt; Using CMC metric
Python time: 0.13342379599998822 s
Cython time: 0.012320944999999028 s
CMC Cython is 10.829022936146435 times faster than python

=&gt; Using ROC metric
Python time: 0.0491705169999932 s
Cython time: 0.040499113000009856 s
ROC Cython is 1.2141134300887337 times faster than python

=&gt; Check precision
Rank results between python and cython are the same!
ROC results between python and cython are the same!

=&gt; Check exact values
mAP = [0.00657895 0.00543478 0.01591496 0.00684963 0.01449275 0.015625
&nbsp;0.01&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.00714286 0.03846154 0.01040639] 
cmc = [0. 0. 0. 0. 0.]
mINP = [0.00657895 0.00543478 0.02020202 0.0077821&nbsp; 0.01449275 0.015625
&nbsp;0.01&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.00714286 0.03846154 0.01351351]
Scores = [0.24854779 0.25491387 0.24539518 ... 0.27043003 0.27055764 0.27292013]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4.自行下载了VeRi数据集，放在了项目里的datasets文件下内,结构及命名如下：
datasets/     VeRi/         image_test/         image_train/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5.准备进行训练，在~/fast-reid-master$目录下运行 ./tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml MODEL.DEVICE "cuda:0"


以上是我的详细操作，在第5步遇到了该报错。希望有助于您发现问题。
事实上，我在您github该项目的issues讨论栏里发现了有人提过同样的问题，但是那个楼主解决了问题并关闭了讨论却没有说明解决方法。


期待您的回复，感谢！
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 谭伟佳



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "JDAI-CV/fast-reid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月16日(星期二) 晚上6:31
收件人:&nbsp;"JDAI-CV/fast-reid"<fast-reid@noreply.github.com&gt;;
抄送:&nbsp;"谭伟佳"<772284090@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JDAI-CV/fast-reid] AssertionError: Invalid type <class 'fastreid.config.config.CfgNode'&gt; for key MODEL (#412)





 
去掉 MODEL.DEVICE "cuda:0" 会报错吗

**Comment by L1aoXingyu** [comment]
使用的是最新的代码吗？python2 or python3?

**Comment by twj1999** [comment]
> 使用的是最新的代码吗？python2 or python3?

您好，我conda创建环境里的的python版本是3.6.12。我用的是您一月中旬时的版本，我在一月中旬下载了您的项目。另外，我刚才又尝试了您最新的版本，还是报一样的错误。我发现这两个版本的不同在于VeRi数据集对应的yml文件中的WARMUP_ITERS参数，旧为10新为2000，其他的不同我没细看。
请问这个报错表明的问题方向是什么。我昨天给您邮箱的邮件里记录了我操作的步骤供您参考，不知道有没有看到。另外我在官方微信讨论群里，微信号18845098812，不方便可以微信。谢谢

**Comment by L1aoXingyu** [comment]
@twj1999 你再 `git pull` 更新一下代码，然后运行 `python3 tools/train_net.py` 看看是否还会报错？

**Comment by twj1999** [comment]
solution:

try:  uninstall pyyaml,  then install(or reinstall) PyYAML.

**Comment by mxl1990** [comment]
我也遇到了这个问题，重装pyyaml的办法不行，pyyaml的版本已经升级到6.0了

**Comment by mxl1990** [comment]
> 我也遇到了这个问题，重装pyyaml的办法不行，pyyaml的版本已经升级到6.0了

问题出在yacs版本，出错的版本yacs是1.6版本，安装了yacs 1.8的版本后解决该问题
