### ISSUE TITLE
求助：关于和论文中指标无法对齐的问题

### ISSUE THREAD

**Issue by xiaochengsky** [JDAI-CV/fast-reid#419]
你好：
       我用 resnet50 跑了几组实验，AGW，sbs，bagtricks 和 R50 相关的配置都跑了一遍，但是无法复现出论文提出的指标，请问是我哪里配置没注意吗？Market1501 R1掉了 0.22，mAP 掉了 0.02，主要是 Duke mAP掉了将近一个点（sbs跑出来是R1-89.09，mAP-78.79）。

                                       Market           Duke             MSMT
                                       R1   mAP      R1  mAP        R1   mAP
FastReID (ResNet50)      95.4 88.2      89.6 79.8        83.3 59.9

**Comment by L1aoXingyu** [comment]
0.5 以内我们认为是实验波动。
