### ISSUE TITLE
使用fastrt api推理后不同图片之间的余弦相似0.98

### ISSUE THREAD

**Issue by fengfengcxf** [JDAI-CV/fast-reid#421]
用model_zoo中的sbs-R50-ibn转wts后生成引擎，几张图片的余弦相似：
![image](https://user-images.githubusercontent.com/68675033/110270394-a87c3600-8000-11eb-8af6-83c5486ec544.png)
请问是什么问题呀？

**Comment by L1aoXingyu** [comment]
Please try to use the latest fastrt code.

**Comment by SHIsue** [comment]
I had the same problem with the latest fastrt code, have you solved this problem?

**Comment by fengfengcxf** [comment]
@SHIsue 找个阈值和拉伸函数，一般都是单调函数，可以线性拉伸下，但是这个阈值不好控，可以根据实际应用场景建个测试集来统计baseline。仅供参考哈

**Comment by SHIsue** [comment]
我测试的时候，cos距离基本上都是0.9999+，也不知道是什么原因，排查了一下好像python在test的时候数据进入网络之前没有归一化，但是cpp的归一化了，不知道是不是这个的原因导致后面inference出来的feature对不齐。。。。。

**Comment by HaoWangDL** [comment]
@fengfengcxf 我遇到和你一样的问题，用-python模型sbs-R50-ibn权重推理时，不同图像的余弦相似度非常接近。把模型转为onnx后，用onnx_inference推理，不同图像的余弦相似度也非常接近。余弦值几乎是0.99878左右。
几乎是请问你是怎么解决的啊？

**Comment by JiaoPaner** [comment]
@HaoWangDL 请问你解决这个问题了吗 onnx_inference推理后不同图片间的相似度达到0.98

**Comment by deep-practice** [comment]
我用官方的模型，相似度都挺高的，我统计了一下，最低的都有80%+

**Comment by JiaoPaner** [comment]
@deep-practice 我已解决  将距离计算改为 distmat = 1 - torch.mm(base_feat, feat.t())  小于0.025

**Comment by JiaoPaner** [comment]
@deep-practice 我已解决  将距离计算改为 distmat = 1 - torch.mm(base_feat, feat.t())   经过验证 距离小于0.025都是同一人 大于这个值的不是同一人

**Comment by deep-practice** [comment]
@JiaoPaner 谢谢，我试试

**Comment by nanhui69** [comment]
> sbs-R50-ibn

你这边 这个模型的流程你都跑通了么？可以加个联系方式交流下么？

**Comment by JiaoPaner** [comment]
> > @deep-practice @HaoWangDL 我已解决 将距离计算改为 distmat = 1 - torch.mm(base_feat, feat.t()) 经过验证 距离小于0.025都是同一人 大于这个值的不是同一人
> 
> @JiaoPaner 请问base_feat与feat是什么类型的变量？ c++的实现中通过reid获得的feature是长度为2048的float数组， 上诉相似性的计算应该如何处理 ？
@boliurise 
两者都是向量/矩阵,做矩阵乘法
```md
base_feat = [0.1,0.2,0.1,0.1],feat.t() = [0.2,0.2,0.2,0.2]^T   
torch.mm(base_feat, feat.t())  = 0.1 * 0.2 + 0.2 * 0.2 + 0.1 * 0.2 + 0.1 * 0.2
```

**Comment by boliurise** [comment]
> > > @deep-practice @HaoWangDL 我已解决 将距离计算改为 distmat = 1 - torch.mm(base_feat, feat.t()) 经过验证 距离小于0.025都是同一人 大于这个值的不是同一人
> > 
> > 
> > @JiaoPaner 请问base_feat与feat是什么类型的变量？ c++的实现中通过reid获得的feature是长度为2048的float数组， 上诉相似性的计算应该如何处理 ？
> > @boliurise
> > 两者都是向量/矩阵,做矩阵乘法
> 
> ```lisp
> base_feat = [0.1,0.2,0.1,0.1],feat.t() = [0.2,0.2,0.2,0.2]^T   
> torch.mm(base_feat, feat.t())  = 0.1 * 0.2 + 0.2 * 0.2 + 0.1 * 0.2 + 0.1 * 0.2
> ```
> 
> C++里面两个feature 对应索引的值 相乘再相加即可

@JiaoPaner 
![2022-09-17](https://user-images.githubusercontent.com/6425978/190853807-401866f2-c242-4b83-961e-b8b3a8f0ce25.jpg)
使用fastreid model zoo 中的"Market1501 Baselines - SBS(R50-ibn)“ 在Market 1501 数据集上作测试。 如图中所示，distmat的值均为-600多, 你那边作测试时， dismat的值一般为多少 ?
