### ISSUE TITLE
Question About the overhual in FastDistill

### ISSUE THREAD

**Issue by KingWangSeet** [JDAI-CV/fast-reid#422]
The overhual  is  only used in  FastDistill (excepted the loss_cls、loss_triplet、loss_jsdiv）on the dukemtmc , follw the kd-sbs_r101ibn-sbs_r34.yml setting,  get the following results:   Is't norm?
![image](https://user-images.githubusercontent.com/23491388/110293134-248a7400-8029-11eb-8f8d-935f7eb219e7.png)

**Comment by KingWangSeet** [comment]
I change the code in projects/FastDistill/fastdistill/overhaul.py to use loss_overhual  only: 
![image](https://user-images.githubusercontent.com/23491388/110293520-a2e71600-8029-11eb-8c7b-b2b34dec2608.png)

**Comment by L1aoXingyu** [comment]
I think it's normal, though I didn't do this experiment.
The original reid loss is very important for distillation.

**Comment by KingWangSeet** [comment]
Thanks a lot!
