### ISSUE TITLE
i suppose wether there exsit some problem in the preprocessing of fastrt

### ISSUE THREAD

**Issue by fengfengcxf** [JDAI-CV/fast-reid#423]
while frist in model.py the method of inference will div255 at preprocessing_cpu, but in createengine when use preprocessing_gpu，the mean and std are all without div 255.......，Is that right? Please confirm，thank you

**Comment by TCHeish** [comment]
Yes, you only need div255 once. 
Although, You can choice this step from preprocessing_cpu to preprocessing_gpu.
