### ISSUE TITLE
Partial Reid training error

### ISSUE THREAD

**Issue by batuhan-baskurt** [JDAI-CV/fast-reid#431]
I have the error above when I try to start the training of partial reid like this:

`CUDA_VISIBLE_DEVICES='0' python projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'`

> Traceback (most recent call last):
>   File "projects/PartialReID/train_net.py", line 82, in <module>
>     args=(args,),
>   File "./fastreid/engine/launch.py", line 71, in launch
>     main_func(*args)
>   File "projects/PartialReID/train_net.py", line 70, in main
>     return trainer.train()
>   File "./fastreid/engine/defaults.py", line 376, in train
>     super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
>   File "./fastreid/engine/train_loop.py", line 143, in train
>     self.run_step()
>   File "./fastreid/engine/defaults.py", line 385, in run_step
>     self._trainer.run_step()
>   File "./fastreid/engine/train_loop.py", line 238, in run_step
>     loss_dict = self.model(data)
>   File "/home/test/miniconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "./fastreid/modeling/meta_arch/baseline.py", line 55, in forward
>     losses = self.losses(outputs, targets)
> **TypeError: losses() takes 2 positional arguments but 3 were given**

I can run training of fast reid without any problem. This error only happens while using partial re-id.

Here you have config.yaml:

> `CUDNN_BENCHMARK: true
> DATALOADER:
>   NAIVE_WAY: false
>   NUM_INSTANCE: 4
>   NUM_WORKERS: 8
>   PK_SAMPLER: true
> DATASETS:
>   COMBINEALL: false
>   NAMES:
>   - Market1501
>   TESTS:
>   - PartialiLIDS
>   - OccludedREID
> INPUT:
>   AUGMIX_PROB: 0.0
>   AUTOAUG_PROB: 0.0
>   CJ:
>     BRIGHTNESS: 0.15
>     CONTRAST: 0.15
>     ENABLED: false
>     HUE: 0.1
>     PROB: 0.5
>     SATURATION: 0.1
>   DO_AFFINE: false
>   DO_AUGMIX: false
>   DO_AUTOAUG: false
>   DO_FLIP: true
>   DO_PAD: false
>   FLIP_PROB: 0.5
>   PADDING: 10
>   PADDING_MODE: constant
>   REA:
>     ENABLED: false
>     PROB: 0.5
>     VALUE:
>     - 123.675
>     - 116.28
>     - 103.53
>   RPT:
>     ENABLED: false
>     PROB: 0.5
>   SIZE_TEST:
>   - 384
>   - 128
>   SIZE_TRAIN:
>   - 384
>   - 128
> KD:
>   MODEL_CONFIG:
>   - ''
>   MODEL_WEIGHTS:
>   - ''
> MODEL:
>   BACKBONE:
>     DEPTH: 50x
>     FEAT_DIM: 2048
>     LAST_STRIDE: 1
>     NAME: build_resnet_backbone
>     NORM: BN
>     PRETRAIN: true
>     PRETRAIN_PATH: resnet50_ibn_a-d9d0bb7b.pth
>     WITH_IBN: true
>     WITH_NL: false
>     WITH_SE: false
>   DEVICE: cuda
>   FREEZE_LAYERS:
>   - ''
>   HEADS:
>     CLS_LAYER: linear
>     EMBEDDING_DIM: 0
>     MARGIN: 0.15
>     NAME: DSRHead
>     NECK_FEAT: before
>     NORM: BN
>     NUM_CLASSES: 751
>     POOL_LAYER: avgpool
>     SCALE: 128
>     WITH_BNNECK: true
>   LOSSES:
>     CE:
>       ALPHA: 0.2
>       EPSILON: 0.1
>       SCALE: 1.0
>     CIRCLE:
>       GAMMA: 128
>       MARGIN: 0.25
>       SCALE: 1.0
>     COSFACE:
>       GAMMA: 128
>       MARGIN: 0.25
>       SCALE: 1.0
>     FL:
>       ALPHA: 0.25
>       GAMMA: 2
>       SCALE: 1.0
>     NAME:
>     - CrossEntropyLoss
>     - TripletLoss
>     TRI:
>       HARD_MINING: false
>       MARGIN: 0.3
>       NORM_FEAT: false
>       SCALE: 1.0
>   META_ARCHITECTURE: PartialBaseline
>   PIXEL_MEAN:
>   - 123.675
>   - 116.28
>   - 103.53
>   PIXEL_STD:
>   - 58.395
>   - 57.120000000000005
>   - 57.375
>   QUEUE_SIZE: 8192
>   WEIGHTS: ''
> OUTPUT_DIR: projects/PartialReID/logs/test_partial
> SOLVER:
>   BASE_LR: 0.00035
>   BIAS_LR_FACTOR: 2.0
>   CHECKPOINT_PERIOD: 10
>   DELAY_EPOCHS: 0
>   ETA_MIN_LR: 1.0e-07
>   FP16_ENABLED: false
>   FREEZE_FC_ITERS: 0
>   FREEZE_ITERS: 0
>   GAMMA: 0.1
>   HEADS_LR_FACTOR: 1.0
>   IMS_PER_BATCH: 64
>   MAX_EPOCH: 30
>   MOMENTUM: 0.9
>   NESTEROV: true
>   OPT: Adam
>   SCHED: MultiStepLR
>   STEPS:
>   - 15
>   - 25
>   WARMUP_FACTOR: 0.01
>   WARMUP_ITERS: 1000
>   WARMUP_METHOD: linear
>   WEIGHT_DECAY: 0.0005
>   WEIGHT_DECAY_BIAS: 0.0
> TEST:
>   AQE:
>     ALPHA: 3.0
>     ENABLED: false
>     QE_K: 5
>     QE_TIME: 1
>   DSR:
>     ENABLED: true
>   EVAL_PERIOD: 5
>   FLIP_ENABLED: false
>   IMS_PER_BATCH: 128
>   METRIC: cosine
>   PRECISE_BN:
>     DATASET: Market1501
>     ENABLED: false
>     NUM_ITER: 300
>   RERANK:
>     ENABLED: false
>     K1: 20
>     K2: 6
>     LAMBDA: 0.3
>   ROC_ENABLED: false`

Could you please help me to solve this problem?

**Comment by L1aoXingyu** [comment]
We will solve this problem as soon as possible.

**Comment by lichaomingAI** [comment]
I met the same problem.

**Comment by lichaomingAI** [comment]
@batuhan-baskurt I try to modify the code which in projects/PartialReID/partialreid/partialbaseline.py. Then it start training.

from fastreid.modeling.losses import *
from fastreid.modeling.meta_arch import Baseline
from fastreid.modeling.meta_arch.build import META_ARCH_REGISTRY

@META_ARCH_REGISTRY.register()
class PartialBaseline(Baseline):

    def losses(self, outputs, gt_labels):
        r"""
        Compute loss from modeling's outputs, the loss function input arguments
        must be the same as the outputs of the model forwarding.
        """
        # fmt: off
        # outputs           = outs["outputs"]
        # gt_labels         = outs["targets"]
        # model predictions
        pred_class_logits = outputs['pred_class_logits'].detach()
        cls_outputs       = outputs["cls_outputs"]
        fore_cls_outputs  = outputs["fore_cls_outputs"]
        global_feat       = outputs["global_features"]
        fore_feat         = outputs["foreground_features"]
        # fmt: on

**Comment by lichaomingAI** [comment]
@batuhan-baskurt I found the evaluate error too. We must modify the code which in projects/PartialReID/partialreid/dsr_evaluation.py like this:

        if self.cfg.TEST.DSR.ENABLED:
            logger.info("Testing with DSR setting")
            dist = compute_dsr_dist(spatial_features[:self._num_query], spatial_features[self._num_query:], dist,
                                    scores[:self._num_query])
            cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids,
                                                 query_camids, gallery_camids)
        else:
            cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids,
                                                 query_camids, gallery_camids)
        mAP = np.mean(all_AP)
        mINP = np.mean(all_INP)

Then the training result :

[03/19 20:32:31 fastreid.engine.defaults]: Prepare testing set
[03/19 20:32:31 fastreid.data.datasets.bases]: => Loaded PartialREID in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 60      | 300        | 5           |
| gallery  | 60      | 300        | 5           |
[03/19 20:32:31 fastreid.evaluation.evaluator]: Start inference on 600 images
[03/19 20:32:32 fastreid.evaluation.evaluator]: Inference done 11/10. 0.0078 s / batch. ETA=0:00:00
[03/19 20:32:32 fastreid.evaluation.evaluator]: Total inference time: 0:00:00.539325 (0.107865 s / batch per device)
[03/19 20:32:32 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.009301 s / batch per device)
[03/19 20:32:32 fastreid.partialreid.dsr_evaluation]: Testing with DSR setting
[03/19 20:32:46 fastreid.engine.defaults]: Prepare testing set
[03/19 20:32:46 fastreid.data.datasets.bases]: => Loaded PartialiLIDS in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 119     | 119        | 1           |
| gallery  | 119     | 119        | 1           |
[03/19 20:32:46 fastreid.evaluation.evaluator]: Start inference on 238 images
[03/19 20:32:47 fastreid.evaluation.evaluator]: Total inference time: 0:00:00.112336 (0.112336 s / batch per device)
[03/19 20:32:47 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.009358 s / batch per device)
[03/19 20:32:47 fastreid.partialreid.dsr_evaluation]: Testing with DSR setting
[03/19 20:32:52 fastreid.engine.defaults]: Prepare testing set
[03/19 20:32:52 fastreid.data.datasets.bases]: => Loaded OccludedREID in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 200     | 1000       | 5           |
| gallery  | 200     | 1000       | 5           |
[03/19 20:32:52 fastreid.evaluation.evaluator]: Start inference on 2000 images
[03/19 20:32:56 fastreid.evaluation.evaluator]: Total inference time: 0:00:02.983242 (0.110490 s / batch per device)
[03/19 20:32:56 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.010137 s / batch per device)
[03/19 20:32:56 fastreid.partialreid.dsr_evaluation]: Testing with DSR setting
[03/19 20:33:44 fastreid.evaluation.testing]: Evaluation results in csv format: 
| Datasets     | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   |
|:-------------|:---------|:---------|:----------|:------|:-------|
| PartialREID  | 0.71     | 0.87     | 0.91      | 0.67  | 0.54   |
| PartialiLIDS | 0.66     | 0.87     | 0.90      | 0.75  | 0.75   |
| OccludedREID | 0.73     | 0.85     | 0.88      | 0.63  | 0.46   |
[03/19 20:33:44 fastreid.utils.checkpoint]: Saving checkpoint to projects/PartialReID/logs/test_partial/model_0001.pth
[03/19 20:33:44 fastreid.utils.events]:  eta: 2:28:54  epoch/iter: 1/1615  total_loss: 3.254  loss_avg_branch_cls: 1.631  loss_fore_branch_cls: 1.621  loss_avg_branch_triplet: 0  loss_fore_branch_triplet: 0  time: 0.0970  data_time: 0.0004  lr: 3.50e-04  max_mem: 5463M
[03/19 20:34:01 fastreid.utils.events]:  eta: 2:28:14  epoch/iter: 2/1799  total_loss: 3.03  loss_avg_branch_cls: 1.513  loss_fore_branch_cls: 1.517  loss_avg_branch_triplet: 0  loss_fore_branch_triplet: 0  time: 0.0966  data_time: 0.0004  lr: 3.50e-04  max_mem: 5463M

**Comment by L1aoXingyu** [comment]
Please use the latest code
