### ISSUE TITLE
k-reciprocal neighbors in reranking returns incorrect reciprocal neighbors

### ISSUE THREAD

**Issue by ImNotMT** [JDAI-CV/fast-reid#446]
k-reciprocal neighbors in compute_dist.py ([def k_reciprocal_neigh](https://github.com/JDAI-CV/fast-reid/blob/master/fastreid/utils/compute_dist.py)) returns incorrect reciprocal neighbors.

Test codes samples:
```python
initial_rank = numpy.array([[0, 3, 2, 1, 4],  [1, 2, 0, 3, 4], [2, 0, 1, 3, 4], [3, 0, 2, 1, 4], [4, 3, 0, 2, 1]])
i = 4
k1 = 4
krn = k_reciprocal_neigh(initial_rank, i, k1)
print('krn: ', krn)
```

Test output:
`krn:  [4 3 0 2 1]`

However, g4 is not in N(g0, 4), N(g1, 4), N(g2, 4), N(g3, 4), but only in N(g4, 4)
Actually, the first impression is the k-reciprocal neighbors size should <= k. The result has 5 neighbors but k is 4.

Refer to [re-ranking paper](https://openaccess.thecvf.com/content_cvpr_2017/papers/Zhong_Re-Ranking_Person_Re-Identification_CVPR_2017_paper.pdf)
The N(p, k1) should be `initial_rank[i, : k1]`
The N(gi, k1) should be `initial_rank[forward_k_neigh_index, : k1]`

so I tried to fix the k reciprocal neighbors function:
```python
def k_reciprocal_neigh(initial_rank, i, k1):
    forward_k_neigh_index = initial_rank[i, : k1]
    backward_k_neigh_index = initial_rank[forward_k_neigh_index, : k1]
    fi = np.where(backward_k_neigh_index == i)[0]
    return forward_k_neigh_index[fi]
```

Test output:
`krn:  [4]`

This issue could be also traced back to https://github.com/JDAI-CV/fast-reid/blob/master/fastreid/evaluation/rerank.py

**Comment by L1aoXingyu** [comment]
@ImNotMT Thanks! I will check it later.
