### ISSUE TITLE
The performance gap between training with Single GPU and Multi GPU

### ISSUE THREAD

**Issue by chanhoeom** [JDAI-CV/fast-reid#449]
Hi~ thanks for releasing awesome codes.

I notice that there are a huge performance gap depending on the number of GPUs I use during training. I followed "sbs_R50-ibn.yml" configuration, while setting MAX_EPOCH to 120.

When I use a single GPU:
![image](https://user-images.githubusercontent.com/25449812/113078958-176b3a00-920f-11eb-9fc7-22b1e888f791.png)
I got the similar results with those in the paper.

However, when I use two GPUs:
![image](https://user-images.githubusercontent.com/25449812/113079016-3cf84380-920f-11eb-8c79-37051f17a872.png)
The results are degraded quite a lot...

What's wrong with this?

I would change batch size in to double, and let you know the results.

**Comment by L1aoXingyu** [comment]
Please follow the issue instructions and put the training config.
