### ISSUE TITLE
为什么用你的代码能得到比较好的结果呢

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#451]
之前试过罗浩的strong-baseline和MGN的代码，训练market基本map都在86左右，用了这份代码map能达到89。一些常用的trick strong-baseline也都有用到啊，比如circleloss、ibn、bnneck等等，为什么fastreid的map会高这么多呢？代码我都看过一遍，没看到明显区别啊，烦请作者解惑

**Comment by guanyonglai** [comment]
是训练方法上的区别吗，那也不至于差这么多吧

**Comment by L1aoXingyu** [comment]
一些训练trick和超参数的配合，主要的提升应该来自 circleSoftmax
