### ISSUE TITLE
TypeError: _test_loader_from_config() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/fast-reid#454]
**运行：**
python ./demo/visualize_result.py --config-file ./configs/Market1501/bagtricks_R50.yml --vis-label --dataset-name Market1501  --opts MODEL.WEIGHTS ./logs/market1501/bagtricks_R50/model_final.pth
**报错：**
Traceback (most recent call last):
  File "./demo/visualize_result.py", line 104, in <module>
    test_loader, num_query = build_reid_test_loader(cfg, args.dataset_name)
  File "./fastreid/config/config.py", line 264, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "./fastreid/config/config.py", line 292, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
TypeError: _test_loader_from_config() takes 1 positional argument but 2 were given

**Comment by linghu8812** [comment]
遇到了同样的问题，请问解决了么？

**Comment by L1aoXingyu** [comment]
fixed in (#468)
