### ISSUE TITLE
why delete triplet loss with distributed training setting?

### ISSUE THREAD

**Issue by knaffe** [JDAI-CV/fast-reid#458]
https://github.com/JDAI-CV/fast-reid/blob/e124a9afd3d662da32cb4c0b61175c83c58ce1ff/fastreid/modeling/losses/triplet_loss.py#L86

Why do you delete this distributed training setting for Triplet loss? 
If deleting this, how to achieve the distributed training with triplet loss? 
Is it not key point for triplet loss? I think it is because the model outputs ALL embeds when finishing distributed training, so we don't need the gather layer here.

**Comment by L1aoXingyu** [comment]
We try triplet loss across GPU, but found there is no gain but introducing extra communication overhead. So we just turn it off and just compute triplet loss on intra-GPU.
