### ISSUE TITLE
有关random patch transform的实现

### ISSUE THREAD

**Issue by JR-Wang** [JDAI-CV/fast-reid#460]
我想在数据预处理中加入random patch transform，所以将yml文件改为如下：
_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

INPUT：
  RPT：
    ENABLED：True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/mgn_R50-ibn
训练的时候发现，fastreid/data/transforms/transforms.py中提供的方法应该是对numpy数组进行处理的，但数据传到这里的时候显示是tensor了，请问是我的操作有问题吗？如果没有问题，这里需要自己加入np.array和tensor之间的转换吗？
另外，作者有试过加入这一处理的效果如何吗？
谢谢！

**Comment by L1aoXingyu** [comment]
这个之前试过，后期代码更新之后，可能这个部分没有做好兼容，稍后更新一个 patch
