### ISSUE TITLE
Training osnet model on MTMC and VeRi

### ISSUE THREAD

**Issue by NealAnthoons** [JDAI-CV/fast-reid#463]
I'm trying to train a OSnet model on both the MTMC and VeRi dataset.  Is this a good approach ?

1. Change bagtricks config file [BACKBONE] [NAME] to build_osnet_backbone
2.  Download both VeRi and MTMC datasets and put them in datasets
3.  Use train.py

If this is right. Where do I download the datasets ?

**Comment by L1aoXingyu** [comment]
MTMC is the person reid dataset and VeRi is the vehicle reid dataset. In my opinion, you'd better not combine them to train.
