### ISSUE TITLE
fastrt api inference and then calculate cosine distance, the results are similar?

### ISSUE THREAD

**Issue by SHIsue** [JDAI-CV/fast-reid#465]
When I use FastRT to inference with generated sbs_R50.engine, the features of different images are very similar:
img1: 0.419267 0.419628 ...
img2: 0.419799 0.423215 ...
img3: 0.419326 0.423623 ...
And if I use the same image to extract features by python and cpp, the outputs of python version and cpp version are different, why?

Because of the output of inference are similar on different images, the calculated cos distance are like:
0.999988  0.999989 0.999987 0.999988 ...

What is the reason for this?  =.=
Thank you very much~

**Comment by SHIsue** [comment]
Solved. 
Reference：https://github.com/JDAI-CV/fast-reid/issues/423
Method：
For fastreid model inference, there's no need to div 255.

fast-reid/projects/FastRT/tools/gen_wts.py
 input = torch.ones(1, 3, cfg.INPUT.SIZE_TEST[0], cfg.INPUT.SIZE_TEST[1]).to(cfg.MODEL.DEVICE) 

I should change this to
input = torch.ones(1, 3, cfg.INPUT.SIZE_TEST[0], cfg.INPUT.SIZE_TEST[1]).to(cfg.MODEL.DEVICE) * 255.
and diable div 255 from fastrt.
then the results from real image data should be correct.

**Comment by Thangbluee** [comment]
@SHIsue @HaoWangDL can you guys provide code that gen pth model to wts file? gen_wts.file did not work for me
