### ISSUE TITLE
reid更大数据的训练参数配置问题？

### ISSUE THREAD

**Issue by sky186** [JDAI-CV/fast-reid#466]
@L1aoXingyu 
您好，请问训练数据如果 达到百万千万等等数据量， config文件的一些参数  有更好的配置吗？
例如 
1、不用 tripletloss + pk sample   ,triplet 全部用circlelosss 替换  （模仿人脸了），因为也有人说数据量较大 tripletloss表现不如  circleloss
2、配置文件基本不变，但是batch变， tripletloss 的数据采样 p k 有什么需要变化吗？ batch 单卡 开到256，  多卡的话这里好像也得注意？

**Comment by L1aoXingyu** [comment]
我的训练配置是保持单卡 batch=64，用 sgd，lr 是 0.01，pk sampler 每个 id 采样 4 张图片，然后只用 CircleSoftmax，不用 tripletLoss.
