### ISSUE TITLE
caffe_export.py转caffe后，输出层不是output层，输出层的shape是1x2048x24x8

### ISSUE THREAD

**Issue by gengwb** [JDAI-CV/fast-reid#467]
请问中间是不是有最后有些层没转完吗？

**Comment by L1aoXingyu** [comment]
用的是哪个模型转

**Comment by gengwb** [comment]
> 用的是哪个模型转
sbs_R50-ibn 这个模型，我按照README里面的步骤添加了，layer {
            name: "avgpool1"
            type: "Pooling"
            bottom: "relu_blob49"
            top: "avgpool_blob1"
            pooling_param {
                pool: AVE
                global_pooling: true
            }
        }
这个后，shape是对的，现在还有个问题就是0022_c6s1_002976_01.jpg在caffe_inference.py 出来的结果和demo.py 出来的结果，余弦相似度很低只有-0.011389587

**Comment by L1aoXingyu** [comment]
确认一下是不是预处理的问题
