### ISSUE TITLE
caffe与pytorch 出来的结果不一致，会是这些The checkpoint state_dict contains keys that are not used by the model报错带来的影响吗

### ISSUE THREAD

**Issue by gengwb** [JDAI-CV/fast-reid#472]
![image](https://user-images.githubusercontent.com/40818073/115741828-ab6d9300-a3c2-11eb-95da-29ccaec24074.png)
如题

**Comment by L1aoXingyu** [comment]
是的，caffe 不支持直接转 non-local，如果要使用 non-local，只能自己定义 caffe layer，然后把权重 load 进去。

**Comment by gengwb** [comment]
> 是的，caffe 不支持直接转 non-local，如果要使用 non-local，只能自己定义 caffe layer，然后把权重 load 进去。

请问，你们有non-local的替代训练方案吗？能让caffe转换成功的，又能不掉模型精度的

**Comment by L1aoXingyu** [comment]
不需要 non-local，速度又慢，精度也不怎么提升
