### ISSUE TITLE
大数据训练参数配置

### ISSUE THREAD

**Issue by wangguangyuan** [JDAI-CV/fast-reid#476]
你好，感谢公开这么优秀的reid框架，现在有个问题需要请教，就是用咱们架构在大数据集上训练参数如何配置，比如在单机8卡或者4卡上，batch size、学习速率，冻结，instance number d等相关参数如何配置，能否给个可以参考的config问件

**Comment by L1aoXingyu** [comment]
推荐的配置是保持单卡 batch 64，然后 lr 按照 linear scale 的方式修正，base lr 是 0.01，使用 SGD，每个 id 采样4 张图或者2张图，使用人脸的 loss

**Comment by wangguangyuan** [comment]
@L1aoXingyu 感谢大神快速回复，我去试试有问题再请教大神！
