### ISSUE TITLE
有关模型推理时间的问题

### ISSUE THREAD

**Issue by JR-Wang** [JDAI-CV/fast-reid#477]
你好，我在1060ti上测试mgn模型的前向推理时间，在fastreid/modeling/meta_arch/mgn.py中，打印出MGN的forward函数的执行时间，发现修改输入的尺寸，如修改384*128为288*96；或者修改test batch的大小，如将其从32修改为1，forward函数的执行时间并没有太大变化。但是您在evaluator.py中打印的Total inference time: {} ({:.6f} s / batch per device, on {} devices)确实会随输入数据的大小变化发生改变，请问这是什么原因呢？
具体测试数据如下
batch = 32, 输入288*96时
input size:  torch.Size([32, 3, 288, 96])
cost time:  0.01912196900229901
input size:  torch.Size([32, 3, 288, 96])
cost time:  0.01779893902130425
input size:  torch.Size([32, 3, 288, 96])
cost time:  0.020249406981747597
input size:  torch.Size([32, 3, 288, 96])
cost time:  0.018268920946866274
[04/26 17:32:05 fastreid.evaluation.evaluator]: Inference done 11/24. 0.1999 s / batch. ETA=0:00:02
batch = 32, 输入384*128时
input size:  torch.Size([32, 3, 384, 128])
cost time:  0.019666051026433706
input size:  torch.Size([32, 3, 384, 128])
cost time:  0.020363551971968263
input size:  torch.Size([32, 3, 384, 128])
cost time:  0.02058741997461766
input size:  torch.Size([32, 3, 384, 128])
cost time:  0.020216608012560755
[04/26 17:34:26 fastreid.evaluation.evaluator]: Inference done 11/24. 0.3193 s / batch. ETA=0:00:04

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/117433887-95350a80-af5e-11eb-8d12-4a665f2b8714.png)

**Comment by JR-Wang** [comment]
感谢您的回复。我后来发现虽然减小输入的尺寸，模型推理时间没有发生太大变化，但是gpu的利用率是大幅下降，说明计算量是降低的，推测是一些instance norm的操作使得压缩输入尺寸之后，gpu利用率上不去了。
您说的torch.cuda.synchronize()，我试了一下，不会解决模型推理时间不随输入尺寸变化而改变的问题。
