### ISSUE TITLE
多类别训练

### ISSUE THREAD

**Issue by JiangWeiHn** [JDAI-CV/fast-reid#478]
我现在有一个多类别的数据集，想训练目标跟踪模型，请问如何定义数据集的格式？数据集中有一部分需要目标跟踪，一部分类别不需要跟踪。

**Comment by L1aoXingyu** [comment]
可以在读取数据的时候，直接保留需要跟踪的类别。

**Comment by JiangWeiHn** [comment]
好的 谢谢
