### ISSUE TITLE
when following your steps to execute trt_inference.py, broadcast issue appears.

### ISSUE THREAD

**Issue by GeLink9999** [JDAI-CV/fast-reid#480]
![image](https://user-images.githubusercontent.com/56419000/116520030-c54c3000-a904-11eb-9a78-3b120ee61251.png)
Please help me out. Thanks

**Comment by GeLink9999** [comment]
Who can help me out? Thanks a lot

**Comment by L1aoXingyu** [comment]
The batch size in inference and conversion needs to be consistent.
