### ISSUE TITLE
demo doesn't work now after update

### ISSUE THREAD

**Issue by oceanlvr** [JDAI-CV/fast-reid#481]
## ❓ How to do something using fastreid

Describe what you want to do, including:

1. what inputs you will provide, Chinese blog link which located in README.md is not available https://l1aoxingyu.github.io/blogpages/reid/2020/05/29/fastreid.html. plz update it.

2. what outputs you are expecting: update README.md

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/JDAI-CV/fast-reid/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to fastreid, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by oceanlvr** [comment]
Chinese blog link which located in `README.md`  is not available `https://l1aoxingyu.github.io/blogpages/reid/2020/05/29/fastreid.html`.

**Comment by L1aoXingyu** [comment]
Check this: https://l1aoxingyu.github.io/blogpages/reid/fastreid/2020/05/29/fastreid.html

**Comment by oceanlvr** [comment]
THANKS
