### ISSUE TITLE
unable to reproduce the baseline results with 4 gpus

### ISSUE THREAD

**Issue by sijun-zhou** [JDAI-CV/fast-reid#483]
I use 4 GPUs to reproduce the results of bagtricks_R50.yml. 
Below is my results:
![image](https://user-images.githubusercontent.com/39326729/117439452-6ec69d80-af65-11eb-8f1a-48c90d319ae3.png)

Below is the baseline in model zone:
![image](https://user-images.githubusercontent.com/39326729/117439094-fbbd2700-af64-11eb-9d1e-4c686a397758.png)

top1 is **1 point lower** than the baseline, and map is **2 points lower** than the baseline

I just download the newest repo of fastreid today and use 4 GPUs to train. 
**I only change one thing is that  IMS_PER_BATCH from 64 to 256**

Below is my config:

![image](https://user-images.githubusercontent.com/39326729/117440108-383d5280-af66-11eb-8c95-6185a390fbb1.png)

![image](https://user-images.githubusercontent.com/39326729/117440175-48553200-af66-11eb-815d-b4fd4b991ca9.png)

![image](https://user-images.githubusercontent.com/39326729/117440210-560ab780-af66-11eb-89db-1b3799c4a290.png)

could any give me any advice to reproduce the results?
@L1aoXingyu  could you plz give me some advice?
Thanks in advance!

**Comment by L1aoXingyu** [comment]
If you want to train the model with multiple GPUs, you need to increase the batch size and lr with linear scaling. I see you have increased the batch size to 256, then you need to increase the lr.

BTW, if you increase batch size, you will get a little bit worse result than reported.

**Comment by sijun-zhou** [comment]
> If you want to train the model with multiple GPUs, you need to increase the batch size and lr with linear scaling. I see you have increased the batch size to 256, then you need to increase the lr.
> 
> BTW, if you increase batch size, you will get a little bit worse result than reported.

@L1aoXingyu 
I have tried scaling the both batch size and lr to 4 times comparing to default. That is batch size = 256 and lr = 0.0014. But got a bit worse result than the results above.  see the below. All the other settings have not changed.

![image](https://user-images.githubusercontent.com/39326729/117528179-763c8400-b003-11eb-91a5-7d953b4ab146.png)

Below is my config. I also upload the whole training log. 

![image](https://user-images.githubusercontent.com/39326729/117528263-eba85480-b003-11eb-98d1-c5ae0573aea5.png)
![image](https://user-images.githubusercontent.com/39326729/117528283-fcf16100-b003-11eb-8cfd-ea4b22dca1b1.png)
![image](https://user-images.githubusercontent.com/39326729/117528300-12ff2180-b004-11eb-93e4-a5e3ca2450eb.png)

**Comment by sijun-zhou** [comment]
@L1aoXingyu 
I also have upload my training log this time. Please have a look when you have time. Thanks.

[log.txt](https://github.com/JDAI-CV/fast-reid/files/6445310/log.txt)

**Comment by sijun-zhou** [comment]
And I find when evaluation, only three gpus are used. But training, all 4 gpus are used.

![image](https://user-images.githubusercontent.com/39326729/117532381-dccc9c80-b019-11eb-91ed-42ac85f6fe48.png)

**Comment by L1aoXingyu** [comment]
When evaluating the results, the main process is computing CMC and mAP, and the other processes are waiting after feature extraction. The 100% GPU-Util isn't meaning it's used.

**Comment by sijun-zhou** [comment]
> When evaluating the results, the main process is computing CMC and mAP, and the other processes are waiting after feature extraction. The 100% GPU-Util isn't meaning it's used.

ok. got it. thank you.
BTW.  @L1aoXingyu   any solutions for me to train with 4gpus? I have already upload my results and my whole train log in the uppper floors follow your suggestions before. It is trained with 4 GPUs and batch size = 256 and lr = 0.0014. But I got even poorer results with the config than the batch size = 256 and lr =0.00035. 
And all the above two kinds of settings got poorer results than the baseline in the model zone.

Thanks in advance!

**Comment by sijun-zhou** [comment]
> When evaluating the results, the main process is computing CMC and mAP, and the other processes are waiting after feature extraction. The 100% GPU-Util isn't meaning it's used.

ok. got it. thank you.
BTW. @L1aoXingyu  any solutions for me to train with 4gpus? I have already upload my results and my whole train log named **log.txt** in the uppper floors follow your suggestions before. It is trained with **4 GPUs and batch size = 256 and lr = 0.0014**. But I got even poorer results with the config than the batch size = 256 and lr =0.00035.

And all the above two kinds of settings got poorer results than the baseline in the model zone.

Thanks in advance!

**Comment by L1aoXingyu** [comment]
Change lr to 0.0007 and try it again?

**Comment by sijun-zhou** [comment]
@L1aoXingyu , 
change lr to 0.0007, but got worser results. **top1=91.6, mAP=79.52**
I have also upload my train log named **log_lr0.0007.txt**
Is there anything related to code need to change when using mutl gpus to train? like sync_bn, blur, blur, blur, etc

[log_lr0.0007.txt](https://github.com/JDAI-CV/fast-reid/files/6449115/log_lr0.0007.txt)

**Comment by L1aoXingyu** [comment]
I will try it later.

**Comment by sijun-zhou** [comment]
@L1aoXingyu  i got nearly the same results as you posted. So, I close this issue.
