### ISSUE TITLE
如何在不更改任何参数的配置下，使用多GPU训练

### ISSUE THREAD

**Issue by duerwen** [JDAI-CV/fast-reid#487]
源码当中配置的IMS_PER_BATCH=64，我使用的服务器是单机多GPU的配置，每张卡显存是12G，在使用一块GPU配置下，使用默认的IMS_PER_BATCH=64显卡显存不够，请问我应该如何在多卡训练时，使用两块GPU，在默认的参数配置下，IMS_PER_BATCH=64,同样能够达到给定的baseline效果？

题外：参考您在其他问题中的回答，我了解到当相应的增加显卡个数时，要对应的调整batch的大小和lr，单卡训练中默认的batch=64，训练时由于我的显卡显存大小为12G，因此会显存不够用，同样设置为多GPU训练时，相应的将batch设置为128,同样会显存溢出，想问问我应该如何在两块GPU的情况下，将batch设置为64时，达到跟baseline中相似的结果

**Comment by L1aoXingyu** [comment]
抱歉这么久才回复，之前没看到这个 issue
使用目前的代码没有办法保证两卡使用 batchsize=64 能够复现单卡的结果，其中原因比较多，主要是 data sampler 和 BN 的问题，BN 可以通过改为 syncBN 来完成统计量的同步，但是 data sampler 就需要在代码上进行改动，比较麻烦
建议你使用 AMP 进行训练，这样显存可以减少，如果还是不能装的下，建议将 image size 改小，使用 128x256，在我们的实验中，128x384 提升其实比较微弱。
