### ISSUE TITLE
ONNX export utility BASE PATH setup issue

### ISSUE THREAD

**Issue by viyer-research** [JDAI-CV/fast-reid#491]
I wanted to check if I am doing anything wrong with the onnx export tool as I need to export the VeRi pre-trained model from PyTorch->onnx-->others. I have downloaded the two files from the pretrained model zoo for VeRi baseline, sbs_R50-ibn.yml and veri_sbs_R50-ibn.pth. I have copied the model files into the Download folder. I run the onnx_export.py, and I get an error due to an incorrect path. Let me know if the files need to be in a specific directory, so I am attaching the screenshot. I tied to see the code, and it may be due to get_cfg appending _BASE_ to the command-line options.
![image](https://user-images.githubusercontent.com/8236526/118866916-2170f700-b8a8-11eb-9e3d-8ddfdee975ed.png)

Let me know if you need anything from me and I am following the example syntax provided in the help page:

python onnx_export.py --config-file root-path/bagtricks_R50/config.yml --name baseline_R50 --output outputs/onnx_model --opts MODEL.WEIGHTS root-path/logs/market1501/bagtricks_R50/model_final.pth

**Comment by young169** [comment]
> I wanted to check if I am doing anything wrong with the onnx export tool as I need to export the VeRi pre-trained model from PyTorch->onnx-->others. I have downloaded the two files from the pretrained model zoo for VeRi baseline, sbs_R50-ibn.yml and veri_sbs_R50-ibn.pth. I have copied the model files into the Download folder. I run the onnx_export.py, and I get an error due to an incorrect path. Let me know if the files need to be in a specific directory, so I am attaching the screenshot. I tied to see the code, and it may be due to get_cfg appending _BASE_ to the command-line options.
> ![image](https://user-images.githubusercontent.com/8236526/118866916-2170f700-b8a8-11eb-9e3d-8ddfdee975ed.png)
> 
> Let me know if you need anything from me and I am following the example syntax provided in the help page:
> 
> python onnx_export.py --config-file root-path/bagtricks_R50/config.yml --name baseline_R50 --output outputs/onnx_model --opts MODEL.WEIGHTS root-path/logs/market1501/bagtricks_R50/model_final.pth

sbs_R50-ibn.yml requires Base-SBS.yml, I suppose you just moved a single yml file to your specific path rather than the whole 'configs' folder.

**Comment by viyer-research** [comment]
Thanks, I was able to get the ONNX file exported. Any plans to document and support depthai models located at this site: http://luxonis.com:8080/
