### ISSUE TITLE
train osnet failed

### ISSUE THREAD

**Issue by Royzon** [JDAI-CV/fast-reid#494]
My osnet config is:  
_BASE_: Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_osnet_backbone
    DEPTH: x0_25
  
  HEADS:
    EMBEDDING_DIM: 256

INPUT:
  DO_AUTOAUG: True

I got RuntimeError: Given groups=1, weight of size [256, 2048, 1, 1], expected input[64, 128, 1, 1] to have 2048 channels, but got 128 channels instead

How to configure osnet correctly？

**Comment by L1aoXingyu** [comment]
Change backbone feature dim as following
```
MODEL:
  BACKBONE:
    FEAT_DIM: 128	
```

**Comment by Royzon** [comment]
Thanks very much, it works!
