### ISSUE TITLE
The network structure of MGN is inconsistent with the official

### ISSUE THREAD

**Issue by AlphaPlusTT** [JDAI-CV/fast-reid#505]
In the three branches of MGN, one branch is stride 2, and the other two branches are stride 1. However, in the implementation of this project, the stride of the three branches are all 1 (the default LAST_STRIDE in Base-bagtricks.yml is 1);
I have done a simple experiment, and the stride has no obvious effect on the performance; But if all the stride is set to 1, can we use deepcopy to make the [code](https://github.com/JDAI-CV/fast-reid/blob/4f90197336805381e89bfb1bef14262dbcaf4077/fastreid/modeling/meta_arch/mgn.py#L114) more concise? I believe the code is written to set different strides for different branches. If you don't need to set different strides, you can use deepcopy directly.

**Comment by L1aoXingyu** [comment]
Actually, we just set the `last_stride` to 1, but we need to allow others can set it differently.
