### ISSUE TITLE
ModuleNotFoundError: No module named 'fastattr.data_build'

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/fast-reid#517]
CUDA_VISIBLE_DEVICES=1,2 python3 projects/FastAttr/train_net.py --config-file projects/FastAttr/configs/pa100.yml --num-gpus 2

Traceback (most recent call last):
  File "projects/FastAttr/train_net.py", line 20, in <module>
    from fastattr import *
  File "/home/work/deep_learning/reid/fast-reid/projects/FastAttr/fastattr/__init__.py", line 9, in <module>
    from .data_build import build_attr_train_loader, build_attr_test_loader
ModuleNotFoundError: No module named 'fastattr.data_build'

**Comment by L1aoXingyu** [comment]
You can just simply delete this line to fix this problem. 
```
from .data_build import build_attr_train_loader, build_attr_test_loader
```

**Comment by deep-practice** [comment]
对于既有二分类属性，又有多分类属性的数据集，只能在计算loss的时候分别计算吗？
