### ISSUE TITLE
TensorRT inference error: 'INVALID_ARGUMENT: getPluginCreator could not find plugin InstanceNormalization_TRT version 1'

### ISSUE THREAD

**Issue by young169** [JDAI-CV/fast-reid#518]
## ❓ How to do something using fastreid

I want to train on cuda:4 using "python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cuda:4"", but an error occured: "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:4!".  And I'm not sure if somewhere fixed to be cuda:0?

**Comment by L1aoXingyu** [comment]
You can set the environment variables, for example
```
CUDA_VISIBLE_DEVICES=4 python3 ..
```

**Comment by young169** [comment]
> You can set the environment variables, for example
> 
> ```
> CUDA_VISIBLE_DEVICES=4 python3 ..
> ```

Thank you for your reply! It works.

**Comment by young169** [comment]
And I got some errors during transfering onnx to tensorrt engine. So what are the versions of cuda and TensorRT for you? I didn't find your specifications.

**Comment by young169** [comment]
> You can set the environment variables, for example
> 
> ```
> CUDA_VISIBLE_DEVICES=4 python3 ..
> ```

And I'm now facing some deployment problems. May I ask for what versions of TensorRT and CUDA you're using?

**Comment by nanhui69** [comment]
when i run it on tx2 ，errors happens that "no CUDA-capable device is detected"
