### ISSUE TITLE
baseline文件中from_config返回的参数是如何传递给__init__函数的呢

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/fast-reid#522]

**Comment by xmy0916** [comment]
@deep-practice 你可以看@configurable代码里这个装饰器的注释说明，有讲解。或者在pycharm里面ctrl + b点这个装饰器可以跳到对应的代码，这个装饰器可以修饰一个类的初始化函数并且在初始化的时候和初始化函数一起调用。
