### ISSUE TITLE
相同配置多卡训练和单卡训练结果评估差别很大

### ISSUE THREAD

**Issue by xmy0916** [JDAI-CV/fast-reid#523]
感谢你们的工作~很好的框架。
我在使用的时候相同的配置，单卡训练rank1可以达到98多，换成四卡训练的时候rank1就一直在35左右震荡。一点不同的地方，单卡因为显存不够训练的batchsize是128，四卡是256。

目前我觉得可能的原因，因为我的数据集没有camera id这一项参数，所以我自己构造数据集的时候将训练集、query、gallery的camer id参数都设成了不一样的值（没有一个相同）。请问这样会有问题吗？

感谢~

**Comment by xmy0916** [comment]
我这边测试了用多卡训的保存的模型，进行单卡评估发现结果正确了...根据现象有点怀疑是多卡训练时候评估代码哪里有bug？

**Comment by hushunda** [comment]
我也发现了这个bug。然后测试market1501，评估程序在多gpu的时候，又没有问题

**Comment by xmy0916** [comment]
> 我也发现了这个bug。然后测试market1501，评估程序在多gpu的时候，又没有问题

应该是跟摄像头的id有关，你是不是每张图都是不同的摄像头id？

**Comment by L1aoXingyu** [comment]
要不你们按照 market 的格式去配置数据集，我怀疑是你们自己构建数据的时候出的问题，比如多卡会起多个进程，每个进程都会读一次完整的数据，如果每个进程获得数据集的顺序不同，那么多卡测试就会出问题

**Comment by hushunda** [comment]
> > 我也发现了这个bug。然后测试market1501，评估程序在多gpu的时候，又没有问题
> 
> 应该是跟摄像头的id有关，你是不是每张图都是不同的摄像头id？

这个试过，也试过按照正常camera id来配置，都会出现相同的问题，但是每个图像设置不同的id，应该不会导致整个问题吧

**Comment by hushunda** [comment]
> 要不你们按照 market 的格式去配置数据集，我怀疑是你们自己构建数据的时候出的问题，比如多卡会起多个进程，每个进程都会读一次完整的数据，如果每个进程获得数据集的顺序不同，那么多卡测试就会出问题

我自己的数据集就是按照market重构的dataset😓

**Comment by L1aoXingyu** [comment]
读数据的代码一样吗？

**Comment by hushunda** [comment]
> 要不你们按照 market 的格式去配置数据集，我怀疑是你们自己构建数据的时候出的问题，比如多卡会起多个进程，每个进程都会读一次完整的数据，如果每个进程获得数据集的顺序不同，那么多卡测试就会出问题

我没有修改读取数据的程序，在添加了fasetreid/data/dataset下面添加了自己的数据
![image](https://user-images.githubusercontent.com/21358656/125579201-854f257d-5653-4183-91de-e91d26c9119d.png)

只是重写了数据的索引

**Comment by hushunda** [comment]
找到bug了。我的问题是在进行id map的时候，按照了set(idname)顺序来的，没有对它排序，导致每个gpu中顺序不一致，导致id设置错误

**Comment by L1aoXingyu** [comment]
> 找到bug了。我的问题是在进行id map的时候，按照了set(idname)顺序来的，没有对它排序，导致每个gpu中顺序不一致，导致id设置错误

赞
