### ISSUE TITLE
使用提供的yml配置文件跑VeRi数据集出现NAN问题

### ISSUE THREAD

**Issue by ChristmasStory** [JDAI-CV/fast-reid#529]
问题：
[07/06 15:36:16 fastreid.utils.events]:  eta: 1:24:10  epoch/iter: 5/3539  total_loss: 41.46  loss_cls: 41.4
ERROR [07/06 15:36:19 fastreid.engine.train_loop]: Exception during training:

FloatingPointError: Loss became infinite or NaN at iteration=3555!
loss_dict = {'loss_cls': nan, 'loss_triplet': nan}
未曾更改配置文件

**Comment by L1aoXingyu** [comment]
你用的是多卡还是单卡？如果使用多卡需要修改配置文件

**Comment by siyuch-fdu** [comment]
> 你用的是多卡还是单卡？如果使用多卡需要修改配置文件

请问多卡训练需要如何修改配置文件使得loss不会出现nan

**Comment by L1aoXingyu** [comment]
比如增加 batch size，调一下学习率
