### ISSUE TITLE
Training fast-reid on custom dataset

### ISSUE THREAD

**Issue by VAIBHAVPATEL97** [JDAI-CV/fast-reid#530]
Hello,
I would like to retrain the fast-reid model on custom dataset can you please tell me is there any documentation available about this process?. Thankyou.

**Comment by L1aoXingyu** [comment]
You can refer to this documentation https://github.com/JDAI-CV/fast-reid/issues/220 for your own dataset preparation. Then you can retrain the model on your custom dataset.

**Comment by VAIBHAVPATEL97** [comment]
Hello @L1aoXingyu , Thank you for redirecting me. If you don't mind, I wanted to know whether or not fast Reid store any part of our dataset?.  Because I want to train the model on a proprietary dataset and the author does not want to share the dataset. I hope you understand.

**Comment by L1aoXingyu** [comment]
Fastreid will **never** ever store any part of the datasets.

**Comment by VAIBHAVPATEL97** [comment]
@L1aoXingyu Thank you for the confirmation.
