### ISSUE TITLE
ONNX export the cls_layer

### ISSUE THREAD

**Issue by weilli** [JDAI-CV/fast-reid#531]
Model: R50
I want the class layer.
But I find the onnx_output  .npy files are the 2048dim.(as the readme.txt procedures)
I need the onnx version in class_num. What should I do?
Thanks a lot!

**Comment by L1aoXingyu** [comment]
Maybe you can change the `EmbeddingHead` to `ClasHead`, then you can get the classifier layer.

**Comment by weilli** [comment]
Thanks a lot. I have solved the problem by following your instructions.
