### ISSUE TITLE
Tutorial to run the fast-reid

### ISSUE THREAD

**Issue by VAIBHAVPATEL97** [JDAI-CV/fast-reid#532]
Hello, 
I am getting really confused about where to start working with this repo. Is there any step-by-step tutorial that can be used as a reference to run this repo?. Any help is highly appreciated. Thanks.

**Comment by L1aoXingyu** [comment]
Check here
https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md
