### ISSUE TITLE
Detected invalid timing cache, setup a local cache instead

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#537]
docker ： nvcr.io/nvidia/pytorch:21.05-py3
Driver Version: 470.57.02   
CUDA Version: 11.4
TensorRT 7.3   TensorRT 8
 model ：https://github.com/JDAI-CV/fast-reid/blob/master/MODEL_ZOO.md#veri-baseline

let the VeRi  SBS  model to trt, it fail.
But use the Market1501 SBS ,it success

Both of VeRi and Market1501 are differtent architecture？

all back to non-int8 implementation for any layer consuming or producing given tensor        trt_utils.cpp:252
   WARN         TRT: Detected invalid timing cache, setup a local cache instead        trt_utils.cpp:252
 WARN         TRT: No implementation of layer 417 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.        trt_utils.cpp:252
 WARN         TRT: No implementation of layer 419 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.        trt_utils.cpp:252
	WARN 	TRT: Detected invalid timing cache, setup a local cache instead	trt_utils.cpp:252
WARN 	TRT: No implementation of layer 417 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.	trt_utils.cpp:252
WARN 	TRT: No implementation of layer 419 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.	trt_utils.cpp:252
ERROR	TRT: instanceNormalizationPlugin.cu (292) - Cudnn Error in enqueue: 3 (CUDNN_STATUS_BAD_PARAM)	trt_utils.cpp:251

**Comment by L1aoXingyu** [comment]
This error is about instanceNorm which is not supported in tensorRT.

**Comment by alicera** [comment]
1.
How can I solve it ？
Do you have the advance？

2.
If I change the backbone without ibn, is it better

**Comment by L1aoXingyu** [comment]
> How can I solve it ？
> Do you have the advance？
> 
> 
> If I change the backbone without ibn, is it better

You can refer to `projects/fastRT` which has instance norm  plugin. Or you can just use backbone without ibn.
