### ISSUE TITLE
Warning: ONNX Preprocess - Removing mutation from node aten::sub_ on block input: 'batched_inputs.1'. This changes graph semantics.

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#538]
pytorch 21.05
onnx1.6.0
How to solveit 

 python tools/deploy/onnx_export.py --config-file configs/VeRi/sbs_R50-ibn.yml --name veri_sbs_R50 --output ouputs/ --opts MODEL.WEIGHTS logs/veri/sbs_R50-ibn/model_0000.pth 

Warning: ONNX Preprocess - Removing mutation from node aten::sub_ on block input: 'batched_inputs.1'. This changes graph semantics.

**Comment by Meet20230712** [comment]
Did you solve this issue? This happen to me at the same time..
