### ISSUE TITLE
unable to find META_ARCHITECTURE DistillerOverhaul

### ISSUE THREAD

**Issue by sijun-zhou** [JDAI-CV/fast-reid#540]
Hi @L1aoXingyu  @wangguanan , 
I'm reading the codes of fast distill. But I cannot find the meta_architecture of 'DistillerOverhaul' under the folder fastreid/modeling/meta_arch/. 
Is there any thing missing here? or do i go into the wrong folder to find the 'DistillerOverhaul'?

In the readme of 'fastdistill', I find that there is a 'DistillerOverhaul'.

loss+overhaul distillation
python3 projects/FastDistill/train_net.py \
--config-file projects/FastDistill/configs/kd-sbs_r101ibn-sbs_r34.yaml \
--num-gpus 4 \
**_MODEL.META_ARCHITECTURE DistillerOverhaul_**
KD.MODEL_CONFIG '("projects/FastDistill/logs/dukemtmc/r101_ibn/config.yaml",)' \
KD.MODEL_WEIGHTS '("projects/FastDistill/logs/dukemtmc/r101_ibn/model_best.pth",)'

Thanks!

**Comment by L1aoXingyu** [comment]
Check here https://github.com/JDAI-CV/fast-reid/blob/7e652fea2ac76db27170ce8ab294724ddfe8b716/projects/FastDistill/fastdistill/overhaul.py#L59
