### ISSUE TITLE
请问如何在FastRetri任务里使用repvgg或vision_transformer的backbone来训练模型吗？

### ISSUE THREAD

**Issue by xgyyao** [JDAI-CV/fast-reid#545]
我现在只能使用base-image_retri.yml 的resnet backbone来训练FastRetri任务，如何使用其他的backbone呢？

**Comment by L1aoXingyu** [comment]
你把配置文件里面的 backbone 名字换掉就可以了，具体的名字可以去这里看
https://github.com/JDAI-CV/fast-reid/blob/7e652fea2ac76db27170ce8ab294724ddfe8b716/fastreid/modeling/backbones/repvgg.py#L254-L260
