### ISSUE TITLE
trt_inference 流程代码 放到deepstream 流程中 内存爆炸

### ISSUE THREAD

**Issue by ycy1164656** [JDAI-CV/fast-reid#546]
请问这是什么原因导致的呢？

**Comment by L1aoXingyu** [comment]
是不是 deepstream 里面起得模型太多了，你有测过单独的 trt_inference 代码会有内存泄露吗

**Comment by ycy1164656** [comment]
> 是不是 deepstream 里面起得模型太多了，你有测过单独的 trt_inference 代码会有内存泄露吗

确实是deepstream内存占用太多挤压后续trt流程了
