### ISSUE TITLE
visualize_result

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#547]
python demo/visualize_result.py --config-file configs/Market1501/bagtricks_R50.yml --vis-label

/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "demo/visualize_result.py", line 105, in <module>
    test_loader, num_query = build_reid_test_loader(cfg, dataset_name=args.dataset_name)
  File "/work/Pictures/REID/fast-reid/./fastreid/config/config.py", line 264, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/config/config.py", line 292, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/data/build.py", line 111, in _test_loader_from_config
    assert dataset_name is not None, "dataset_name must be explicitly passed in when test_set is not provided"
AssertionError: dataset_name must be explicitly passed in when test_set is not provided

**Comment by alicera** [comment]
python demo/visualize_result.py --vis-label --config-file logs/market1501/bagtricks_R50/config.yaml --dataset-name 'Market1501' --output logs/out --opts MODEL.WEIGHTS market_bot_R50.pth
It work fine.

Where is the distance value the decide the object similarity ?

**Comment by L1aoXingyu** [comment]
It will show the distance on the top of image.
