### ISSUE TITLE
How to interpret the output of the baseline.inference

### ISSUE THREAD

**Issue by chenscottus** [JDAI-CV/fast-reid#548]
Hello,

     I eventually run the  FastRT project in fast-reid, and the output :
[new 2.txt](https://github.com/JDAI-CV/fast-reid/files/6965575/new.2.txt)

    I expect the model will give me and ID (int) like other re-id model such openvino. How ever, it gives me a lot of numbers, and I went through the whole site, the paper, the doc, I cannot understand the output and know not how to use them.

    Or how can i get an ID like other re-id model when I get a person image to the model?

     Many thanks!

-Scott

**Comment by TCHeish** [comment]
Hi, 
Those numbers are representing the input person's embedding features. 
What you intend to get is called retrieval, you still have to calculate the feature embedding similarity between query image and dataset by yourself after get the numbers.
Currently FastRT haven't support yet. 
Thanks for asking this, I'm considering to add this function for demonstrate this. :)

**Comment by chenscottus** [comment]
Got it. Could you please show us how to calculate the the feature embedding similarity between those images in FastRT? Thanks!

**Comment by chenscottus** [comment]
Thanks !  I will do it by myself. -Scott
