### ISSUE TITLE
Assertion failed: tensors.count(input_name)

### ISSUE THREAD

**Issue by grapefruitL** [JDAI-CV/fast-reid#549]
你好 我在使用onnx转trt模型时出错
指令如下：

> python trt_export.py --name baseline_R50 --output outputs/trt_model --mode fp32 --batch-size 8 --height 256 --width 256 --onnx-model outputs/onnx_model/baseline_R50.onnx

报错如下：

> [08/11 07:35:31 trt_export]: Loading ONNX file from path outputs/onnx_model/baseline_R50.onnx...
[08/11 07:35:31 trt_export]: Beginning ONNX file parsing
[08/11 07:35:31 trt_export]: In node 0 (importModel): INVALID_GRAPH: Assertion failed: tensors.count(input_name)
[08/11 07:35:31 trt_export]: Completed parsing of ONNX file.
[08/11 07:35:31 trt_export]: Building an engine from file outputs/onnx_model/baseline_R50.onnx; this may take a while...
[TensorRT] ERROR: Network must have at least one output
[08/11 07:35:31 trt_export]: Create engine successfully!
[08/11 07:35:31 trt_export]: Saving TRT engine file to path outputs/trt_model/baseline_R50.engine
Traceback (most recent call last):
  File "trt_export.py", line 166, in <module>
    onnx2trt(onnx_file_path, engineFile, args.mode, int8_calibrator=int8_calib)
  File "trt_export.py", line 150, in onnx2trt
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

onnx模型已经经过测试，和torch输出一致
我使用的原始模型是你的预训练模型：veriwild_bot_R50-ibn.pth
tensorrt版本是6.0.1.8
python各库版本是：

> absl-py                0.11.0      
appdirs                1.4.3       
attrs                  19.3.0      
cachetools             4.2.0       
certifi                2020.12.5   
chardet                4.0.0       
cycler                 0.10.0      
Cython                 0.29.21     
cython-bbox            0.1.3       
DCNv2                  0.1         /alg/src/dcnv2
decorator              4.4.1       
faiss                  1.5.3       
faiss-cpu              1.7.1.post2 
faiss-gpu              1.6.3       
filelock               3.0.12      
flake8                 3.8.3       
flake8-import-order    0.18.1      
future                 0.18.2      
gdown                  3.13.0      
google-auth            1.24.0      
google-auth-oauthlib   0.4.2       
grpcio                 1.35.0      
idna                   2.10        
importlib-metadata     3.4.0       
iniconfig              1.0.1       
joblib                 1.0.0       
kiwisolver             1.1.0       
lap                    0.4.0       
llvmlite               0.36.0      
Mako                   1.1.0       
Markdown               3.3.3       
MarkupSafe             1.1.1       
matplotlib             3.3.2       
mccabe                 0.6.1       
more-itertools         8.4.0       
motmetrics             1.2.0       
numba                  0.53.1      
numpy                  1.19.5      
oauthlib               3.1.0       
opencv-python          4.5.1.48    
packaging              20.4        
pandas                 1.0.3       
Pillow                 8.1.0       
pip                    19.3.1      
pluggy                 0.13.1      
progress               1.5         
protobuf               3.14.0      
py                     1.9.0       
py-cpuinfo             7.0.0       
pyasn1                 0.4.8       
pyasn1-modules         0.2.8       
pycocotools            2.0.0       
pycodestyle            2.6.0       
pycuda                 2019.1.2    
pyflakes               2.2.0       
pyparsing              2.4.2       
pyquaternion           0.9.9       
PySocks                1.7.1       
pytest                 6.0.1       
pytest-benchmark       3.2.3       
python-dateutil        2.8.0       
pytools                2019.1.1    
pytz                   2020.1      
PyYAML                 5.4.1       
requests               2.25.1      
requests-oauthlib      1.3.0       
rsa                    4.6         
scikit-learn           0.19.2      
scipy                  1.5.4       
setuptools             42.0.2      
six                    1.15.0      
sklearn                0.0         
tabulate               0.8.9       
tensorboard            2.4.0       
tensorboard-plugin-wit 1.7.0       
tensorboardX           2.2         
tensorrt               6.0.1.8     
termcolor              1.1.0       
threadpoolctl          2.1.0       
toml                   0.10.1      
torch                  1.6.0       
torchsummary           1.5.1       
torchvision            0.7.0       
tqdm                   4.40.2      
typing-extensions      3.7.4.3     
urllib3                1.26.4      
Werkzeug               1.0.1       
wheel                  0.33.6      
xmltodict              0.12.0      
yacs                   0.1.8       
zipp                   3.4.0

**Comment by L1aoXingyu** [comment]
你使用的模型包含 ibn 吗？如果包含你可以先去掉这个部分然后再转 trt 看看有没有问题，如果没有问题，说明是 ibn 这个部分的问题

**Comment by together0** [comment]
我也报了这个错，然后我换了一个版本。
cuda : 10.2
cudnn: 7.6.5
tensorrt : 7.0.0.11
onnx : 1.6.0
结果就可以了，所以可能是版本问题吧

**Comment by nanhui69** [comment]
> 我也报了这个错，然后我换了一个版本。
> cuda : 10.2
> cudnn: 7.6.5
> tensorrt : 7.0.0.11
> onnx : 1.6.0
> 结果就可以了，所以可能是版本问题吧

修改了哪一个版本呢？
