### ISSUE TITLE
How to export a TRT model with implicit batch size? (rather than explicit batch size)

### ISSUE THREAD

**Issue by JosephAssaker** [JDAI-CV/fast-reid#551]
## ❓ How to export a TRT model with implicit batch size? (rather than explicit batch size)

Describe what you want to do, including:

Currently, when exporting a pytorch model to ONNX and then to TRT, the TRT engine is generated with an EXPLICIT batch size. This is causing me several issues when trying to integrate the model in my pipeline. Would anyone know how to address that?

NOTE:

For reference, I have tested exporting the SBS R101 model using the `onnx_export.py` followed by `trt_export.py`. Also, the `trt_inference.py` works perfectly fine.

**Comment by L1aoXingyu** [comment]
You can check this issue about dynamic batch https://github.com/NVIDIA/TensorRT/issues/976
