### ISSUE TITLE
Purpose of doing (-99999999.) * (1 - is_pos) in circle loss

### ISSUE THREAD

**Issue by twotwoiscute** [JDAI-CV/fast-reid#557]
Hi,while I am reading the code of circle loss ,everything makes sense to me until this line ,the link I show below : 
https://github.com/JDAI-CV/fast-reid/blob/ced654431be28492066f4746d23c1ff89d26acbd/fastreid/modeling/losses/circle_loss.py#L38
I wonder why we need to add ` (-99999999.) * (1 - is_pos)`  after `- gamma * alpha_p * (s_p - delta_p)` .Thanks!!

**Comment by L1aoXingyu** [comment]
明天回复你

**Comment by twotwoiscute** [comment]
> 明天回复你
好的，期待您的回覆

**Comment by twotwoiscute** [comment]
@L1aoXingyu 好的期待您的回复
