### ISSUE TITLE
inter_channels of Non_Local

### ISSUE THREAD

**Issue by howieraem** [JDAI-CV/fast-reid#558]
Why is the inter_channels in Non_local module 1? Isn't it supposed to be in_channels / 2 according to the original implementation?
[code](https://github.com/JDAI-CV/fast-reid/blob/master/fastreid/layers/non_local.py#L14)

**Comment by L1aoXingyu** [comment]
Yes, you are right. But I found there is no performance gain if setting to be `in_channels/2`.
