### ISSUE TITLE
About training ViT on Market1501

### ISSUE THREAD

**Issue by stoneyang** [JDAI-CV/fast-reid#559]
I've trained the transformer-based model as shipped with the code, it seems that there's nothing outperforming the CNN models?  Correct me if I were wrong. 

```
[08/18 15:07:26 fastreid.evaluation.testing]: Evaluation results in csv format:
| Dataset    | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:-----------|:---------|:---------|:----------|:------|:-------|:---------|
| Market1501 | 94.12    | 98.04    | 99.05     | 86.19 | 62.11  | 90.16    |
```

```
  | Rank-1 | Rank-5 | Rank-10 | mAP | mINP | metric |
|:-----------|:---------|:---------|:----------|:------|:-------|:---------|
|R50 | 94.45 | 98.16 | 98.78 | 85.08 | 56.78 | 89.76 |
|R50-ibn | 95.07 | 98.37 | 99.05 | 86.82 | 61.06 | 90.94 |
|R101-ibn | 95.58 | 98.43 | 99.08 | 88.20 | 65.34 | 91.89 |
|S50 | 94.77 | 98.31 | 98.99 | 86.91 | 61.27 | 90.84 |
|ViT | 94.12 | 98.04 | 99.09 | 86.19 | 62.11 | 90.16 |
```

**Comment by L1aoXingyu** [comment]
Yes, I also found there is not much gain.

**Comment by genhao3** [comment]
> I've trained the transformer-based model as shipped with the code, it seems that there's nothing outperforming the CNN models? Correct me if I were wrong.
> 
> ```
> [08/18 15:07:26 fastreid.evaluation.testing]: Evaluation results in csv format:
> | Dataset    | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
> |:-----------|:---------|:---------|:----------|:------|:-------|:---------|
> | Market1501 | 94.12    | 98.04    | 99.05     | 86.19 | 62.11  | 90.16    |
> ```
> 
> ```
>   | Rank-1 | Rank-5 | Rank-10 | mAP | mINP | metric |
> |:-----------|:---------|:---------|:----------|:------|:-------|:---------|
> |R50 | 94.45 | 98.16 | 98.78 | 85.08 | 56.78 | 89.76 |
> |R50-ibn | 95.07 | 98.37 | 99.05 | 86.82 | 61.06 | 90.94 |
> |R101-ibn | 95.58 | 98.43 | 99.08 | 88.20 | 65.34 | 91.89 |
> |S50 | 94.77 | 98.31 | 98.99 | 86.91 | 61.27 | 90.84 |
> |ViT | 94.12 | 98.04 | 99.09 | 86.19 | 62.11 | 90.16 |
> ```

could you provide the configuration file for vit?
