### ISSUE TITLE
Plans for integration of TopDBNet with Fast Reid?

### ISSUE THREAD

**Issue by shreejalt** [JDAI-CV/fast-reid#561]
Hi 
Are there any plans for the integration of TopDBNet with FastReid?

**Comment by syh-hue** [comment]
> Hi
> Are there any plans for the integration of TopDBNet with FastReid?

Hi，if you want to do this work？I think that it may interesting and effective.

**Comment by shreejalt** [comment]
@syh-hue 
It would be a pleasure to do it
Yes I also feel that TopDBNet with present fast-reid augmentation and architectural design can improve the overall performance of TopDBNet
