### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by shreejalt** [JDAI-CV/fast-reid#562]
Hi @L1aoXingyu 
I wanted to do inference on PCU to get the time. But it does not happen if I change MODEL.DEVICE in the config file. 

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

I think somewhere it is going on cuda by default

Can you help it in this?

**Comment by L1aoXingyu** [comment]
Sorry for the late reply. Would you please show me the command you use?
