### ISSUE TITLE
Evaluation using DSR

### ISSUE THREAD

**Issue by shreejalt** [JDAI-CV/fast-reid#564]
Is the evaluation of DSR done on CPU?
Whenever I do the evaluation my whole 32 GB gets filled up

Do I need to change anything in the code or config file to du the inference on GPU?

Because I see in the code that you append the `.cpu().numpy()` features in `M = []` 
So my whole memory is getting filled up

**Comment by shreejalt** [comment]
I think there is a serious issue in the inference of PartiallReID
`DSREvaluation` is done on CPU which is disrupting the RAM. If you can optimize it , it would be of a great help

While evaluating the PartialReID training on big datasets like Market1501, it is impossible to do so

**Comment by xiaomingzhid** [comment]
Due to the GPU space limitation，it cannot save the spatial features. So we first save these spatial features in CPUs. And then compute DSR on GPUs by converting numpy to tensor.

**Comment by shreejalt** [comment]
@xiaomingzhid 
So we cant use the DSR features for big datasets?
I wanted to train and test the fast-reid PartialReID on Market1501 dataset

**Comment by xiaomingzhid** [comment]
We have tried experiments on large databases, there is no problem, you can try

**Comment by shreejalt** [comment]
My whole RAM gets filled up 32 G on Market1501?
Is there any hack you can suggest?

**Comment by xiaomingzhid** [comment]
Do your CPUs only have 32 G? Our CPUs have 216 G. If you want to test using DSR, you save the spatial features on hard disk or increase your cpu memory.

**Comment by shreejalt** [comment]
For calculcation I need to load the features in hard drive. So it will create the same issue right?
Is there any solution where I can use dsr in parts. i.e Get some chunks of spatial features and calculate it with query images

**Comment by xiaomingzhid** [comment]
Three suggestions you could try:
1. feature channel could be reduced to 512 (ours is 2048). But it may reduce the accuracy.
2. add sever CPU memory
3. save the gallery spatial features in hard disk and store these gallery features separately. If you want to use these spatial features, you can load them separately.

**Comment by shreejalt** [comment]
Thanks a lot @xiaomingzhid 
Do you have the results of PartialReID trained on Market1501 and tested on Market1501?
If you can just provide me the benchmark then it would be of a great help.

**Comment by xiaomingzhid** [comment]
You could find some useful results in this paper: https://openaccess.thecvf.com/content_ICCV_2019/papers/He_Foreground-Aware_Pyramid_Reconstruction_for_Alignment-Free_Occluded_Person_Re-Identification_ICCV_2019_paper.pdf.

**Comment by shreejalt** [comment]
@xiaomingzhid  Thanks a lot. 
I solved it with some small workaround as my use-case was pretty based on an only a small set of gallery images at the time of inference. 

Thanks again for your help. I am closing the issue
