### ISSUE TITLE
Visualize my own dataset(custom dataset)

### ISSUE THREAD

**Issue by SoheeKANG** [JDAI-CV/fast-reid#565]
Hello, I'm new to person re-identification and fast-reid.
I trained my custom dataset with fast-reid.

My custom dataset follows Market1501 naming convention.

like this
![image](https://user-images.githubusercontent.com/68429247/131763922-269a311b-ec32-4ed7-8c67-91e7f5588e4a.png)

so I used this command in docker environment

```
python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cuda:0"
```
and I got the weight, so I wanted visualize my own dataset.

like this

![show](https://user-images.githubusercontent.com/68429247/131764276-8d0871dc-c753-4103-94d5-ac8a1cd3e038.png)
(this is other re-id source's output)

but I got result of Market1501
![0](https://user-images.githubusercontent.com/68429247/131764369-9e510df3-6481-44f5-af37-07577b43aacf.jpg)
this is not my dataset, and I can't understand why this happens

I used this command for visualization

```
python .\demo\visualize_result.py --config-file .\configs\Market1501\bagtricks_R50.yml --dataset-name Market1501 --output .\logs\ --vis-label --opts MODEL.WEIGHTS .\logs\market1501\bagtricks_R50\model_final.pth
```

how can I visualize my own dataset?

**Comment by SoheeKANG** [comment]
I just confused. What I need was just copying my own dataset into market1501 folder

**Comment by Json0926** [comment]
have you solve this problom？

**Comment by SoheeKANG** [comment]
> have you solve this problom？

Yes. Just copy your own dataset into Market1501 folder

**Comment by mnnurilmi** [comment]
hi @SoheeKANG , is this problem solved? i mean, for evaluation, still return your default dataset or custom dataset?

**Comment by SoheeKANG** [comment]
@mnnurilmi Yes, I solved this problem. Visualized my custom dataset.

**Comment by mnnurilmi** [comment]
@SoheeKANG oh, i see, and where are the parts you fixed? where did you go wrong before?
