### ISSUE TITLE
Unable to produce the results of PartialReID Project

### ISSUE THREAD

**Issue by shreejalt** [JDAI-CV/fast-reid#568]
Hi, 
I tried using the PartialReID project but I was unable to reproduce the results that are mentioned in the README file. I reduced to BatchSize of 64 as I was training on only one GPU and apart from that there was no change in the `partial_market.yml` file. 

Can anyone help me with this?

**Comment by shreejalt** [comment]
Hi, 
Any one can help on this?

**Comment by L1aoXingyu** [comment]
@lingxiao-he

**Comment by shreejalt** [comment]
Hi, 
Any updates?
