### ISSUE TITLE
Configs about VehicheID dataset

### ISSUE THREAD

**Issue by CHENGY12** [JDAI-CV/fast-reid#57]
Hi, Thanks for your nice work.
Can you provide the configs of the vehiche reid datasets.

**Comment by L1aoXingyu** [comment]
We will upload vehicle reid training config next week.

**Comment by L1aoXingyu** [comment]
@CHENGY12 Hi, we have added config file, please check the [model zoo](https://github.com/JDAI-CV/fast-reid/blob/master/MODEL_ZOO.md#veri-baseline).

**Comment by CHENGY12** [comment]
Thank you very much for your rapid reply. It is very helpful for our works.

**Comment by Lucky-ZhiwenT** [comment]
Hello, could you please share the download link with PKU VehicleID? I have sent many emails to pkuml, but no response. Thanks a lot!
