### ISSUE TITLE
performance gap between single GPU and multi GPUs on SBS

### ISSUE THREAD

**Issue by YP-Liu** [JDAI-CV/fast-reid#573]
First of all,  thank u for ur great ReID open-source framework! I train the **SBS** on **single and 2 GPUs** on Market1501. The performance gap is really big. I'am quite confused. My configuration is as follows:

**single GPU:**
_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
MODEL:
  BACKBONE:
    PRETRAIN_PATH: ~/pretrained_models/resnet50-19c8e357.pth
  HEADS:
OUTPUT_DIR: logs/market1501/sbs_R50

**2 GPUs:**
_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
MODEL:
  BACKBONE:
    PRETRAIN_PATH: ~/pretrained_models/resnet50-19c8e357.pth
    NORM: SyncBN
  HEADS:
    NORM: SyncBN
OUTPUT_DIR: logs/market1501/sbs_R50_2gpu
the testing mAP is **88.16 vs 79.32**. Which is 85.91vs 86.73 on bagtricks.

**Comment by my462** [comment]
same experience on msmt17 dataset

**Comment by L1aoXingyu** [comment]
You need to change the batch size when you use multiple GPUs. For example, if you use 2 GPUs, you need to change the batch size from 64 to 128.

**Comment by YP-Liu** [comment]
> You need to change the batch size when you use multiple GPUs. For example, if you use 2 GPUs, you need to change the batch size from 64 to 128.

Do you mean that when use 2 GPUs, batch size should be 128 per GPU? In the above 2GPU configuration, it's 64 on both GPU.

**Comment by YP-Liu** [comment]
> You need to change the batch size when you use multiple GPUs. For example, if you use 2 GPUs, you need to change the batch size from 64 to 128.
In deed,  I use the code V1.0 and modify the code here from 'mini_batch_size = cfg.SOLVER.IMS_PER_BATCH // comm.get_world_size()' to 'mini_batch_size = cfg.SOLVER.IMS_PER_BATCH' to ensure that there are 64 imgs on both GPU. So I guess batch size may not be the problem.
