### ISSUE TITLE
执行tools/deploy/onnx_export.py出错

### ISSUE THREAD

**Issue by yanziwu621** [JDAI-CV/fast-reid#574]
执行下面代码，.pth转.onnx报错，
python3 tools/deploy/onnx_export.py --config-file configs/VERIWild/bagtricks_R50-ibn.yml --name baseline_R50 --output logs/veriwild/bagtricks_R50-ibn_with_pretrain_train_list1_AUGMIX/onnx_model --opts MODEL.WEIGHTS /logs/veriwild/bagtricks_R50-ibn_with_pretrain_train_list1_AUGMIX/model_final.pth
具体错误：
Traceback (most recent call last):
  File "tools/deploy/onnx_export.py", line 147, in <module>
    model = build_model(cfg)
  File "./fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "./fastreid/config/config.py", line 245, in wrapped
    init_func(self, **explicit_args)
  File "./fastreid/modeling/meta_arch/baseline.py", line 53, in __init__
    self.register_buffer('pixel_mean', torch.Tensor(pixel_mean).view(1, -1, 1, 1), False)
TypeError: register_buffer() takes 3 positional arguments but 4 were given

**Comment by ZhenpengChenCode** [comment]
遇到一样的错误，请问

> 执行下面代码，.pth转.onnx报错， python3 tools/deploy/onnx_export.py --config-file configs/VERIWild/bagtricks_R50-ibn.yml --name baseline_R50 --output logs/veriwild/bagtricks_R50-ibn_with_pretrain_train_list1_AUGMIX/onnx_model --opts MODEL.WEIGHTS /logs/veriwild/bagtricks_R50-ibn_with_pretrain_train_list1_AUGMIX/model_final.pth 具体错误： Traceback (most recent call last): File "tools/deploy/onnx_export.py", line 147, in model = build_model(cfg) File "./fastreid/modeling/meta_arch/build.py", line 24, in build_model model = META_ARCH_REGISTRY.get(meta_arch)(cfg) File "./fastreid/config/config.py", line 245, in wrapped init_func(self, **explicit_args) File "./fastreid/modeling/meta_arch/baseline.py", line 53, in **init** self.register_buffer('pixel_mean', torch.Tensor(pixel_mean).view(1, -1, 1, 1), False) TypeError: register_buffer() takes 3 positional arguments but 4 were given

遇到一样的错误，请问你解决了吗
