### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by SunNoJJ** [JDAI-CV/fast-reid#579]
### python37 tools/deploy/onnx_export.py --config-file ./configs/Market1501/bagtricks_R50.yml --name baseline_R50 --output onnx_model --opts MODEL.WEIGHTS logs/market1501/bagtricks_R50/model_final.pth

Traceback (most recent call last):
  File "tools/deploy/onnx_export.py", line 158, in <module>
    model_simp, check = simplify(onnx_model)
TypeError: cannot unpack non-iterable ModelProto object

```
    model_simp, check = simplify(onnx_model)

    model_simp = remove_initializer_from_input(model_simp)

    assert check, "Simplified ONNX model could not be validated"
```
改为：
```
    # model_simp, check = simplify(onnx_model)
    model_simp = simplify(onnx_model)

    model_simp = remove_initializer_from_input(model_simp)

    # assert check, "Simplified ONNX model could not be validated"
```

**Comment by L1aoXingyu** [comment]
Maybe it's your `onnxsim` version problem? You can check the github homepage of onnxsim here https://github.com/daquexian/onnx-simplifier
