### ISSUE TITLE
VehicleID results maybe has a error 

### ISSUE THREAD

**Issue by muzishen** [JDAI-CV/fast-reid#58]
Hello, your work is great. But there may be some problems with the VehicleID.
I think you may have reversed probe set and galleryset. 
Because probe set is much larger than gallery set, and you need to randomly select 10 probes for testing in probe set.

**Comment by L1aoXingyu** [comment]
Yes, you are right. And we have already fixed code, you can check it in [vehicleid dataset](https://github.com/JDAI-CV/fast-reid/blob/c21de64166309f83ebdd3ccd56f0a96230c75a9f/fastreid/data/datasets/vehicleid.py#L67), but not yet updated metric table in model zoo.
We are training model and will update model zoo next week.

**Comment by muzishen** [comment]
That's ok,  I look forward to your results in VehicleID！
Can you provide the results of the ablation experiment on Market1501?

**Comment by L1aoXingyu** [comment]
We will release a paper about this toolkit a week or two. We plan to conduct an ablation study on DukeMTMC dataset.

**Comment by muzishen** [comment]
Thank you very much!

**Comment by muzishen** [comment]
Hi, I am very sorry to open this issue again.
Because I found that you updated the results of VeRi776 and VehicleID, do you have any plans to use ResNet50 as a backbone and report the results?
Do you have 10 cross calculation results on VehicleID, please?
Thank you!

**Comment by JinkaiZheng** [comment]
Hi, at your suggestion, we have added 10 cross calculation results on VehicleID, which will be updated to the MODEL_ZOO.md soon.
We don't have any plans to use ResNet50 yet, but we will try it in our spare time.

**Comment by muzishen** [comment]
Thank you! 
 I very look forward to your paper!

**Comment by Astaxanthin** [comment]
> Thanks for your attention to this work. Yes, you are right. And we have already fixed code, you can check it in [vehicleid dataset](https://github.com/JDAI-CV/fast-reid/blob/c21de64166309f83ebdd3ccd56f0a96230c75a9f/fastreid/data/datasets/vehicleid.py#L67), but not yet updated metric table in model zoo. We are training model and will update model zoo next week.

Line 77 and line 79 are still reversed in vehicleid.py? Cause I ran this code and found the number of images in query is still much larger than that in gallery.

![image](https://user-images.githubusercontent.com/39330240/160062471-106cc3ba-fbea-4d44-a801-310ddd871198.png)

**Comment by JinkaiZheng** [comment]
您的邮件已收到！~
