### ISSUE TITLE
How to set FP16 trainning

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/fast-reid#580]
SOLVER:
  FP16_ENABLED: True,
  IMS_PER_BATCH: 256 # 512 For 4 GPUs
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 20

KeyError: 'Non-existent config key: SOLVER.FP16_ENABLED'

**Comment by L1aoXingyu** [comment]
`SOLVER.FP16.ENABLED: True`

**Comment by deep-practice** [comment]
SOLVER.FP16.ENABLED: True not working,still  returns  'Non-existent config key'

Dose the following setting is the same as FP16?
SOLVER:
  AMP:
    ENABLED: True

**Comment by L1aoXingyu** [comment]
My fault. `SOLVER.AMP.ENABLED: True`
