### ISSUE TITLE
About visualize_result.py

### ISSUE THREAD

**Issue by syh-hue** [JDAI-CV/fast-reid#584]
HI， I am working on fastreid, but I encountered some problems when visualizing result
![QQ图片20211003123745](https://user-images.githubusercontent.com/77479420/135740187-d999ab36-f65a-4550-b64e-f57db032d5f4.png)
My configuration：python demo/visualize_result.py --vis-label --config-file F:/workspace/fast-reid-master/tools/logs/market1501/sbs_R50/config.yaml --dataset-name'Market1501' --output F:/workspace/fast-reid-master/tools/logs/out --opts MODEL.WEIGHTS F:/workspace/fast-reid-master/tools/logs/market1501/sbs_R50/model_final.pth
What's going on？How should i solve？thx

**Comment by lchunleo** [comment]
i run with the above but specifying as 
--dataset-name Market1501 instead of --dataset-name'Market1501' as quoted above and it is ok
