### ISSUE TITLE
训练自定义的数据集

### ISSUE THREAD

**Issue by liujs1016** [JDAI-CV/fast-reid#588]
您好，我将我的数据集改成Market1501的命名规则，但是输入
python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cuda:0"
之后，程式码好像就停住无法训练了，请问是什么问题呢?
是因为我的图片数量太少吗?
还是因为我的图片id太少?
或是因为我只有一个camid和一个sequence?
谢谢
![error](https://user-images.githubusercontent.com/68044258/138421807-664a2850-c0f8-4d03-9dc4-3a30aa8e0823.PNG)

**Comment by huajiangY** [comment]
你们配置好环境下载好数据集直接使用train_net.py训练吗，我的会提示FileNotFoundError: [Errno 2] No such file or directory: ''，不知道少什么文件，请大佬指点一下

**Comment by yonadance** [comment]
两者都设置为4后依旧无法执行，训练集图片数量是三万张
