### ISSUE TITLE
您好，请问ECCV2020的crowd re-id还会公布代码么

### ISSUE THREAD

**Issue by xzzy626** [JDAI-CV/fast-reid#589]
您好，之前看到ECCV文章Guided Saliency Feature Learning for Person Re-identification in Crowded Scenes的代码
链接 https://github.com/ JDAI-CV/fast-reid/blob/master/projects/CrowdReID是指向这里的，但是已经失效了，请
问还会公布么？还有里面的数据集crowd re-id会公开么？谢谢。

**Comment by MasonZong** [comment]
我也非常希望了解这个算法，请问后面会公布代码吗？谢谢。

**Comment by FlyuZ** [comment]
同关注

**Comment by jsdd25** [comment]
同关注. E-mail: 773903267@qq.com

**Comment by bestfei001** [comment]
请问代码还会公布吗？
