### ISSUE TITLE
KeyError: "No object named 'build_mobilenetv3_backbone' found in 'BACKBONE' registry!"

### ISSUE THREAD

**Issue by nigeiwo** [JDAI-CV/fast-reid#594]
The code of backbone mobilenetv3 has register , but when I use the mobilenetv3, I have this error :

KeyError: "No object named 'build_mobilenetv3_backbone' found in 'BACKBONE' registry!"

**Comment by nigeiwo** [comment]
The code of backbone mobilenetv3 has register , but when I use the mobilenetv3, I have this error :   

KeyError: "No object named 'build_mobilenetv3_backbone' found in 'BACKBONE' registry!"

**Comment by nigeiwo** [comment]
![1636941995(1)](https://user-images.githubusercontent.com/49048879/141711095-692d6961-3db3-4fe1-910d-e3c706a9c414.png)

**Comment by wang11wang** [comment]
add this in fastreid/modeling/backbones/__init__.py
`from .mobilenetv3 import build_mobilenetv3_backbone`

**Comment by ThelilinNB** [comment]
Hello, have you solved this problem
