### ISSUE TITLE
A little doubt about AQE's code

### ISSUE THREAD

**Issue by DrinkTeaFirst** [JDAI-CV/fast-reid#596]
Hello Xingyu @L1aoXingyu ,

Thanks for your work. I am currently studying your code, and I am confused about the following part:
https://github.com/JDAI-CV/fast-reid/blob/37ccd3683d81018aabd9fd81087398aeb662050f/fastreid/evaluation/query_expansion.py#L37-L40

In line 37, the code returns with the index of query itself and its top (qe_k) neighbours. 

However, in line 38 and 40, it seems you forgot the qe_k th neighbour. The code only used the query and its top (qe_k -1) neighbours to become a new query.

In my opinion, here should keep using (qe_k + 1). Am I right?

**Comment by L1aoXingyu** [comment]
It's just a minor distinction and I think it will make no difference.
