### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by rrjia** [JDAI-CV/fast-reid#597]
## ❓ How to do something using fastreid

在阅读fast-reid我发现数据输入模型时，除了各种数据增强外，没有对图像进行归一化处理和正则化处理，请问这样模型不是应该非常容易不稳定，难以训练么？

代码片段在：fastreid/data/transforms/build.py中，
图像数据除了各种增强外，只有一个ToTensor，而这个ToTensor操作只是```Converts a PIL Image or numpy.ndarray (H x W x C) in the range
    [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 255.0]```

**Comment by young169** [comment]
> ## ❓ How to do something using fastreid
> 在阅读fast-reid我发现数据输入模型时，除了各种数据增强外，没有对图像进行归一化处理和正则化处理，请问这样模型不是应该非常容易不稳定，难以训练么？
> 
> 代码片段在：fastreid/data/transforms/build.py中， 图像数据除了各种增强外，只有一个ToTensor，而这个ToTensor操作只是`Converts a PIL Image or numpy.ndarray (H x W x C) in the range [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 255.0]`

我是用mgn网络的，他在mgn.py中有预处理，把预处理直接放在forward里面了，转出来的onnx也可以看到，头两层是SUB和DIV。其他的应该也类似吧。。

**Comment by rrjia** [comment]
感谢，的确在网络的forward中进行了这样的操作，请问如果是这种操作的话，在模型推理的时候是不是输入图片就不用做归一化操作了？这些操作已经集成到网络中了。

**Comment by young169** [comment]
> 感谢，的确在网络的forward中进行了这样的操作，请问如果是这种操作的话，在模型推理的时候是不是输入图片就不用做归一化操作了？这些操作已经集成到网络中了。

是的

**Comment by rrjia** [comment]
感谢解答
