### ISSUE TITLE
how to move the preprocessing step out of model?

### ISSUE THREAD

**Issue by young169** [JDAI-CV/fast-reid#598]
## ❓ How to do something using fastreid

We'd like to deploy a MGN model, I noticed that the SUB and DIV layer of data preprocessing caused the inconsistent outputs, so I tried to set the pixel mean to 0 and pixel std to 1. However this seem to be helpless, so how to modify the code so that the transferred ONNX file will not contain those two layers?

**Comment by PrinceP** [comment]
Comment out 
[line130](https://github.com/JDAI-CV/fast-reid/blob/4508251d7439c6c20e8e2d9573c6123b1f388cc5/fastreid/modeling/meta_arch/baseline.py#L130)
