### ISSUE TITLE
在win10系统下运行fast-reid特别慢

### ISSUE THREAD

**Issue by LY-cmd-xtt** [JDAI-CV/fast-reid#605]
![1638496418437](https://user-images.githubusercontent.com/80497702/144531845-a4304331-ec4f-40c7-9d71-248574c472c5.jpg)
您好，我在win10系统使用TITAN显卡，仅用于复现本代码时如图所示，time:2.1272,data_time:0.0011,比我使用另外一个台乌班图系统3060TI显卡的电脑接近慢了十倍。在其他数据集上也是如此缓慢，请问这是什么原因？该如何解决呢？
难道是1.在win10系统fast-reid环境中我未make all;2.使用的faiss是cpu版本而不是GPU版本（我在win10系统似乎无法安装GPU版本）？

**Comment by L1aoXingyu** [comment]
是不是你的 pytorch 版本的问题呢？
使用 pytorch 训练别的模型也很慢吗？
