### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by MartinAOlsen** [JDAI-CV/fast-reid#606]
I am currently working on a project where we want to identify a small group of people on multiple cameras. 
Currently we are using a small "DeepReId" model, but we are hoping to find an increased performance by switching to fast-reid. 

However, on our own dataset we are finding significantly worse performance. Currently we are doing the following. 
- We rescale pictures from our detector using padding.
- Images are converted from interleaved to planar RGB.
- To compare two images we use cosine distance.

Our small test include 87 pictures of 6 different people in a realistic scenario. The goal is to make the overlap between matches and not-matches as small as possible so we will be able to more correctly group the pictures of each individual. 
Our histogram and heatmap for the two models can be seen here: [https://i.imgur.com/23yaxth.png](url)

I assume it is possible to gain a better performance than this. So am I doing something wrong or is there steps I am missing in the data preparation or in the analysis of the output?

Best,
Martin

**Comment by TelBotDev** [comment]
Your histogram and heatmap for those models are so cool. How do you plot that? 

![histogram and heatmap](https://i.imgur.com/23yaxth.png)

**Comment by L1aoXingyu** [comment]
> I am currently working on a project where we want to identify a small group of people on multiple cameras. Currently we are using a small "DeepReId" model, but we are hoping to find an increased performance by switching to fast-reid.
> 
> However, on our own dataset we are finding significantly worse performance. Currently we are doing the following.
> 
> * We rescale pictures from our detector using padding.
> * Images are converted from interleaved to planar RGB.
> * To compare two images we use cosine distance.
> 
> Our small test include 87 pictures of 6 different people in a realistic scenario. The goal is to make the overlap between matches and not-matches as small as possible so we will be able to more correctly group the pictures of each individual. Our histogram and heatmap for the two models can be seen here: [https://i.imgur.com/23yaxth.png](url)
> 
> I assume it is possible to gain a better performance than this. So am I doing something wrong or is there steps I am missing in the data preparation or in the analysis of the output?
> 
> Best, Martin

How did you train reid model with fast-reid compared with your small "DeepReId" model?
