### ISSUE TITLE
请问如何缩小输出特征的纬度?

### ISSUE THREAD

**Issue by qq995431104** [JDAI-CV/fast-reid#615]
默认的FEAT_DIM是2048, 我想输出小一点的特征纬度, 如512, 256等, 如何调整呢?
我调整了config里面的FEAT_DIM, 会报BN的错, 应该是和模型不匹配;
那么, 需要调整模型本身来做吗?还是说通过调整配置文件的某个地方就可以?
期待您的回复~

**Comment by qq995431104** [comment]
找到答案了:https://github.com/JDAI-CV/fast-reid/issues/317

**Comment by Json0926** [comment]
在这个是在yml文件里面修改吗 还是在哪里改
