### ISSUE TITLE
使用KD（模型蒸馏）效果怎么样呢

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#616]
我看你说在resnet101上直接训练测试duke的map=81.14，rank1=90.66；
使用KD的方法用resnet101指导resnet34训练map=73.28，rank1=86.31；
我想问下，直接在resnet34上训练的指标是多少呢？想知道使用KD到底有多少提升

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/148151413-88f49dd0-cfc8-424e-934d-61bd5e490157.png)

这个结果是说 resnet34 直接训练的指标是 73.28，经过蒸馏之后是 78.25
