### ISSUE TITLE
蒸馏过后的R34模型推理速度慢于R50Ibn，R34Ibn大幅度慢于R50Ibn

### ISSUE THREAD

**Issue by yuan960426** [JDAI-CV/fast-reid#621]
请问为什么使用R34蒸馏出来的网络部署在侧端，R34 inference：15ms，R34Ibn inference：18ms，R101Ibn(预训练)：20ms，R50Ibn：10ms，请问模型骨干网络做了哪些更改导致了如此大的差距？

**Comment by L1aoXingyu** [comment]
r34 按道理会比 r50 更快，你是在哪个设备上测试的呀？

**Comment by yuan960426** [comment]
谢谢回复，是由于推理框架会对图做融合，导致的，我关闭融合后速度无误



---原始邮件---
发件人: "Xingyu ***@***.***&gt;
发送时间: 2022年1月6日(周四) 晚上10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JDAI-CV/fast-reid] 蒸馏过后的R34模型推理速度慢于R50Ibn，R34Ibn大幅度慢于R50Ibn (Issue #621)




 
r34 按道理会比 r50 更快，你是在哪个设备上测试的呀？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
