### ISSUE TITLE
Hi, about FastFace

### ISSUE THREAD

**Issue by MrDavinci** [JDAI-CV/fast-reid#627]
## ❓ How to do something using fastreid

I see the models in Fastface with circle loss, but when I check the config I find it is cosface layer.
My question are followings:
1. The circle loss you used for training with Partial FC has a sample rate 0.1?
2. or you didn't use sampled Partial FC, e.g. sample rate = 1

**Comment by L1aoXingyu** [comment]
1. Actually, I use **cosface** for face recognition model training.
2. I used partial-fc with sample_rate = 0.1

**Comment by MrDavinci** [comment]
lol, thanks
谢哥，
