### ISSUE TITLE
多机多卡训练FastRetri报错

### ISSUE THREAD

**Issue by xgyyao** [JDAI-CV/fast-reid#629]
主机命令:
`CUDA_VISIBLE_DEVICES='0,1' python projects/FastRetri/train_net.py --config-file projects/FastRetri/configs/hat.yml --num-gpus 2 --num-machines 2 --machine-rank 0 --dist-url tcp://172.16.2.81:3425`
副机命令：
`CUDA_VISIBLE_DEVICES='0,1' python projects/FastRetri/train_net.py --config-file projects/FastRetri/configs/hat.yml --num-gpus 2 --num-machines 2 --machine-rank 1 --dist-url tcp://172.16.2.81:3425`
报错：
<img width="907" alt="image" src="https://user-images.githubusercontent.com/34907486/150925606-f1590515-e22a-470e-8bde-b4212a4c15d4.png">
请问应该怎么解决呢？

**Comment by L1aoXingyu** [comment]
看上去好像是两台机器之前没法 ping 通，分别的单机两卡可以训练吧。ip 使用主机的 ip 地址，然后尝试在第二台机器上 ping 一下 ip，看看能不能访问。

**Comment by xgyyao** [comment]
你好，分别的单机两卡可以训练, 两台机器是可以互相ping通的。奇怪的是我设置的主机ip和端口是tcp://172.16.2.81:3425，但是看报错显示的却是127.0.0.1+一个随机端口
<img width="258" alt="image" src="https://user-images.githubusercontent.com/34907486/151110744-3e0365bc-d6ba-4fea-8b7e-6cb0b6f7ac0b.png">

**Comment by L1aoXingyu** [comment]
加上这两行命令有用吗
```
export GLOO_SOCKET_IFNAME=eth0
export NCCL_SOCKET_IFNAME=eth0
```
