### ISSUE TITLE
is there any light weight and device friendly reid models for edge device?

### ISSUE THREAD

**Issue by sijun-zhou** [JDAI-CV/fast-reid#630]
Hi, @L1aoXingyu 
is there any light weight and device friendly reid models for edge device? I use osnet before. But i find it is not friendly to edge device. It is not fast enough compared to is low float operations.

Thanks in advance!

**Comment by L1aoXingyu** [comment]
Actually, I just tried ResNet-18 and ResNet-34 for edge devices. 
Maybe each device has its preference operation, so osnet may be very small and has low flops. But the speed may be a little bit slow.
My suggestion is to choose the edge-friendly model architecture.
