### ISSUE TITLE
AssertionError: Checkpoint /path/to/checkpoint_file not found!

### ISSUE THREAD

**Issue by mamimaka** [JDAI-CV/fast-reid#631]
根据Getting Started with Fastreid.md中evolution的主命令：python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --eval-only MODEL.WEIGHTS /path/to/checkpoint_file MODEL.DEVICE "cpu"
（我将cuda:0改为了cpu，因为自己没有cuda）
报错如下：

![Screenshot_20220126_101105](https://user-images.githubusercontent.com/57143134/151091951-6d3b4e4e-7eb9-4fae-a9de-0b74303e893e.png)

请问该如何解决呢？

**Comment by L1aoXingyu** [comment]
`MODEL.WEIGHTS /path/to/checkpoint` 需要传你自己的模型路径

**Comment by mamimaka** [comment]
> `MODEL.WEIGHTS /path/to/checkpoint` 需要传你自己的模型路径

明白了，谢谢啦

**Comment by mamimaka** [comment]
> `MODEL.WEIGHTS /path/to/checkpoint` 需要传你自己的模型路径

问题解决啦
