### ISSUE TITLE
大数据集无法训练的问题

### ISSUE THREAD

**Issue by widgetxp** [JDAI-CV/fast-reid#632]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:
使用FastRetri训练一个1800万图的训练集，读完label文件后屏幕会停止输出约5分钟，然后报错，信息如下：
![image](https://user-images.githubusercontent.com/16634327/151121692-eec214d8-66ab-49f6-93fe-3c8b37701f2c.png)
做了些尝试解决这个问题
1. 网上一般建议减少dataloader的worker数目，由8降到4之后，才能开启训练，但是gpu利用率不足
2. 尝试只用一半训练数据1100万图，仍是8个worker，也能正常开启训练。
3. 数据加载队列的size由默认的10减小到2，不work。
4. batch_size由2048降低到1024，不work。
想问下出现这种问题的根本原因是什么，以及解决方案。配置截图如下：
![image](https://user-images.githubusercontent.com/16634327/151121100-b5eab501-c720-4ccc-b7e4-8d992f8073ac.png)

1. full code you wrote or full changes you made (`git diff`)

新增的数据集：
![image](https://user-images.githubusercontent.com/16634327/151121406-530d34ae-4e03-4142-982c-e236b06c4543.png)

2. what exact command you run:
python projects/FastRetri/train_net.py --config-file projects/FastRetri/configs/goods-image_retri.yml --num-gpus 4

**Comment by L1aoXingyu** [comment]
建议提前离线生成 txt，然后从 txt 读取 index 进行训练，应该可以解决这个问题
