### ISSUE TITLE
questions on fastface

### ISSUE THREAD

**Issue by markncx** [JDAI-CV/fast-reid#633]
## ❓ How to do something using fastreid

As you mentioned in faceface experiment result, fastface is trained with circle loss, but when I check the config I find it is cosface layer.

which one is better? cosface/arcface/circle loss

![image](https://user-images.githubusercontent.com/37343257/151309263-34208902-8c1f-4f8f-b6fc-4eb56ad731b2.png)

**Comment by L1aoXingyu** [comment]
According to our experiments, cosface is little bit better.
