### ISSUE TITLE
How to evaluation on CPU?

### ISSUE THREAD

**Issue by mamimaka** [JDAI-CV/fast-reid#636]
我按照文档输入了指令：
python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml --eval-only \
MODEL.WEIGHTS /home/xhr/桌面/fast-reid-master/pretrained_model/2022-01-27-16-56-46-fast-reid-msmt_agw_R101-ibn.pth MODEL.DEVICE "cpu"

上面预训练模型是我自己是的路径，MODEL.DEVICE我改为了CPU

但在evaluation过程中出现了错误：

![Screenshot_20220128_104208](https://user-images.githubusercontent.com/57143134/151642565-7941e3b1-3236-4f23-a8b8-6454a836e51e.png)

请问该如何解决这个问题呢？

**Comment by L1aoXingyu** [comment]
抱歉现在不支持在 cpu 上推理和测试
