### ISSUE TITLE
请问par 的evaluation代码对多类适用吗？

### ISSUE THREAD

**Issue by zhangshitoday** [JDAI-CV/fast-reid#640]
`fast-reid/projects/FastAttr/fastattr/attr_evaluation.py
def get_attr_metrics(gt_labels, pred_logits, thres):

        eps = 1e-20

        pred_labels = copy.deepcopy(pred_logits)
        pred_labels[pred_logits < thres] = 0
        pred_labels[pred_logits >= thres] = 1
`
请问这里只考虑2类吗，像age属性有[0,1,2,3]  四类，是适用的吗

**Comment by L1aoXingyu** [comment]
应该是不行的，可能需要自己改写一下
