### ISSUE TITLE
降低输出维度

### ISSUE THREAD

**Issue by qijiaojiao** [JDAI-CV/fast-reid#644]
我用veriwild训练，原来的维度是2048维，对于我的业务场景维度过高，存储成本太高。请问我训练的时候，只需要在HEADS加个EMBEDDING_DIM: 256就可以么？还有其他的修改么

**Comment by L1aoXingyu** [comment]
是的，不过这样精度可能会降低

**Comment by qijiaojiao** [comment]
> 是的，不过这样精度可能会降低

好的多谢
