### ISSUE TITLE
About visualize_demo.py

### ISSUE THREAD

**Issue by Thangbluee** [JDAI-CV/fast-reid#651]
![0](https://user-images.githubusercontent.com/88204104/161895336-0fc6482b-a4b0-430a-b19c-e507d0724808.jpg)

This is a visualize result of market1501. 
I see that the cosine distance is very big. Is any thing wrong? 
Help please.

**Comment by hotfeng** [comment]
hi, I also encountered the same problem, have you ever solved it ?
I used the checkout with both customed  and model zoo, but neither got proper AP and cosine distance.

**Comment by Thangbluee** [comment]
@hotfeng I haven't solved it

**Comment by phanthanhtung0701** [comment]
Hi @Thangbluee @hartvon, I also met this problem, have you ever solved it?
