### ISSUE TITLE
How to train with ViT

### ISSUE THREAD

**Issue by genhao3** [JDAI-CV/fast-reid#653]
The evaluation metrics are very low when I use the original configuration of bagtricks_vit.yml for training. What am I doing wrong? Do I need to modify the code elsewhere?
![image](https://user-images.githubusercontent.com/23277773/163532770-61c6e84e-b660-4e02-85cf-f4c408fdfb22.png)

**Comment by peterzpy** [comment]
Maybe another version of pytorch could solve this problem. I meet the same problem under pytorch1.10 and solve it by using pytoch1.8.1.

**Comment by genhao3** [comment]
> Maybe another version of pytorch could solve this problem. I meet the same problem under pytorch1.10 and solve it by using pytoch1.8.1.

That's great!
