### ISSUE TITLE
请问，行人属性识别工程，提供tensorrt部署细节吗？

### ISSUE THREAD

**Issue by starsky68** [JDAI-CV/fast-reid#676]
## ❓ How to do something using fastreid

请问，行人属性识别工程，提供tensorrt部署细节吗？

**Comment by L1aoXingyu** [comment]
整体的部署流程和 reid 模型基本一致，通过 onnx -> trt 流程走通，然后再看使用 c++ 部署还是 python 来决定前后处理的代码该怎么写。
