### ISSUE TITLE
a bug in ./fastreid/modeling/backbones/regnet/regnet.py

### ISSUE THREAD

**Issue by cd70zyx** [JDAI-CV/fast-reid#678]
Dear Author,

There is a bug in ./fastreid/modeling/backbones/regnet/regnet.py - line 562.
It is currently written as:
'4000x': 'fastreid/modeling/backbones/regnet/regnety/RegNetX-4.0GF_dds_8gpu.yaml',
But '**regnety**' should be rectified as '**regnetx**', like this:
'4000x': 'fastreid/modeling/backbones/regnet/regnetx/RegNetX-4.0GF_dds_8gpu.yaml',

I guess you may need to fix this error. Many thanks!

**Comment by L1aoXingyu** [comment]
Thanks very mush and already fixed it.
