### ISSUE TITLE
显存增长问题

### ISSUE THREAD

**Issue by annyhou** [JDAI-CV/fast-reid#681]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/45547401/191222943-124a5cf5-c315-48e5-9444-df61e03a3a73.png">

问题描述：项目:FastRetri,backbone:resnet50,训练测试batchsize:32,第一次验证,显存暴涨至7G多，后面训练验证能稳定到4G以内。由于最大显存为7G多，相当于我需要提供的显存要在8G以上。为什么第一次验证时，需要那么大的显存缓冲区空间？可以减小么？

**Comment by L1aoXingyu** [comment]
可以尝试减小 inference batch_size 
https://github.com/JDAI-CV/fast-reid/blob/afe432b8c0ecd309db7921b7292b2c69813d0991/configs/Base-bagtricks.yml#L74
