### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by stqwzr** [JDAI-CV/fast-reid#682]
Hi, how can i do finetuning? So i have pretrained weights and want to freeze all layer expect last fc layer and train only last fc layer.

**Comment by L1aoXingyu** [comment]
Maybe you need to add some code for this feature. You can freeze the parameters after model initialization, for example

```python
model = model_init()
for name, params in model.named_parameters():
    if name.find("fc") != 0:
		params.requires_grad_(False)
```
