### ISSUE TITLE
No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by tiamo405** [JDAI-CV/fast-reid#700]
file Base-SBS.yml
```
SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
```

  error:
```
 File "/mnt/nvme0n1/miniconda3/envs/fast-reid/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 368, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```
code run :
`CUDA_VISIBLE_DEVICES=0 python tools/train_net.py \
  --config-file ./configs/Market1501/sbs_R50.yml \
   MODEL.DEVICE "cuda:0"`
can someone help me? thanks

**Comment by anaatef9** [comment]
hey, i am facing the same issue when running the getting started code, did you figure out the problem?

**Comment by pierrez99** [comment]
Hi. I was facing the same issue today on the Market1501 dataset, and in my case I think it had to do with `self.optimizer.zero_grad()` (found in _engine/train_loop.py_). After changing this to `self.optimizer.zero_grad(set_to_none=False)` I started getting a different error, related to my GPU. 

The problem with my GPU was that it was not able to allocate enough memory. I managed to fix this by adding a parameter to the autocast, in the same file, as follows `with autocast(dtype=torch.float16):`. Moreover, I also played around with the IMS_PER_BATCH in _Base-bagtricks.yml_. I had to reduce the batch size for both the SOLVER and the TEST fields. I also added `torch.cuda.empty_cache()` right after the `self.grad_scaler.update()`, but I don't think it is necessary. Emptying the cache ensured it worked during training but it also increased training time.

I am quite new to this so I am not sure if this was the best approach but I hope it helps.

**Comment by tiamo405** [comment]
> này, tôi đang gặp vấn đề tương tự khi chạy mã bắt đầu, bạn có tìm ra vấn đề không?
> 
> cập nhật: vừa xóa MODEL.DEVICE "cuda:0 khỏi dòng lệnh
> 
> chạy cái này: `python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml" `



> CHÀO. Tôi đã gặp phải vấn đề tương tự ngày hôm nay trên bộ dữ liệu Market1501 và trong trường hợp của tôi, tôi nghĩ rằng nó đã xảy ra với `self.optimizer.zero_grad()`(được tìm thấy trong _engine/train_loop.py_ ). Sau khi thay đổi điều này thành, `self.optimizer.zero_grad(set_to_none=False)`tôi bắt đầu gặp một lỗi khác, liên quan đến GPU của mình.
> 
> Vấn đề với GPU của tôi là nó không thể phân bổ đủ bộ nhớ. Tôi đã cố gắng khắc phục điều này bằng cách thêm một tham số vào autocast, trong cùng một tệp, như sau `with autocast(dtype=torch.float16):`. Ngoài ra, tôi cũng đã thử với IMS_PER_BATCH trong _Base-bagtricks.yml_ . Tôi đã phải giảm kích thước lô cho cả hai trường SOLVER và TEST. Tôi cũng đã thêm `torch.cuda.empty_cache()`ngay sau dấu `self.grad_scaler.update()`, nhưng tôi không nghĩ là cần thiết. Làm trống bộ đệm đảm bảo nó hoạt động trong quá trình đào tạo nhưng nó cũng làm tăng thời gian đào tạo.
> 
> Tôi còn khá mới với điều này vì vậy tôi không chắc liệu đây có phải là cách tiếp cận tốt nhất hay không nhưng tôi hy vọng nó có ích.

cách giải quyết của tôi là hạ phiên bản pytorch xuống. 
`pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113`
sau đó chương trình hoạt động bình thường

**Comment by tiamo405** [comment]
> Hi. I was facing the same issue today on the Market1501 dataset, and in my case I think it had to do with `self.optimizer.zero_grad()` (found in _engine/train_loop.py_). After changing this to `self.optimizer.zero_grad(set_to_none=False)` I started getting a different error, related to my GPU.
> 
> The problem with my GPU was that it was not able to allocate enough memory. I managed to fix this by adding a parameter to the autocast, in the same file, as follows `with autocast(dtype=torch.float16):`. Moreover, I also played around with the IMS_PER_BATCH in _Base-bagtricks.yml_. I had to reduce the batch size for both the SOLVER and the TEST fields. I also added `torch.cuda.empty_cache()` right after the `self.grad_scaler.update()`, but I don't think it is necessary. Emptying the cache ensured it worked during training but it also increased training time.
> 
> I am quite new to this so I am not sure if this was the best approach but I hope it helps.



> hey, i am facing the same issue when running the getting started code, did you figure out the problem?
> 
> update: just removed MODEL.DEVICE "cuda:0 from the command line
> 
> run this: `python3 tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml" `

my workaround was to downgrade pytorch version.
`pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113`
then the program works normally

**Comment by michal-kierzynka** [comment]
In my case adding `set_to_none` parameter to `self.optimizer.zero_grad(set_to_none=False)` fixed the problem.

**Comment by huiyiygy** [comment]
Hi everyone, I also encountered this issue in Pytorch 2.0, and after debugging the code, I found a simple solution that does not require lowering the Pytorch version。
Just need to Set the parameter 'continuous=False' of the build_optimizer()  in line 380 of defaults.py  like this
···
return build_optimizer(cfg, model)
# convert to
return build_optimizer(cfg, model, continuous=False)
···
In this way, it is avoided to convert the network's params to ContiguousParams.

I debugged code and found that if using ContiguousParams,  after loss.backword() , the calculated gradient is None,  and leading to training errors.

After setting it to False, the network can train smoothly and may achieve higher accuracy : )

**Comment by jveitchmichaelis** [comment]
@huiyiygy Thanks for this! Minor typo, it should be `contiguous=False`, not `continuous`. Otherwise this seems to work and while you can train with AMP off, I get pretty terrible loss curves. With this set, loss immediately decreases as expected.
