### ISSUE TITLE
 Some model parameters or buffers are not found in the checkpoint:Please read & provide the following

### ISSUE THREAD

**Issue by WZR8277** [JDAI-CV/fast-reid#705]
从官网下载'ibn_50x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth'到指定文件夹，训练时报如下错误后，加载checkpoints无效从头训练了：
 Some model parameters or buffers are not found in the checkpoint:
 NL_2.0.g.{weight, bias}
  NL_2.0.W.0.{weight, bias}
  NL_2.0.W.1.{weight, bias, running_mean, running_var}
  NL_2.0.theta.{weight, bias}
  NL_2.0.phi.{weight, bias}
  NL_2.1.g.{weight, bias}
  NL_2.1.W.0.{weight, bias}
  NL_2.1.W.1.{weight, bias, running_mean, running_var}
  NL_2.1.theta.{weight, bias}
  NL_2.1.phi.{weight, bias}
  NL_3.0.g.{weight, bias}
  NL_3.0.W.0.{weight, bias}
  NL_3.0.W.1.{weight, bias, running_mean, running_var}
  NL_3.0.theta.{weight, bias}
  NL_3.0.phi.{weight, bias}
  NL_3.1.g.{weight, bias}
  NL_3.1.W.0.{weight, bias}
  NL_3.1.W.1.{weight, bias, running_mean, running_var}
  NL_3.1.theta.{weight, bias}
  NL_3.1.phi.{weight, bias}
  NL_3.2.g.{weight, bias}
  NL_3.2.W.0.{weight, bias}
  NL_3.2.W.1.{weight, bias, running_mean, running_var}
  NL_3.2.theta.{weight, bias}
  NL_3.2.phi.{weight, bias}

**Comment by gyh420** [comment]
> 从官网下载'ibn_50x': '[https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth'到指定文件夹，训练时报如下错误后，加载checkpoints无效从头训练了：](https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth'%E5%88%B0%E6%8C%87%E5%AE%9A%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AE%AD%E7%BB%83%E6%97%B6%E6%8A%A5%E5%A6%82%E4%B8%8B%E9%94%99%E8%AF%AF%E5%90%8E%EF%BC%8C%E5%8A%A0%E8%BD%BDcheckpoints%E6%97%A0%E6%95%88%E4%BB%8E%E5%A4%B4%E8%AE%AD%E7%BB%83%E4%BA%86%EF%BC%9A) Some model parameters or buffers are not found in the checkpoint: NL_2.0.g.{weight, bias} NL_2.0.W.0.{weight, bias} NL_2.0.W.1.{weight, bias, running_mean, running_var} NL_2.0.theta.{weight, bias} NL_2.0.phi.{weight, bias} NL_2.1.g.{weight, bias} NL_2.1.W.0.{weight, bias} NL_2.1.W.1.{weight, bias, running_mean, running_var} NL_2.1.theta.{weight, bias} NL_2.1.phi.{weight, bias} NL_3.0.g.{weight, bias} NL_3.0.W.0.{weight, bias} NL_3.0.W.1.{weight, bias, running_mean, running_var} NL_3.0.theta.{weight, bias} NL_3.0.phi.{weight, bias} NL_3.1.g.{weight, bias} NL_3.1.W.0.{weight, bias} NL_3.1.W.1.{weight, bias, running_mean, running_var} NL_3.1.theta.{weight, bias} NL_3.1.phi.{weight, bias} NL_3.2.g.{weight, bias} NL_3.2.W.0.{weight, bias} NL_3.2.W.1.{weight, bias, running_mean, running_var} NL_3.2.theta.{weight, bias} NL_3.2.phi.{weight, bias

请问您解决了吗
