### ISSUE TITLE
Pretrained-fastreid for Partial ReID

### ISSUE THREAD

**Issue by petercsjTW** [JDAI-CV/fast-reid#709]
Thank you for your service:)

I wonder whether there is a pre-trained fastreid model for partial ReID.
I cannot find the fastreid model for partial ReID.

Thank you.

**Comment by ShawnaWong** [comment]
I guess you could find some pre-trained model in files: MODEL_ZOO.md.
Hope to help you:)

**Comment by petercsjTW** [comment]
Thank you for your reply. However, I'm sorry but I cannot find any model weight related to DSR. In the DSR paper, they said it needs the fine-tuning, so it has to be the fine-tuned version of the each weight (BoT, AGW, and SBS or etc).
