### ISSUE TITLE
error *** Error in `python3': double free or corruption (!prev): 0x000055e66e0a3350 *** for train

### ISSUE THREAD

**Issue by Millczc** [JDAI-CV/fast-reid#71]
i  want to train veri,and i start train:
python3 tools/train_net.py  --config-file configs/VeRi/sbs_R50-ibn.yml
but get this error:
*** Error in `python3': double free or corruption (!prev): 0x000055e66e0a3350 ***
Aborted (core dumped)
what should i do?

**Comment by L1aoXingyu** [comment]
maybe this will help you
https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156

**Comment by Millczc** [comment]
> maybe this will help you
> [tensorflow/tensorflow#6968 (comment)](https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156)



> maybe this will help you
> [tensorflow/tensorflow#6968 (comment)](https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156)

thanks for help
i found this issue happend in ubuntu 14.04;
this project work well in ubuntu 16.04 now.
