### ISSUE TITLE
vis_result and train_net accuracy result not match

### ISSUE THREAD

**Issue by WenjinFu** [JDAI-CV/fast-reid#717]
<img width="566" alt="image" src="https://github.com/JDAI-CV/fast-reid/assets/57229263/feeff3da-6265-4fe8-8037-3ffa7c4f8c22">

<img width="578" alt="image" src="https://github.com/JDAI-CV/fast-reid/assets/57229263/9b2da98d-2846-4b5b-b37b-9ca8543a8475">

The rank-1 acc is 100% but in vis_result, I used 7 images for query, but only got 5/7 correct for rank-1. Why the rank-1 acc from train_net doesn't match with vis_result? Why rank-1, rank-5, rank-10 all get 100% results?

**Comment by puyiwen** [comment]
I have the same question，do you solve it?
