### ISSUE TITLE
KeyError: "No object named 'MGN' found in 'META_ARCH' registry!"

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#72]
运行程序的时候出现这样的错误
KeyError: "No object named 'MGN' found in 'META_ARCH' registry!"
运行的是 visualize_result.py --config-file "../configs/Market1501/mgn_R50-ibn.yml" --parallel --vis-label --dataset-name "Market1501" --output "logs/mgn_market_vis" --opts MODEL.WEIGHTS "../../pretrained/resnet50_ibn_a.pth.tar"

**Comment by L1aoXingyu** [comment]
fixed，please update and try again.

**Comment by xiaopanchen** [comment]
谢谢。您的程序我在windows下运行，您提供的训练好的模型文件以.tar结尾，如果使用您预训练好的模型，如何从这个文件得到.pth文件呢。谢谢廖老师。
