### ISSUE TITLE
How to use custom backbone architecture?

### ISSUE THREAD

**Issue by chamecall** [JDAI-CV/fast-reid#725]
hello and thanks for your work.
could u please guys tell me how to use custom (not resnet50) backbone cause speed is the most important aspect for me so I'd like to try mobilenetv3 from timm for this purpose;

I guees it's not enough to modify config files..

**Comment by Macklzh1** [comment]
I have the same question, I want to replace backbone with VIT, but I don't know how to properly change the mgn.py file in meta_arch. I hope the author or someone with the same question can answer me.

**Comment by Thomas-CHOCHOY** [comment]
i have the same question, i'd like to be able to train the reid model with my own detection model
