### ISSUE TITLE
AMPTrainer

### ISSUE THREAD

**Issue by Tsai-chia-hsiang** [JDAI-CV/fast-reid#735]
At the part [AMPTrainer](https://github.com/JDAI-CV/fast-reid/blob/c9bc3ceb2f7a6438b62fb515ea3df6d1e999e95d/fastreid/engine/train_loop.py#L351)
line 351
```
self.grad_scaler.step(self.optimizer)
```

Will raise the error   
```
File "/home/tch/.conda/envs/tenv/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 450, in step
    len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
```

Do I need to set something before run ```tools/train_net.py``` ?

**Comment by gilta-iron** [comment]
I have encountered this issue as well.
Is there any solution ?

Additionally, 
even after disabling AMPTrainer (AMP: False) the loss (all of it's components) does not decrease and remains constant.

Context:
- trying to fast-reid [bagtricks_R50-ibn](https://github.com/JDAI-CV/fast-reid/blob/master/configs/VERIWild/bagtricks_R50-ibn.yml) on VERI-WILD dataset
- used "python3 tools/train_net.py --config-file ./configs/VERIWild/bagtricks_R50-ibn.yml MODEL.DEVICE "cuda:0" to train
- devices: 
- - RTX4080
- - 2 x A6000

**Comment by jayong-sv** [comment]
In my case, this solution worked. See https://github.com/JDAI-CV/fast-reid/issues/700#issuecomment-1857228550

**Comment by gilta-iron** [comment]
@jayong-sv 
thank you
