### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#74]
1.  File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
    cpdef evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03=False):
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
    return eval_market1501_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
2. Windows下如何使用cython编译呢，python setup.py build_ext --inplace
precated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
rank_cy.c(3165): warning C4244: “=”: 从“Py_ssize_t”转换到“long”，可能丢失数据
rank_cy.c(3174): warning C4244: “=”: 从“Py_ssize_t”转换到“long”，可能丢失数据
rank_cy.c(3818): warning C4244: “=”: 从“long”转换到“float”，可能丢失数据
rank_cy.c(4531): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
rank_cy.c(4561): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
rank_cy.c(5053): warning C4244: “=”: 从“Py_ssize_t”转换到“long”，可能丢失数据
rank_cy.c(5062): warning C4244: “=”: 从“Py_ssize_t”转换到“long”，可能丢失数据
rank_cy.c(5705): warning C4244: “=”: 从“long”转换到“float”，可能丢失数据
rank_cy.c(5860): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
rank_cy.c(5947): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
rank_cy.c(5997): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Anaconda3\libs /LIBPATH:C:\ProgramData\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_rank_cy build\temp.win-amd64-3.7\Release\rank_cy.obj /OUT:E:\Person-reid\fast-reid\fastreid\evaluation\rank_cylib\rank_cy.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\rank_cy.cp37-win_amd64.lib
rank_cy.obj : warning LNK4197: 多次指定导出“PyInit_rank_cy”；使用第一个规范
  正在创建库 build\temp.win-amd64-3.7\Release\rank_cy.cp37-win_amd64.lib 和对象 build\temp.win-amd64-3.7\Release\rank_cy.cp37-win_amd64.exp

**Comment by L1aoXingyu** [comment]
建议使用 linux 或者 macos 来编译测试代码，我没有试过在 windows 下编译。

**Comment by caffelearn** [comment]
我解决了这个问题，在rank.py文件中，把184行的Ture改成False,不使用cython编译的东西。我的是windows系统,可以复现结果
