### ISSUE TITLE
预训练模型问题

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#75]
google云盘中的模型是pth格式，可是我下载到本地后就自动添加了.tar，如何解决呢。请各位指教。谢谢

**Comment by xiaopanchen** [comment]
还是本来就是tar格式呢，我用的是Windows系统

**Comment by fangwudi** [comment]
tar应该是ok的 你试试

**Comment by xiaopanchen** [comment]
> tar应该是ok的 你试试

    checkpoint_state_dict = checkpoint.pop("model")
KeyError: 'model'

**Comment by xiaopanchen** [comment]
@fangwudi    
错误信息如下
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\Person-reid\fast-reid\demo\predictor.py", line 101, in run
    predictor = DefaultPredictor(self.cfg, self.device)
  File "E:\Person-reid\fast-reid\fastreid\engine\defaults.py", line 142, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "E:\Person-reid\fast-reid\fastreid\utils\checkpoint.py", line 110, in load
    self._load_model(checkpoint)
  File "E:\Person-reid\fast-reid\fastreid\utils\checkpoint.py", line 204, in _load_model
    checkpoint_state_dict = checkpoint.pop("model")
KeyError: 'model'
请指教

**Comment by L1aoXingyu** [comment]
这个pretrain model是backbone的pretrain，不是可以直接用的reid model，你需要自己先train一下

**Comment by xiaopanchen** [comment]
> 这个pretrain model是backbone的pretrain，不是可以直接用的reid model，你需要自己先train一下

ok

**Comment by finger-monkey** [comment]
resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？

**Comment by L1aoXingyu** [comment]
> resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？

请查看 GETTING_STARTED.md

**Comment by finger-monkey** [comment]
> > resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？
> 
> 请查看 [GETTING_STARTED.md](https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md)

好的。感谢您的回复。抱歉之前没有仔细看。
如何运行这方面要是能够再写详细一点就好了，若不是之前有跑过strong baseline会感觉不知道从何入手。

**Comment by L1aoXingyu** [comment]
> > > resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？
> > 
> > 
> > 请查看 [GETTING_STARTED.md](https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md?rgh-link-date=2020-06-06T11%3A40%3A17Z)
> 
> 好的。感谢您的回复。抱歉之前没有仔细看。
> 如何运行这方面要是能够再写详细一点就好了，若不是之前有跑过strong baseline会感觉不知道从何入手。

好的，目前是开源的代码比较完善，文档还比较欠缺，我们正在努力，谢谢提的意见。

**Comment by LoryMANG** [comment]
> > > > resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？
> > > 
> > > 
> > > 请查看 [GETTING_STARTED.md](https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md?rgh-link-date=2020-06-06T11%3A40%3A17Z)
> > 
> > 
> > 好的。感谢您的回复。抱歉之前没有仔细看。
> > 如何运行这方面要是能够再写详细一点就好了，若不是之前有跑过strong baseline会感觉不知道从何入手。
> 
> 好的，目前是开源的代码比较完善，文档还比较欠缺，我们正在努力，谢谢提的意见。

您好，目前行人重识别和车辆重识别的工程代码没有公开对吧？后期会公开吗？

**Comment by linjiawen2019** [comment]
@L1aoXingyu  你好，我想请教两个问题：
1. 请问预训练模型一直加载失败是为什么呢？ 路径应该是没有写错的：
“No checkpoint found. Initializing model from scratch”
2. 请问config中的WITH_NL，non-local指的是什么呢？

谢谢你的回答，一下是我的config:
[06/10 13:53:05] fastreid INFO: Running with full config:
CUDNN_BENCHMARK: True
DATALOADER:
  NUM_INSTANCE: 16
  NUM_WORKERS: 16
  PK_SAMPLER: True
DATASETS:
  COMBINEALL: False
  NAMES: ('Market1501',)
  TESTS: ('Market1501',)
INPUT:
  DO_AUGMIX: False
  DO_AUTOAUG: True
  DO_CJ: False
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: True
    MEAN: [123.675, 116.28, 103.53]
    PROB: 0.5
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: True
    PRETRAIN_PATH: /data2/ljw/fast-reid/pretrained_models/torch/checkpoints/resnet50_ibn_a.pth.tar
    WITH_IBN: True
    WITH_NL: False
    WITH_SE: False
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 2048
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.3
      EPSILON: 0.1
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss', 'TripletLoss')
    TRI:
      HARD_MINING: True
      MARGIN: 0.0
      NORM_FEAT: False
      SCALE: 1.0
      USE_COSINE_DIST: False
  META_ARCHITECTURE: Baseline
  OPEN_LAYERS: ['heads']
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  WEIGHTS: 
OUTPUT_DIR: logs/market1501/sbs_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS: (30, 55)
  SWA:
    ENABLED: False
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: False
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3

**Comment by L1aoXingyu** [comment]
> > > > > resnet101_ibn_a.pth.tar  请问这个文件要到哪里下载呢？
> > > > 
> > > > 
> > > > 请查看 [GETTING_STARTED.md](https://github.com/JDAI-CV/fast-reid/blob/master/GETTING_STARTED.md?rgh-link-date=2020-06-08T05%3A50%3A54Z)
> > > 
> > > 
> > > 好的。感谢您的回复。抱歉之前没有仔细看。
> > > 如何运行这方面要是能够再写详细一点就好了，若不是之前有跑过strong baseline会感觉不知道从何入手。
> > 
> > 
> > 好的，目前是开源的代码比较完善，文档还比较欠缺，我们正在努力，谢谢提的意见。
> 
> 您好，目前行人重识别和车辆重识别的工程代码没有公开对吧？后期会公开吗？

工程代码是指什么？

**Comment by L1aoXingyu** [comment]
> 1. “No checkpoint found. Initializing model from scratch”

这里并不是指模型没有 load pretrain model，而是指模型没有 checkpoint，从头训练，如果你的训练中断了，你要继续训练，这里就会变成 found checkpoint ...

> 请问config中的WITH_NL，non-local指的是什么呢？

non-local 是指这个网络结构
https://arxiv.org/abs/1711.07971

**Comment by linjiawen2019** [comment]
> > 1. “No checkpoint found. Initializing model from scratch”
> 
> 这里并不是指模型没有 load pretrain model，而是指模型没有 checkpoint，从头训练，如果你的训练中断了，你要继续训练，这里就会变成 found checkpoint ...
> 
> > 请问config中的WITH_NL，non-local指的是什么呢？
> 
> non-local 是指这个网络结构
> https://arxiv.org/abs/1711.07971

谢谢你的回答！意思是说在imageNet上预训练的backbone实际上已经加载成功了，然后Re-ID模型要在Market1501上进行训练是吗

**Comment by L1aoXingyu** [comment]
> 谢谢你的回答！意思是说在imageNet上预训练的backbone实际上已经加载成功了，然后Re-ID模型要在Market1501上进行训练是吗

是的

**Comment by linjiawen2019** [comment]
> > 谢谢你的回答！意思是说在imageNet上预训练的backbone实际上已经加载成功了，然后Re-ID模型要在Market1501上进行训练是吗
> 
> 是的，我等会儿修改一下描述，以免大家误解这个地方的意思。

嗯嗯~ 非常感谢

**Comment by nobody-cheng** [comment]
@xiaopanchen 你好，请问一下你是怎么解决  KeyError: 'model' 我这边也是训练mgn_R50出现的问题

Command Line Args: Namespace(config_file='./configs/Market1501/mgn_R50-ibn.yml', eval_only=False, opts=[], resume=False)
[07/01 08:14:29 fastreid]: Rank of current process: 0. World size: 1
[07/01 08:14:29 fastreid]: Command line arguments: Namespace(config_file='./configs/Market1501/mgn_R50-ibn.yml', eval_only=False, opts=[], resume=False)
[07/01 08:14:29 fastreid]: Contents of args.config_file=./configs/Market1501/mgn_R50-ibn.yml:
_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    PRETRAIN_PATH: "/data/share/imageAlgorithm/zhangcheng/code/fast-reid/checkpoints/resnet50_ibn_a.pth.tar"
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)


OUTPUT_DIR: "logs/market1501/mgn_R50-ibn"

[07/01 08:14:29 fastreid]: Running with full config:
CUDNN_BENCHMARK: True
DATALOADER:
  NAIVE_WAY: False
  NUM_INSTANCE: 16
  NUM_WORKERS: 0
  PK_SAMPLER: True
DATASETS:
  COMBINEALL: False
  NAMES: ('Market1501',)
  TESTS: ('Market1501',)
INPUT:
  DO_AUGMIX: False
  DO_AUTOAUG: True
  DO_CJ: False
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: True
    MEAN: [123.675, 116.28, 103.53]
    PROB: 0.5
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [384, 128]
  SIZE_TRAIN: [384, 128]
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: True
    PRETRAIN_PATH: /data/share/imageAlgorithm/zhangcheng/code/fast-reid/checkpoints/resnet50_ibn_a.pth.tar
    WITH_IBN: False
    WITH_NL: False
    WITH_SE: False
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 256
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 0.125
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss', 'TripletLoss')
    TRI:
      HARD_MINING: True
      MARGIN: 0.0
      NORM_FEAT: False
      SCALE: 0.2
  META_ARCHITECTURE: MGN
  OPEN_LAYERS: ['b1_pool', 'b1_head', 'b2_pool', 'b2_head', 'b21_pool', 'b21_head', 'b22_pool', 'b22_head', 'b3_pool', 'b3_head', 'b31_pool', 'b31_head', 'b32_pool', 'b32_head', 'b33_pool', 'b33_head']
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  WEIGHTS:
OUTPUT_DIR: logs/market1501/mgn_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS: (30, 55)
  SWA:
    ENABLED: False
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: False
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
[07/01 08:14:29 fastreid]: Full config saved to /data/share/imageAlgorithm/zhangcheng/code/fast-reid/logs/market1501/mgn_R50-ibn/config.yaml
Traceback (most recent call last):
  File "./tools/train_net.py", line 79, in <module>
    main(args)
  File "./tools/train_net.py", line 70, in main
    trainer = Trainer(cfg)
  File "./fastreid/engine/defaults.py", line 203, in __init__
    model = self.build_model(cfg)
  File "./fastreid/engine/defaults.py", line 366, in build_model
    model = build_model(cfg)
  File "./fastreid/modeling/meta_arch/build.py", line 23, in build_model
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "./fastreid/modeling/meta_arch/mgn.py", line 33, in __init__
    backbone = build_backbone(cfg)
  File "./fastreid/modeling/backbones/build.py", line 27, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg)
  File "./fastreid/modeling/backbones/resnet.py", line 259, in build_resnet_backbone
    state_dict = torch.load(pretrain_path)['model']
KeyError: 'model'

**Comment by Gavin666Github** [comment]
> google云盘中的模型是pth格式，可是我下载到本地后就自动添加了.tar，如何解决呢。请各位指教。谢谢

朋友，云盘里的模型我下载不了，可以共享一下到百度网盘吗，感谢

**Comment by Adil42s** [comment]
I am tring to make infefrence using a vision transformer pre trained mode,I am using Fastreid library. Please help me with this error: trackers.append(BoTSORT(track_buffer=args[‘track_buffer’], max_batch_size=args[‘max_batch_size’],
File “/media/storage/AIC2024_Track1_Nota/trackers/botsort/bot_sort.py”, line 270, in init
self.encoder = FastReIDInterface(‘/media/storage/AIC2024_Track1_Nota/configs/reid/AIC/bagtricks_vit.yml’, ‘/media/storage/AIC2024_Track1_Nota/pretrained/transformer_120.pth’, ‘cuda’)
File “/media/storage/AIC2024_Track1_Nota/trackers/botsort/fast_reid_interfece.py”, line 68, in init
Checkpointer(self.model).load(weights_path)
File “/home/imslab/.local/lib/python3.8/site-packages/fastreid/utils/checkpoint.py”, line 123, in load
incompatible = self._load_model(checkpoint)
File “/home/imslab/.local/lib/python3.8/site-packages/fastreid/utils/checkpoint.py”, line 225, in _load_model
checkpoint_state_dict = checkpoint.pop(“model”)
KeyError: ‘model’
