### ISSUE TITLE
multi dataset prefix

### ISSUE THREAD

**Issue by fangwudi** [JDAI-CV/fast-reid#76]
In "fastreid/data/common.py" get_pids function use file_path to generate the prefix for multi-dataset. I think it's better to use the dataset's name instead; maybe the dataset class should have a variable for its name.

**Comment by L1aoXingyu** [comment]
Yes, I use a naive method to generate the prefix of datasets. I am considering to take your suggestion.

We can describe your proposal in more detail here, and we can give a discussion. 

Of curse, You are welcome to open a PR to fix this problem.
