### ISSUE TITLE
visualizer.py:

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#80]
visualizer.py:136: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.tight_layout()

哪位高手遇到过此问题，如何解决呢。多谢。偶是新手。

**Comment by L1aoXingyu** [comment]
这只是 warning，没有关系，你可以查看一下是否生成了 ranklist
