### ISSUE TITLE
请问可以自定义训练过程吗

### ISSUE THREAD

**Issue by houhaopeng** [JDAI-CV/fast-reid#81]

**Comment by L1aoXingyu** [comment]
如果你的训练逻辑很简单，那么可以通过加 `hook` 来实现，如果你想完全重写一个训练过程，你可以参考 `DefaultTrainer` 来完全重写，主要的模型训练在 `run_step` 这个函数中

https://github.com/JDAI-CV/fast-reid/blob/e7156e1cfa307f9b3c61a124681541cd88bb027d/fastreid/engine/defaults.py#L160

https://github.com/JDAI-CV/fast-reid/blob/e7156e1cfa307f9b3c61a124681541cd88bb027d/fastreid/engine/train_loop.py#L186

**Comment by houhaopeng** [comment]
你好,廖博士,我需要用到多个模型,还要用到多个数据库,请问一下,这个框架可以支持吗,感觉需要改很多地方呀

**Comment by L1aoXingyu** [comment]
多数据集现在是直接支持的，你使用下面的方式
```
DATASETS:
  NAMES: ("DukeMTMC", "Market1501",)
  TESTS: ("DukeMTMC",)
```
多模型的话，可以把他们都写在一个 `meta_arch` 里面应该是没问题的
