### ISSUE TITLE
deployment caffe error

### ISSUE THREAD

**Issue by huangzhenjie** [JDAI-CV/fast-reid#84]
when i try to converts a fastreid model to Caffe format. I follow the tutorial step by step, when I run caffe_export.py to get the converted Caffe model(python caffe_export.py --config-file "/home/hhh/Project/Pytorch/Deep_Learning/fast-reid/logs/market1501/sbs_R50/config.yaml" --name "baseline_R50" --output "logs/caffe_model" --opts MODEL.WEIGHTS "/home/hhh/Project/Pytorch/Deep_Learning/fast-reid_2020_6_3/logs/market1501/sbs_R50/model_final.pth" ), the following error occurred 
Traceback (most recent call last):
  File "caffe_export.py", line 72, in <module>
    pytorch_to_caffe.trans_net(model, inputs, args.name)
  File "/home/hhh/Project/Pytorch/Deep_Learning/fast-reid_2020_6_3/tools/deploy/pytorch_to_caffe.py", line 775, in trans_net
    out = net.forward(input_var)
  File "../../fastreid/modeling/meta_arch/baseline.py", line 50, in forward
    return pred_feat, batched_inputs["targets"], batched_inputs["camid"]
IndexError: too many indices for tensor of dimension 4

how should I do? thanks

**Comment by L1aoXingyu** [comment]
fixed, please update and try again.

**Comment by huangzhenjie** [comment]
thanks
