### ISSUE TITLE
Caffe deploy error

### ISSUE THREAD

**Issue by huangzhenjie** [JDAI-CV/fast-reid#86]
when I Run caffe_inference.py, the error as follow:

Traceback (most recent call last):
  File "caffe_inference.py", line 9, in <module>
    import caffe
ModuleNotFoundError: No module named 'caffe'

what should i do? thanks

**Comment by L1aoXingyu** [comment]
you need to install `caffe`.

Please refer [this](https://blog.csdn.net/weixin_39916966/article/details/93221564).

**Comment by huangzhenjie** [comment]
thanks

**Comment by gmt710** [comment]
@huangzhenjie Hello,I see that you are also working on converting torch to Caffe. Would you mind asking whether your inference is correct?
