### ISSUE TITLE
tensorrt

### ISSUE THREAD

**Issue by zhanghongruiupup** [JDAI-CV/fast-reid#91]
你好，感谢您更新了对tensorrt的支持，请问 resnet50_ibn能转换成tensorrt吗？谢谢

**Comment by L1aoXingyu** [comment]
> 你好，感谢您更新了对tensorrt的支持，请问 resnet50_ibn能转换成tensorrt吗？谢谢

可以的，我们会尽快整理好代码

**Comment by zhanghongruiupup** [comment]
请问开源的基于resnet50转caffe的代码，这个resnet50是否包含non-local层？

**Comment by L1aoXingyu** [comment]
不包含，non-local 需要自己在 caffe 里面写 prototxt
