### ISSUE TITLE
evaluation process should depend on neck_feat‘s choice of before/after

### ISSUE THREAD

**Issue by fangwudi** [JDAI-CV/fast-reid#93]
In bnnneck_head.py line 40:
     " # Evaluation
        if not self.training: return bn_feat"  maybe should be modified as below:

"# Evaluation
        if not self.training: 
            if self.neck_feat == "before":  return global_feat[..., 0, 0]
            elif self.neck_feat == "after": return bn_feat
            else:
                raise KeyError("MODEL.HEADS.NECK_FEAT value is invalid, must choose from ('after' & 'before')")  "

Am I right?

**Comment by fangwudi** [comment]
@L1aoXingyu 帮忙看下~  neck_feat的befoe和after在Evaluation中没体现的问题

**Comment by L1aoXingyu** [comment]
我们默认大家最后用来测试的 feature 都是 bn 之后的，这个部分可能需要更多的人来讨论一下，因为如果加上之后大家都不用，那我倾向于还是不加这个特性。
