### ISSUE TITLE
关于测试部分的问题

### ISSUE THREAD

**Issue by finger-monkey** [JDAI-CV/fast-reid#95]
训练完FastReID (ResNet101-ibn) 模型之后，要如何编写测试命令开启QE和Rerank得到最高精度的结果？
+ QE 96.5 94.4 
+ Rerank 96.8 95.3 
能否给个模板命令？类似下面的：
python3 tools/test.py --config_file='configs/xxx.yml' \
MODEL.DEVICE_ID= '0' \
TEST.WEIGHT "('xxx.pth')"

**Comment by L1aoXingyu** [comment]
参考下面的默认配置文件，
https://github.com/JDAI-CV/fast-reid/blob/27c48c8f020772b7e2948db7a5e89e32add599b2/fastreid/config/defaults.py#L228
在 `config.yml` 里面加入对应的关键字就可以了

**Comment by finger-monkey** [comment]
抱歉，我还是没有弄清楚要怎么测试。我试图使用dataset_test.py进行测试您论文的最高精度（+QE 
+Rerank）并使用如下命令
CUDA_VISIBLE_DEVICES='1' python3  tests/dataset_test.py MODEL.WEIGHTS"('xxx/ model_final.pth')" DATASETS.NAMES(“Market1501”)"
TEST.AQE.ENABLED "(“True”)"
TEST.RERANK.ENABLED "(“True”)"
一方面dataset_test.py会报错：from data import get_dataloader 找不到包data.并且我找了一番没有get_dataloader函数代码所在位置，不知道会不会漏掉了一些文件？
另一方面，使用TEST.AQE.ENABLED "(“True”)"或TEST.AQE.ENABLED="True"会报错说找不到命令。
还望您能详细指点一下。

**Comment by L1aoXingyu** [comment]
sorry, 这是我们的疏忽，没有写清楚训练和测试该怎么做

其实测试非常简单，加上一个 `--eval-only` 的 flag 就行了

```bash
CUDA_VISIBLE_DEVICES=$gpus python tools/train_net.py --config-file "logs/market1501/sbs-R101-ibn/config.yaml" \
--eval-only  MODEL.WEIGHTS "logs/market1501/sbs-R101-ibn/model_final.pth"
```

这些说明文档应该是不小心被删掉了，我们会尽快加上。

**Comment by finger-monkey** [comment]
好像使用了reRank就会自动使用QE?可以设置单独使用reRank不用QE吗？

**Comment by finger-monkey** [comment]
请问训练迭代周期数在哪里可以更改？

**Comment by finger-monkey** [comment]
您好，我想请教一下您的模型实验精度误差大概有多大，我跑了两次QE、reank后精度差了近0.5%-1%。当然多跑几次应该就能得到您的结果 。另外想了解一下您实验过程中跑过的最高精度是多少？

**Comment by L1aoXingyu** [comment]
@finger-monkey 我就随便跑了一次，我并没有花时间跑这些后处理，我觉得没啥意义。

**Comment by finger-monkey** [comment]
好的，理解。咨询您最高精度只是想知道，之后在您的基础上做改进的化要达到多少才算是真正的提升，不至于在您的精度误差范围内造成提升的错觉。因为您的进度已经非常高了，接下来的改进提升空间会非常小。
