### ISSUE TITLE
归一化不匹配问题

### ISSUE THREAD

**Issue by fangwudi** [JDAI-CV/fast-reid#96]
build_transforms 中使用了ToTensor()，它最后会/255归一化到[0，1]，而Baseline模型中preprocess所用到的cfg.MODEL.PIXEL_MEAN、cfg.MODEL.PIXEL_STD按照default中填写的是*255的，这里是否是不匹配的？  我去看了reid-strong-baseline代码，是没有这个问题的。

**Comment by L1aoXingyu** [comment]
`ToTensor` 是我们自己实现的，并没有用 torchvision 的实现。

**Comment by fangwudi** [comment]
> `ToTensor` 是我们自己实现的，并没有用 torchvision 的实现。
> 
> https://github.com/JDAI-CV/fast-reid/blob/27c48c8f020772b7e2948db7a5e89e32add599b2/fastreid/data/transforms/functional.py#L12
> 
> 我们没有除 255。

好的，感谢。麻烦ToTensor 这个类的注释改一下。
class ToTensor(object):
    """Convert a ``PIL Image`` or ``numpy.ndarray`` to tensor.
    Converts a PIL Image or numpy.ndarray (H x W x C) in the range
    [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]

**Comment by L1aoXingyu** [comment]
抱歉，我们马上修改注释。
