### ISSUE TITLE
关于circleloss的使用

### ISSUE THREAD

**Issue by Mrqianduoduo** [JDAI-CV/fast-reid#98]
你好，我是用circle layer代替了我模型中的linear layer。在最后loss计算，直接使用score和label进行交叉熵loss。但是这样我得到的精度特别低，在veri数据集上只有60左右的MAP。因为我看你代码里面也是这么实现的，是有什么gap嘛

**Comment by L1aoXingyu** [comment]
你可以参考我的配置文件，里面有所有需要注意的细节。

https://github.com/JDAI-CV/fast-reid/blob/master/configs/VeRi/sbs_R50-ibn.yml

**Comment by Mrqianduoduo** [comment]
嗯，我是参照你的来的，但是还是这个样子，所以我有点疑惑

**Comment by L1aoXingyu** [comment]
我的 batch 是 4个id，每个id 16张图，这里是一个比较关键的地方。

**Comment by zoujialong9012** [comment]
弱弱打扰下，
BalancedIdentitySampler    batch sample没看出负样本sample 都是相同pid 选取。 NaiveIdentitySampler 才有取neg  过程？

**Comment by zoujialong9012** [comment]
打扰下 BalancedIdentitySampler batch sample没看出负样本sample 都是相同pid 选取。 NaiveIdentitySampler 才有取neg 过程？
