### ISSUE TITLE
circle loss

### ISSUE THREAD

**Issue by Wink-Xu** [JDAI-CV/fast-reid#99]
Great job! 
Recently, I want to use circle loss in my code. I just change the head . But using softmax loss I get Rank-1 92.4%,  using circle loss I only get Rank-1 72.3%. I found I dont use any sampler strategy, so I changed it like you. The Rank-1 of circle loss turns to be 88.8%. It is still lower than softmax loss.
Of course, many tricks in your code, I have not used now.So I want to know which tricks is vital to circle loss.
thx!

**Comment by L1aoXingyu** [comment]
Decrease the number of IDs in a batch is the key to boost performance.
